export type Sector =
  | "IT" | "Banks" | "NBFC" | "Auto" | "Pharma" | "FMCG" | "Energy"
  | "Metals" | "Telecom" | "Cement" | "Power" | "Insurance" | "Consumer"
  | "Realty" | "Capital Goods" | "Chemicals" | "Infrastructure"
  | "Media" | "Logistics" | "Textiles" | "Agri" | "Other";

export type SymbolEntry = {
  symbol: string;
  name: string;
  exchange: "NSE" | "BSE";
  sector: Sector;
  industry?: string;
};

// Universe: Nifty Total Market (~750 active large/mid/small/micro-cap NSE equities).
// Regenerated from scripts/nifty_total_market.csv via scripts/build-symbols.mjs.
// Sectors are preserved from prior manual classification where the symbol existed;
// new entries get auto-mapped from NSE's industry classification.
export const NSE_SYMBOLS: SymbolEntry[] = [
  { symbol: "360ONE", name: "360 ONE WAM", exchange: "NSE", sector: "NBFC", industry: "Financial Services" },
  { symbol: "3MINDIA", name: "3M India", exchange: "NSE", sector: "Other", industry: "Diversified" },
  { symbol: "ABB", name: "ABB India", exchange: "NSE", sector: "Capital Goods", industry: "Electrical Equipment" },
  { symbol: "ACC", name: "ACC", exchange: "NSE", sector: "Cement", industry: "Cement" },
  { symbol: "ACMESOLAR", name: "ACME Solar Holdings", exchange: "NSE", sector: "Power", industry: "Power" },
  { symbol: "AIAENG", name: "AIA Engineering", exchange: "NSE", sector: "Capital Goods", industry: "Grinding Media" },
  { symbol: "APLAPOLLO", name: "APL Apollo Tubes", exchange: "NSE", sector: "Metals", industry: "Steel Tubes" },
  { symbol: "ASKAUTOLTD", name: "ASK Automotive", exchange: "NSE", sector: "Auto", industry: "Automobile and Auto Components" },
  { symbol: "AUBANK", name: "AU Small Finance Bank", exchange: "NSE", sector: "Banks", industry: "Small Finance" },
  { symbol: "AWL", name: "AWL Agri Business", exchange: "NSE", sector: "FMCG", industry: "Fast Moving Consumer Goods" },
  { symbol: "AXISCADES", name: "AXISCADES Technologies", exchange: "NSE", sector: "Capital Goods", industry: "Capital Goods" },
  { symbol: "AADHARHFC", name: "Aadhar Housing Finance", exchange: "NSE", sector: "NBFC", industry: "Housing Finance" },
  { symbol: "AARTIDRUGS", name: "Aarti Drugs", exchange: "NSE", sector: "Pharma", industry: "Healthcare" },
  { symbol: "AARTIIND", name: "Aarti Industries", exchange: "NSE", sector: "Chemicals", industry: "Specialty Chemicals" },
  { symbol: "AARTIPHARM", name: "Aarti Pharmalabs", exchange: "NSE", sector: "Pharma", industry: "Healthcare" },
  { symbol: "AAVAS", name: "Aavas Financiers", exchange: "NSE", sector: "NBFC", industry: "Housing Finance" },
  { symbol: "ABBOTINDIA", name: "Abbott India", exchange: "NSE", sector: "Pharma", industry: "Pharmaceuticals" },
  { symbol: "ACE", name: "Action Construction Equipment", exchange: "NSE", sector: "Capital Goods", industry: "Capital Goods" },
  { symbol: "ACUTAAS", name: "Acutaas Chemicals", exchange: "NSE", sector: "Pharma", industry: "Healthcare" },
  { symbol: "ADANIENSOL", name: "Adani Energy Solutions", exchange: "NSE", sector: "Power", industry: "Transmission" },
  { symbol: "ADANIENT", name: "Adani Enterprises", exchange: "NSE", sector: "Other", industry: "Diversified" },
  { symbol: "ADANIGREEN", name: "Adani Green Energy", exchange: "NSE", sector: "Power", industry: "Renewable Energy" },
  { symbol: "ADANIPORTS", name: "Adani Ports & SEZ", exchange: "NSE", sector: "Logistics", industry: "Ports" },
  { symbol: "ADANIPOWER", name: "Adani Power", exchange: "NSE", sector: "Power", industry: "Power Generation" },
  { symbol: "ATGL", name: "Adani Total Gas", exchange: "NSE", sector: "Energy", industry: "Oil Gas & Consumable Fuels" },
  { symbol: "ABCAPITAL", name: "Aditya Birla Capital", exchange: "NSE", sector: "NBFC", industry: "Diversified Financial" },
  { symbol: "ABFRL", name: "Aditya Birla Fashion", exchange: "NSE", sector: "Textiles", industry: "Apparel Retail" },
  { symbol: "ABLBL", name: "Aditya Birla Lifestyle Brands", exchange: "NSE", sector: "Consumer", industry: "Consumer Services" },
  { symbol: "ABREL", name: "Aditya Birla Real Estate", exchange: "NSE", sector: "Realty", industry: "Realty" },
  { symbol: "ABSLAMC", name: "Aditya Birla Sun Life AMC", exchange: "NSE", sector: "Insurance", industry: "Financial Services" },
  { symbol: "CPPLUS", name: "Aditya Infotech", exchange: "NSE", sector: "Capital Goods", industry: "Capital Goods" },
  { symbol: "AVL", name: "Aditya Vision", exchange: "NSE", sector: "Consumer", industry: "Consumer Services" },
  { symbol: "ADVENZYMES", name: "Advanced Enzyme Tech", exchange: "NSE", sector: "Pharma", industry: "Healthcare" },
  { symbol: "AEGISLOG", name: "Aegis Logistics", exchange: "NSE", sector: "Energy", industry: "Oil Gas & Consumable Fuels" },
  { symbol: "AEGISVOPAK", name: "Aegis Vopak Terminals", exchange: "NSE", sector: "Energy", industry: "Oil Gas & Consumable Fuels" },
  { symbol: "AEQUS", name: "Aequs", exchange: "NSE", sector: "Capital Goods", industry: "Capital Goods" },
  { symbol: "AETHER", name: "Aether Industries", exchange: "NSE", sector: "Chemicals", industry: "Specialty Chemicals" },
  { symbol: "AFCONS", name: "Afcons Infrastructure", exchange: "NSE", sector: "Infrastructure", industry: "Construction" },
  { symbol: "AFFLE", name: "Affle India", exchange: "NSE", sector: "IT", industry: "AdTech" },
  { symbol: "AHLUCONT", name: "Ahluwalia Contracts (India)", exchange: "NSE", sector: "Infrastructure", industry: "Construction" },
  { symbol: "AJANTPHARM", name: "Ajanta Pharma", exchange: "NSE", sector: "Pharma", industry: "Pharmaceuticals" },
  { symbol: "AKUMS", name: "Akums Drugs and Pharmaceuticals", exchange: "NSE", sector: "Pharma", industry: "Healthcare" },
  { symbol: "APLLTD", name: "Alembic Pharmaceuticals", exchange: "NSE", sector: "Pharma", industry: "Healthcare" },
  { symbol: "ALIVUS", name: "Alivus Life Sciences", exchange: "NSE", sector: "Pharma", industry: "Healthcare" },
  { symbol: "ALKEM", name: "Alkem Laboratories", exchange: "NSE", sector: "Pharma", industry: "Pharmaceuticals" },
  { symbol: "ALKYLAMINE", name: "Alkyl Amines Chemicals", exchange: "NSE", sector: "Chemicals", industry: "Specialty Chemicals" },
  { symbol: "ABDL", name: "Allied Blenders and Distillers", exchange: "NSE", sector: "FMCG", industry: "Fast Moving Consumer Goods" },
  { symbol: "ALOKINDS", name: "Alok Industries", exchange: "NSE", sector: "Textiles", industry: "Textiles" },
  { symbol: "ARE&M", name: "Amara Raja Energy & Mobility", exchange: "NSE", sector: "Auto", industry: "Automobile and Auto Components" },
  { symbol: "AMBER", name: "Amber Enterprises", exchange: "NSE", sector: "Consumer", industry: "Consumer Durables" },
  { symbol: "AMBUJACEM", name: "Ambuja Cements", exchange: "NSE", sector: "Cement", industry: "Cement" },
  { symbol: "ANANDRATHI", name: "Anand Rathi Wealth", exchange: "NSE", sector: "NBFC", industry: "Wealth Management" },
  { symbol: "ANANTRAJ", name: "Anant Raj", exchange: "NSE", sector: "Realty", industry: "Real Estate" },
  { symbol: "ANGELONE", name: "Angel One", exchange: "NSE", sector: "NBFC", industry: "Capital Markets" },
  { symbol: "ANTHEM", name: "Anthem Biosciences", exchange: "NSE", sector: "Pharma", industry: "Healthcare" },
  { symbol: "ANURAS", name: "Anupam Rasayan India", exchange: "NSE", sector: "Chemicals", industry: "Chemicals" },
  { symbol: "APARINDS", name: "Apar Industries", exchange: "NSE", sector: "Capital Goods", industry: "Capital Goods" },
  { symbol: "APOLLOHOSP", name: "Apollo Hospitals", exchange: "NSE", sector: "Pharma", industry: "Healthcare Services" },
  { symbol: "APOLLO", name: "Apollo Micro Systems", exchange: "NSE", sector: "Capital Goods", industry: "Capital Goods" },
  { symbol: "APOLLOTYRE", name: "Apollo Tyres", exchange: "NSE", sector: "Auto", industry: "Tyres" },
  { symbol: "APTUS", name: "Aptus Value Housing Finance", exchange: "NSE", sector: "NBFC", industry: "Housing Finance" },
  { symbol: "ACI", name: "Archean Chemical Industries", exchange: "NSE", sector: "Chemicals", industry: "Chemicals" },
  { symbol: "ARVINDFASN", name: "Arvind Fashions", exchange: "NSE", sector: "Consumer", industry: "Consumer Services" },
  { symbol: "ARVIND", name: "Arvind", exchange: "NSE", sector: "Textiles", industry: "Denim & Apparel" },
  { symbol: "ASAHIINDIA", name: "Asahi India Glass", exchange: "NSE", sector: "Auto", industry: "Automobile and Auto Components" },
  { symbol: "ASHAPURMIN", name: "Ashapura Minechem", exchange: "NSE", sector: "Metals", industry: "Metals & Mining" },
  { symbol: "ASHOKLEY", name: "Ashok Leyland", exchange: "NSE", sector: "Auto", industry: "Commercial Vehicles" },
  { symbol: "ASHOKA", name: "Ashoka Buildcon", exchange: "NSE", sector: "Infrastructure", industry: "Roads" },
  { symbol: "ASIANPAINT", name: "Asian Paints", exchange: "NSE", sector: "Consumer", industry: "Paints" },
  { symbol: "ASTERDM", name: "Aster DM Healthcare", exchange: "NSE", sector: "Pharma", industry: "Hospitals" },
  { symbol: "ASTRAMICRO", name: "Astra Microwave Products", exchange: "NSE", sector: "Capital Goods", industry: "Defence Electronics" },
  { symbol: "ASTRAL", name: "Astral", exchange: "NSE", sector: "Capital Goods", industry: "Plastics" },
  { symbol: "ATHERENERG", name: "Ather Energy", exchange: "NSE", sector: "Auto", industry: "Automobile and Auto Components" },
  { symbol: "ATLANTAELE", name: "Atlanta Electricals", exchange: "NSE", sector: "Capital Goods", industry: "Capital Goods" },
  { symbol: "ATUL", name: "Atul", exchange: "NSE", sector: "Chemicals", industry: "Specialty Chemicals" },
  { symbol: "AURIONPRO", name: "Aurionpro Solution", exchange: "NSE", sector: "IT", industry: "Information Technology" },
  { symbol: "AUROPHARMA", name: "Aurobindo Pharma", exchange: "NSE", sector: "Pharma", industry: "Pharmaceuticals" },
  { symbol: "AIIL", name: "Authum Investment & Infrastructure", exchange: "NSE", sector: "NBFC", industry: "Financial Services" },
  { symbol: "AVALON", name: "Avalon Technologies", exchange: "NSE", sector: "Capital Goods", industry: "EMS" },
  { symbol: "AVANTIFEED", name: "Avanti Feeds", exchange: "NSE", sector: "Agri", industry: "Shrimp Feed" },
  { symbol: "DMART", name: "Avenue Supermarts", exchange: "NSE", sector: "Consumer", industry: "Retail" },
  { symbol: "CCAVENUE", name: "AvenuesAI", exchange: "NSE", sector: "NBFC", industry: "Financial Services" },
  { symbol: "AWFIS", name: "Awfis Space Solutions", exchange: "NSE", sector: "Other", industry: "Services" },
  { symbol: "AXISBANK", name: "Axis Bank", exchange: "NSE", sector: "Banks", industry: "Private Bank" },
  { symbol: "AZAD", name: "Azad Engineering", exchange: "NSE", sector: "Capital Goods", industry: "Capital Goods" },
  { symbol: "BEML", name: "BEML", exchange: "NSE", sector: "Capital Goods", industry: "Capital Goods" },
  { symbol: "BLS", name: "BLS International Services", exchange: "NSE", sector: "Consumer", industry: "Consumer Services" },
  { symbol: "BSE", name: "BSE", exchange: "NSE", sector: "Other", industry: "Exchange" },
  { symbol: "BAJAJ-AUTO", name: "Bajaj Auto", exchange: "NSE", sector: "Auto", industry: "Two Wheelers" },
  { symbol: "BAJAJELEC", name: "Bajaj Electricals", exchange: "NSE", sector: "Consumer", industry: "Electricals" },
  { symbol: "BAJFINANCE", name: "Bajaj Finance", exchange: "NSE", sector: "NBFC", industry: "Consumer Finance" },
  { symbol: "BAJAJFINSV", name: "Bajaj Finserv", exchange: "NSE", sector: "NBFC", industry: "Diversified Financial" },
  { symbol: "BAJAJHLDNG", name: "Bajaj Holdings", exchange: "NSE", sector: "NBFC", industry: "Holding Company" },
  { symbol: "BAJAJHFL", name: "Bajaj Housing Finance", exchange: "NSE", sector: "NBFC", industry: "Financial Services" },
  { symbol: "BALAMINES", name: "Balaji Amines", exchange: "NSE", sector: "Chemicals", industry: "Specialty Chemicals" },
  { symbol: "BALKRISIND", name: "Balkrishna Industries", exchange: "NSE", sector: "Auto", industry: "Tyres" },
  { symbol: "BALRAMCHIN", name: "Balrampur Chini Mills", exchange: "NSE", sector: "Agri", industry: "Sugar" },
  { symbol: "BALUFORGE", name: "Balu Forge Industries", exchange: "NSE", sector: "Capital Goods", industry: "Capital Goods" },
  { symbol: "BANCOINDIA", name: "Banco Products (India)", exchange: "NSE", sector: "Auto", industry: "Automobile and Auto Components" },
  { symbol: "BANDHANBNK", name: "Bandhan Bank", exchange: "NSE", sector: "Banks", industry: "Private Bank" },
  { symbol: "BANKBARODA", name: "Bank of Baroda", exchange: "NSE", sector: "Banks", industry: "Public Bank" },
  { symbol: "BANKINDIA", name: "Bank of India", exchange: "NSE", sector: "Banks", industry: "Financial Services" },
  { symbol: "MAHABANK", name: "Bank of Maharashtra", exchange: "NSE", sector: "Banks", industry: "PSU Bank" },
  { symbol: "BATAINDIA", name: "Bata India", exchange: "NSE", sector: "Consumer", industry: "Footwear" },
  { symbol: "BAYERCROP", name: "Bayer CropScience", exchange: "NSE", sector: "Chemicals", industry: "Agrochemicals" },
  { symbol: "BELRISE", name: "Belrise Industries", exchange: "NSE", sector: "Auto", industry: "Automobile and Auto Components" },
  { symbol: "BERGEPAINT", name: "Berger Paints", exchange: "NSE", sector: "Consumer", industry: "Paints" },
  { symbol: "BDL", name: "Bharat Dynamics", exchange: "NSE", sector: "Capital Goods", industry: "Defence" },
  { symbol: "BEL", name: "Bharat Electronics", exchange: "NSE", sector: "Capital Goods", industry: "Defence" },
  { symbol: "BHARATFORG", name: "Bharat Forge", exchange: "NSE", sector: "Auto", industry: "Auto Components" },
  { symbol: "BHEL", name: "BHEL", exchange: "NSE", sector: "Capital Goods", industry: "Power Equipment" },
  { symbol: "BPCL", name: "Bharat Petroleum", exchange: "NSE", sector: "Energy", industry: "Oil Marketing" },
  { symbol: "BHARTIARTL", name: "Bharti Airtel", exchange: "NSE", sector: "Telecom", industry: "Telecom Services" },
  { symbol: "BHARTIHEXA", name: "Bharti Hexacom", exchange: "NSE", sector: "Telecom", industry: "Telecom Services" },
  { symbol: "BIKAJI", name: "Bikaji Foods International", exchange: "NSE", sector: "FMCG", industry: "Snacks" },
  { symbol: "GROWW", name: "Billionbrains Garage Ventures", exchange: "NSE", sector: "NBFC", industry: "Financial Services" },
  { symbol: "BIOCON", name: "Biocon", exchange: "NSE", sector: "Pharma", industry: "Biotech" },
  { symbol: "BIRLACORPN", name: "Birla Corporation", exchange: "NSE", sector: "Cement", industry: "Cement" },
  { symbol: "BSOFT", name: "Birlasoft", exchange: "NSE", sector: "IT", industry: "Information Technology" },
  { symbol: "BBOX", name: "Black Box", exchange: "NSE", sector: "IT", industry: "Information Technology" },
  { symbol: "BLACKBUCK", name: "Blackbuck", exchange: "NSE", sector: "Other", industry: "Services" },
  { symbol: "BLUEDART", name: "Blue Dart Express", exchange: "NSE", sector: "Logistics", industry: "Courier" },
  { symbol: "BLUEJET", name: "Blue Jet Healthcare", exchange: "NSE", sector: "Pharma", industry: "Healthcare" },
  { symbol: "BLUESTARCO", name: "Blue Star", exchange: "NSE", sector: "Consumer", industry: "Cooling Products" },
  { symbol: "BLUESTONE", name: "BlueStone Jewellery and Lifestyle", exchange: "NSE", sector: "Consumer", industry: "Consumer Durables" },
  { symbol: "BBTC", name: "Bombay Burmah Trading Corporation", exchange: "NSE", sector: "FMCG", industry: "Fast Moving Consumer Goods" },
  { symbol: "BORORENEW", name: "Borosil Renewables", exchange: "NSE", sector: "Chemicals", industry: "Solar Glass" },
  { symbol: "BOSCHLTD", name: "Bosch", exchange: "NSE", sector: "Auto", industry: "Auto Components" },
  { symbol: "FIRSTCRY", name: "Brainbees Solutions", exchange: "NSE", sector: "Consumer", industry: "Consumer Services" },
  { symbol: "BRIGADE", name: "Brigade Enterprises", exchange: "NSE", sector: "Realty", industry: "Real Estate" },
  { symbol: "BRITANNIA", name: "Britannia Industries", exchange: "NSE", sector: "FMCG", industry: "Packaged Foods" },
  { symbol: "MAPMYINDIA", name: "C.E. Info Systems", exchange: "NSE", sector: "IT", industry: "Software Products" },
  { symbol: "CCL", name: "CCL Products (I)", exchange: "NSE", sector: "FMCG", industry: "Fast Moving Consumer Goods" },
  { symbol: "CESC", name: "CESC", exchange: "NSE", sector: "Power", industry: "Power Generation" },
  { symbol: "CGPOWER", name: "CG Power & Industrial Solutions", exchange: "NSE", sector: "Capital Goods", industry: "Electrical Equipment" },
  { symbol: "CIEINDIA", name: "CIE Automotive India", exchange: "NSE", sector: "Auto", industry: "Automobile and Auto Components" },
  { symbol: "CMSINFO", name: "CMS Info Systems", exchange: "NSE", sector: "Other", industry: "Services" },
  { symbol: "CORONA", name: "CORONA Remedies", exchange: "NSE", sector: "Pharma", industry: "Healthcare" },
  { symbol: "CRISIL", name: "CRISIL", exchange: "NSE", sector: "NBFC", industry: "Financial Services" },
  { symbol: "CSBBANK", name: "CSB Bank", exchange: "NSE", sector: "Banks", industry: "Private Bank" },
  { symbol: "CAMPUS", name: "Campus Activewear", exchange: "NSE", sector: "Consumer", industry: "Consumer Durables" },
  { symbol: "CANFINHOME", name: "Can Fin Homes", exchange: "NSE", sector: "NBFC", industry: "Housing Finance" },
  { symbol: "CANBK", name: "Canara Bank", exchange: "NSE", sector: "Banks", industry: "Public Bank" },
  { symbol: "CANHLIFE", name: "Canara HSBC Life Insurance Company", exchange: "NSE", sector: "Insurance", industry: "Financial Services" },
  { symbol: "CRAMC", name: "Canara Robeco Asset Management Company", exchange: "NSE", sector: "NBFC", industry: "Financial Services" },
  { symbol: "CAPILLARY", name: "Capillary Technologies India", exchange: "NSE", sector: "IT", industry: "Information Technology" },
  { symbol: "CAPLIPOINT", name: "Caplin Point Laboratories", exchange: "NSE", sector: "Pharma", industry: "Pharmaceuticals" },
  { symbol: "CGCL", name: "Capri Global Capital", exchange: "NSE", sector: "NBFC", industry: "Financial Services" },
  { symbol: "CARBORUNIV", name: "Carborundum Universal", exchange: "NSE", sector: "Capital Goods", industry: "Abrasives" },
  { symbol: "CARTRADE", name: "Cartrade Tech", exchange: "NSE", sector: "Consumer", industry: "Consumer Services" },
  { symbol: "CASTROLIND", name: "Castrol India", exchange: "NSE", sector: "Energy", industry: "Oil Gas & Consumable Fuels" },
  { symbol: "CEATLTD", name: "CEAT", exchange: "NSE", sector: "Auto", industry: "Tyres" },
  { symbol: "CELLO", name: "Cello World", exchange: "NSE", sector: "Consumer", industry: "Consumer Durables" },
  { symbol: "CEMPRO", name: "Cemindia Projects", exchange: "NSE", sector: "Infrastructure", industry: "Construction" },
  { symbol: "CENTRALBK", name: "Central Bank of India", exchange: "NSE", sector: "Banks", industry: "PSU Bank" },
  { symbol: "CDSL", name: "Central Depository Services", exchange: "NSE", sector: "Other", industry: "Depository" },
  { symbol: "CENTURYPLY", name: "Century Plyboards", exchange: "NSE", sector: "Other", industry: "Plywood" },
  { symbol: "CERA", name: "Cera Sanitaryware", exchange: "NSE", sector: "Consumer", industry: "Sanitaryware" },
  { symbol: "CHALET", name: "Chalet Hotels", exchange: "NSE", sector: "Consumer", industry: "Hotels" },
  { symbol: "CHAMBLFERT", name: "Chambal Fertilisers", exchange: "NSE", sector: "Chemicals", industry: "Fertilisers" },
  { symbol: "CHENNPETRO", name: "Chennai Petroleum Corporation", exchange: "NSE", sector: "Energy", industry: "Oil Gas & Consumable Fuels" },
  { symbol: "CHOICEIN", name: "Choice International", exchange: "NSE", sector: "NBFC", industry: "Financial Services" },
  { symbol: "CHOLAHLDNG", name: "Cholamandalam Financial Holdings", exchange: "NSE", sector: "NBFC", industry: "Diversified Financial" },
  { symbol: "CHOLAFIN", name: "Cholamandalam Investment", exchange: "NSE", sector: "NBFC", industry: "Consumer Finance" },
  { symbol: "CIPLA", name: "Cipla", exchange: "NSE", sector: "Pharma", industry: "Pharmaceuticals" },
  { symbol: "CUB", name: "City Union Bank", exchange: "NSE", sector: "Banks", industry: "Financial Services" },
  { symbol: "CLEAN", name: "Clean Science & Technology", exchange: "NSE", sector: "Chemicals", industry: "Specialty Chemicals" },
  { symbol: "COALINDIA", name: "Coal India", exchange: "NSE", sector: "Energy", industry: "Coal" },
  { symbol: "COCHINSHIP", name: "Cochin Shipyard", exchange: "NSE", sector: "Capital Goods", industry: "Defence" },
  { symbol: "COFORGE", name: "Coforge", exchange: "NSE", sector: "IT", industry: "IT Services" },
  { symbol: "COHANCE", name: "Cohance Lifesciences", exchange: "NSE", sector: "Pharma", industry: "Healthcare" },
  { symbol: "COLPAL", name: "Colgate-Palmolive India", exchange: "NSE", sector: "FMCG", industry: "Personal Care" },
  { symbol: "CAMS", name: "Computer Age Management Services", exchange: "NSE", sector: "NBFC", industry: "Capital Markets" },
  { symbol: "CONCORDBIO", name: "Concord Biotech", exchange: "NSE", sector: "Pharma", industry: "Healthcare" },
  { symbol: "CONCOR", name: "Container Corporation", exchange: "NSE", sector: "Logistics", industry: "Container Logistics" },
  { symbol: "COROMANDEL", name: "Coromandel International", exchange: "NSE", sector: "Chemicals", industry: "Fertilisers" },
  { symbol: "CRAFTSMAN", name: "Craftsman Automation", exchange: "NSE", sector: "Auto", industry: "Automobile and Auto Components" },
  { symbol: "CREDITACC", name: "CreditAccess Grameen", exchange: "NSE", sector: "NBFC", industry: "Microfinance" },
  { symbol: "CRIZAC", name: "Crizac", exchange: "NSE", sector: "Consumer", industry: "Consumer Services" },
  { symbol: "CROMPTON", name: "Crompton Greaves Consumer", exchange: "NSE", sector: "Consumer", industry: "Consumer Electronics" },
  { symbol: "CUMMINSIND", name: "Cummins India", exchange: "NSE", sector: "Capital Goods", industry: "Industrial Engg" },
  { symbol: "CUPID", name: "Cupid", exchange: "NSE", sector: "FMCG", industry: "Fast Moving Consumer Goods" },
  { symbol: "CYIENT", name: "Cyient", exchange: "NSE", sector: "IT", industry: "Engineering R&D" },
  { symbol: "DCBBANK", name: "DCB Bank", exchange: "NSE", sector: "Banks", industry: "Private Bank" },
  { symbol: "DCMSHRIRAM", name: "DCM Shriram", exchange: "NSE", sector: "Chemicals", industry: "Diversified" },
  { symbol: "DLF", name: "DLF", exchange: "NSE", sector: "Realty", industry: "Real Estate" },
  { symbol: "DOMS", name: "DOMS Industries", exchange: "NSE", sector: "FMCG", industry: "Fast Moving Consumer Goods" },
  { symbol: "DABUR", name: "Dabur India", exchange: "NSE", sector: "FMCG", industry: "Personal Care" },
  { symbol: "DALBHARAT", name: "Dalmia Bharat", exchange: "NSE", sector: "Cement", industry: "Cement" },
  { symbol: "DATAPATTNS", name: "Data Patterns", exchange: "NSE", sector: "Capital Goods", industry: "Defence" },
  { symbol: "DATAMATICS", name: "Datamatics Global Services", exchange: "NSE", sector: "IT", industry: "Information Technology" },
  { symbol: "DEEPAKFERT", name: "Deepak Fertilisers", exchange: "NSE", sector: "Chemicals", industry: "Fertilisers" },
  { symbol: "DEEPAKNTR", name: "Deepak Nitrite", exchange: "NSE", sector: "Chemicals", industry: "Specialty Chemicals" },
  { symbol: "DELHIVERY", name: "Delhivery", exchange: "NSE", sector: "Logistics", industry: "Courier" },
  { symbol: "DEVYANI", name: "Devyani International", exchange: "NSE", sector: "Consumer", industry: "Restaurants" },
  { symbol: "DIACABS", name: "Diamond Power Infrastructure", exchange: "NSE", sector: "Capital Goods", industry: "Capital Goods" },
  { symbol: "DBL", name: "Dilip Buildcon", exchange: "NSE", sector: "Infrastructure", industry: "Roads" },
  { symbol: "DIVISLAB", name: "Divis Laboratories", exchange: "NSE", sector: "Pharma", industry: "Pharmaceuticals" },
  { symbol: "DIXON", name: "Dixon Technologies", exchange: "NSE", sector: "Consumer", industry: "Consumer Electronics" },
  { symbol: "AGARWALEYE", name: "Dr. Agarwal's Health Care", exchange: "NSE", sector: "Pharma", industry: "Healthcare" },
  { symbol: "LALPATHLAB", name: "Dr. Lal Path Labs", exchange: "NSE", sector: "Pharma", industry: "Healthcare" },
  { symbol: "DRREDDY", name: "Dr Reddys Laboratories", exchange: "NSE", sector: "Pharma", industry: "Pharmaceuticals" },
  { symbol: "DYNAMATECH", name: "Dynamatic Technologies", exchange: "NSE", sector: "Capital Goods", industry: "Capital Goods" },
  { symbol: "EIDPARRY", name: "EID Parry India", exchange: "NSE", sector: "Agri", industry: "Sugar" },
  { symbol: "EIHOTEL", name: "EIH (Oberoi Hotels)", exchange: "NSE", sector: "Consumer", industry: "Hotels" },
  { symbol: "EPL", name: "EPL", exchange: "NSE", sector: "Capital Goods", industry: "Capital Goods" },
  { symbol: "EDELWEISS", name: "Edelweiss Financial Services", exchange: "NSE", sector: "NBFC", industry: "Diversified Financial" },
  { symbol: "EICHERMOT", name: "Eicher Motors", exchange: "NSE", sector: "Auto", industry: "Two Wheelers" },
  { symbol: "ELECON", name: "Elecon Engineering", exchange: "NSE", sector: "Capital Goods", industry: "Industrial Gears" },
  { symbol: "EMIL", name: "Electronics Mart India", exchange: "NSE", sector: "Consumer", industry: "Consumer Services" },
  { symbol: "ELECTCAST", name: "Electrosteel Castings", exchange: "NSE", sector: "Capital Goods", industry: "Capital Goods" },
  { symbol: "ELGIEQUIP", name: "Elgi Equipments", exchange: "NSE", sector: "Capital Goods", industry: "Compressors" },
  { symbol: "ELLEN", name: "Ellenbarrie Industrial Gases", exchange: "NSE", sector: "Chemicals", industry: "Chemicals" },
  { symbol: "EMAMILTD", name: "Emami", exchange: "NSE", sector: "FMCG", industry: "Personal Care" },
  { symbol: "EMBDL", name: "Embassy Developments", exchange: "NSE", sector: "Realty", industry: "Realty" },
  { symbol: "EMCURE", name: "Emcure Pharmaceuticals", exchange: "NSE", sector: "Pharma", industry: "Healthcare" },
  { symbol: "EMMVEE", name: "Emmvee Photovoltaic Power", exchange: "NSE", sector: "Capital Goods", industry: "Capital Goods" },
  { symbol: "ENDURANCE", name: "Endurance Technologies", exchange: "NSE", sector: "Auto", industry: "Auto Components" },
  { symbol: "ENGINERSIN", name: "Engineers India", exchange: "NSE", sector: "Infrastructure", industry: "Consultancy" },
  { symbol: "ENTERO", name: "Entero Healthcare Solutions", exchange: "NSE", sector: "Pharma", industry: "Distribution" },
  { symbol: "EIEL", name: "Enviro Infra Engineers", exchange: "NSE", sector: "Power", industry: "Utilities" },
  { symbol: "EQUITASBNK", name: "Equitas Small Finance Bank", exchange: "NSE", sector: "Banks", industry: "Small Finance Bank" },
  { symbol: "ERIS", name: "Eris Lifesciences", exchange: "NSE", sector: "Pharma", industry: "Pharmaceuticals" },
  { symbol: "ESCORTS", name: "Escorts Kubota", exchange: "NSE", sector: "Auto", industry: "Tractors" },
  { symbol: "ETERNAL", name: "Eternal", exchange: "NSE", sector: "Consumer", industry: "Consumer Services" },
  { symbol: "ETHOSLTD", name: "Ethos", exchange: "NSE", sector: "Consumer", industry: "Consumer Durables" },
  { symbol: "EUREKAFORB", name: "Eureka Forbes", exchange: "NSE", sector: "Consumer", industry: "Consumer Durables" },
  { symbol: "EXIDEIND", name: "Exide Industries", exchange: "NSE", sector: "Auto", industry: "Batteries" },
  { symbol: "NYKAA", name: "FSN E-Commerce Ventures", exchange: "NSE", sector: "Consumer", industry: "Internet" },
  { symbol: "FEDFINA", name: "Fedbank Financial Services", exchange: "NSE", sector: "NBFC", industry: "Financial Services" },
  { symbol: "FEDERALBNK", name: "Federal Bank", exchange: "NSE", sector: "Banks", industry: "Private Bank" },
  { symbol: "FACT", name: "Fertilisers and Chemicals Travancore", exchange: "NSE", sector: "Chemicals", industry: "Fertilisers" },
  { symbol: "FIEMIND", name: "Fiem Industries", exchange: "NSE", sector: "Auto", industry: "Automobile and Auto Components" },
  { symbol: "FINCABLES", name: "Finolex Cables", exchange: "NSE", sector: "Capital Goods", industry: "Wires & Cables" },
  { symbol: "FINPIPE", name: "Finolex Industries", exchange: "NSE", sector: "Capital Goods", industry: "PVC Pipes" },
  { symbol: "FSL", name: "Firstsource Solutions", exchange: "NSE", sector: "IT", industry: "BPO" },
  { symbol: "FIVESTAR", name: "Five Star Business Finance", exchange: "NSE", sector: "NBFC", industry: "SME Finance" },
  { symbol: "FORCEMOT", name: "Force Motors", exchange: "NSE", sector: "Auto", industry: "Commercial Vehicles" },
  { symbol: "FORTIS", name: "Fortis Healthcare", exchange: "NSE", sector: "Pharma", industry: "Healthcare Services" },
  { symbol: "UTLSOLAR", name: "Fujiyama Power Systems", exchange: "NSE", sector: "Capital Goods", industry: "Capital Goods" },
  { symbol: "GAIL", name: "GAIL India", exchange: "NSE", sector: "Energy", industry: "Gas Distribution" },
  { symbol: "GVT&D", name: "GE Vernova T&D India", exchange: "NSE", sector: "Capital Goods", industry: "Capital Goods" },
  { symbol: "GHCL", name: "GHCL", exchange: "NSE", sector: "Chemicals", industry: "Soda Ash" },
  { symbol: "GMMPFAUDLR", name: "GMM Pfaudler", exchange: "NSE", sector: "Capital Goods", industry: "Capital Goods" },
  { symbol: "GMRAIRPORT", name: "GMR Airports", exchange: "NSE", sector: "Logistics", industry: "Services" },
  { symbol: "GMRP&UI", name: "GMR Power and Urban Infra", exchange: "NSE", sector: "Power", industry: "Power" },
  { symbol: "GABRIEL", name: "Gabriel India", exchange: "NSE", sector: "Auto", industry: "Auto Components" },
  { symbol: "GALLANTT", name: "Gallantt Ispat", exchange: "NSE", sector: "Capital Goods", industry: "Capital Goods" },
  { symbol: "GRSE", name: "Garden Reach Shipbuilders", exchange: "NSE", sector: "Capital Goods", industry: "Defence" },
  { symbol: "GRWRHITECH", name: "Garware Hi-Tech Films", exchange: "NSE", sector: "Capital Goods", industry: "Capital Goods" },
  { symbol: "GICRE", name: "General Insurance Corp of India", exchange: "NSE", sector: "Insurance", industry: "Reinsurance" },
  { symbol: "GILLETTE", name: "Gillette India", exchange: "NSE", sector: "FMCG", industry: "Fast Moving Consumer Goods" },
  { symbol: "GLAND", name: "Gland Pharma", exchange: "NSE", sector: "Pharma", industry: "Pharmaceuticals" },
  { symbol: "GLAXO", name: "GlaxoSmithKline Pharma", exchange: "NSE", sector: "Pharma", industry: "Pharmaceuticals" },
  { symbol: "GLENMARK", name: "Glenmark Pharmaceuticals", exchange: "NSE", sector: "Pharma", industry: "Pharmaceuticals" },
  { symbol: "MEDANTA", name: "Global Health (Medanta)", exchange: "NSE", sector: "Pharma", industry: "Hospitals" },
  { symbol: "GODIGIT", name: "Go Digit General Insurance", exchange: "NSE", sector: "Insurance", industry: "Financial Services" },
  { symbol: "GPIL", name: "Godawari Power & Ispat", exchange: "NSE", sector: "Capital Goods", industry: "Capital Goods" },
  { symbol: "GODFRYPHLP", name: "Godfrey Phillips India", exchange: "NSE", sector: "FMCG", industry: "Tobacco" },
  { symbol: "GODREJAGRO", name: "Godrej Agrovet", exchange: "NSE", sector: "Agri", industry: "Animal Feed" },
  { symbol: "GODREJCP", name: "Godrej Consumer Products", exchange: "NSE", sector: "FMCG", industry: "Personal Care" },
  { symbol: "GODREJIND", name: "Godrej Industries", exchange: "NSE", sector: "Other", industry: "Diversified" },
  { symbol: "GODREJPROP", name: "Godrej Properties", exchange: "NSE", sector: "Realty", industry: "Real Estate" },
  { symbol: "GOKEX", name: "Gokaldas Exports", exchange: "NSE", sector: "Textiles", industry: "Garments Export" },
  { symbol: "GOKULAGRO", name: "Gokul Agro Resources", exchange: "NSE", sector: "FMCG", industry: "Fast Moving Consumer Goods" },
  { symbol: "GRANULES", name: "Granules India", exchange: "NSE", sector: "Pharma", industry: "API" },
  { symbol: "GRAPHITE", name: "Graphite India", exchange: "NSE", sector: "Capital Goods", industry: "Capital Goods" },
  { symbol: "GRASIM", name: "Grasim Industries", exchange: "NSE", sector: "Cement", industry: "Cement" },
  { symbol: "GRAVITA", name: "Gravita India", exchange: "NSE", sector: "Metals", industry: "Lead Recycling" },
  { symbol: "GESHIP", name: "Great Eastern Shipping", exchange: "NSE", sector: "Logistics", industry: "Shipping" },
  { symbol: "GREAVESCOT", name: "Greaves Cotton", exchange: "NSE", sector: "Capital Goods", industry: "Engines" },
  { symbol: "GAEL", name: "Gujarat Ambuja Exports", exchange: "NSE", sector: "Chemicals", industry: "Agri Processing" },
  { symbol: "FLUOROCHEM", name: "Anupam Rasayan", exchange: "NSE", sector: "Chemicals", industry: "Specialty Chemicals" },
  { symbol: "GMDCLTD", name: "Gujarat Mineral Development Corporation", exchange: "NSE", sector: "Metals", industry: "Metals & Mining" },
  { symbol: "GNFC", name: "GNFC", exchange: "NSE", sector: "Chemicals", industry: "Fertilisers" },
  { symbol: "GPPL", name: "Gujarat Pipavav Port", exchange: "NSE", sector: "Logistics", industry: "Services" },
  { symbol: "GSFC", name: "Gujarat State Fertilizers", exchange: "NSE", sector: "Chemicals", industry: "Fertilisers" },
  { symbol: "HEG", name: "H.E.G.", exchange: "NSE", sector: "Capital Goods", industry: "Capital Goods" },
  { symbol: "HGINFRA", name: "H.G. Infra Engineering", exchange: "NSE", sector: "Infrastructure", industry: "Roads" },
  { symbol: "HBLENGINE", name: "HBL Engineering", exchange: "NSE", sector: "Capital Goods", industry: "Capital Goods" },
  { symbol: "HCLTECH", name: "HCL Technologies", exchange: "NSE", sector: "IT", industry: "IT Services" },
  { symbol: "HDBFS", name: "HDB Financial Services", exchange: "NSE", sector: "NBFC", industry: "Financial Services" },
  { symbol: "HDFCAMC", name: "HDFC Asset Management", exchange: "NSE", sector: "NBFC", industry: "Asset Management" },
  { symbol: "HDFCBANK", name: "HDFC Bank", exchange: "NSE", sector: "Banks", industry: "Private Bank" },
  { symbol: "HDFCLIFE", name: "HDFC Life Insurance", exchange: "NSE", sector: "Insurance", industry: "Life Insurance" },
  { symbol: "HFCL", name: "HFCL", exchange: "NSE", sector: "Telecom", industry: "Telecom Equipment" },
  { symbol: "HAPPSTMNDS", name: "Happiest Minds Technologies", exchange: "NSE", sector: "IT", industry: "IT Services" },
  { symbol: "HAVELLS", name: "Havells India", exchange: "NSE", sector: "Consumer", industry: "Consumer Electronics" },
  { symbol: "HCG", name: "Healthcare Global Enterprises", exchange: "NSE", sector: "Pharma", industry: "Healthcare" },
  { symbol: "HEMIPROP", name: "Hemisphere Properties India", exchange: "NSE", sector: "Other", industry: "Services" },
  { symbol: "HERITGFOOD", name: "Heritage Foods", exchange: "NSE", sector: "FMCG", industry: "Dairy" },
  { symbol: "HEROMOTOCO", name: "Hero MotoCorp", exchange: "NSE", sector: "Auto", industry: "Two Wheelers" },
  { symbol: "HEXT", name: "Hexaware Technologies", exchange: "NSE", sector: "IT", industry: "Information Technology" },
  { symbol: "HSCL", name: "Himadri Speciality Chemical", exchange: "NSE", sector: "Chemicals", industry: "Chemicals" },
  { symbol: "HINDALCO", name: "Hindalco Industries", exchange: "NSE", sector: "Metals", industry: "Aluminium" },
  { symbol: "HAL", name: "Hindustan Aeronautics", exchange: "NSE", sector: "Capital Goods", industry: "Defence" },
  { symbol: "HCC", name: "Hindustan Construction", exchange: "NSE", sector: "Infrastructure", industry: "Construction" },
  { symbol: "HINDCOPPER", name: "Hindustan Copper", exchange: "NSE", sector: "Metals", industry: "Copper" },
  { symbol: "HINDPETRO", name: "Hindustan Petroleum", exchange: "NSE", sector: "Energy", industry: "Oil Marketing" },
  { symbol: "HINDUNILVR", name: "Hindustan Unilever", exchange: "NSE", sector: "FMCG", industry: "Personal Care" },
  { symbol: "HINDZINC", name: "Hindustan Zinc", exchange: "NSE", sector: "Metals", industry: "Zinc" },
  { symbol: "POWERINDIA", name: "Hitachi Energy India", exchange: "NSE", sector: "Power", industry: "Power Equipment" },
  { symbol: "HOMEFIRST", name: "Home First Finance", exchange: "NSE", sector: "NBFC", industry: "Housing Finance" },
  { symbol: "HONASA", name: "Honasa Consumer (Mamaearth)", exchange: "NSE", sector: "FMCG", industry: "Personal Care" },
  { symbol: "HONAUT", name: "Honeywell Automation", exchange: "NSE", sector: "Capital Goods", industry: "Industrial Automation" },
  { symbol: "HUDCO", name: "Housing & Urban Development Corp", exchange: "NSE", sector: "NBFC", industry: "Housing Finance" },
  { symbol: "HYUNDAI", name: "Hyundai Motor India", exchange: "NSE", sector: "Auto", industry: "Automobile and Auto Components" },
  { symbol: "ICICIBANK", name: "ICICI Bank", exchange: "NSE", sector: "Banks", industry: "Private Bank" },
  { symbol: "ICICIGI", name: "ICICI Lombard General Insurance", exchange: "NSE", sector: "Insurance", industry: "General Insurance" },
  { symbol: "ICICIAMC", name: "ICICI Prudential Asset Management Company", exchange: "NSE", sector: "NBFC", industry: "Financial Services" },
  { symbol: "ICICIPRULI", name: "ICICI Prudential Life", exchange: "NSE", sector: "Insurance", industry: "Life Insurance" },
  { symbol: "IDBI", name: "IDBI Bank", exchange: "NSE", sector: "Banks", industry: "Private Bank" },
  { symbol: "IDFCFIRSTB", name: "IDFC First Bank", exchange: "NSE", sector: "Banks", industry: "Private Bank" },
  { symbol: "IFBIND", name: "IFB Industries", exchange: "NSE", sector: "Consumer", industry: "Home Appliances" },
  { symbol: "IFCI", name: "IFCI", exchange: "NSE", sector: "NBFC", industry: "Financial Services" },
  { symbol: "IIFLCAPS", name: "IIFL Capital Services", exchange: "NSE", sector: "NBFC", industry: "Financial Services" },
  { symbol: "IIFL", name: "IIFL Finance", exchange: "NSE", sector: "NBFC", industry: "Diversified NBFC" },
  { symbol: "INOXINDIA", name: "INOX India", exchange: "NSE", sector: "Capital Goods", industry: "Capital Goods" },
  { symbol: "IRB", name: "IRB Infrastructure", exchange: "NSE", sector: "Infrastructure", industry: "Roads" },
  { symbol: "IRCON", name: "Ircon International", exchange: "NSE", sector: "Infrastructure", industry: "Railways" },
  { symbol: "ITCHOTELS", name: "ITC Hotels", exchange: "NSE", sector: "Consumer", industry: "Consumer Services" },
  { symbol: "ITC", name: "ITC", exchange: "NSE", sector: "FMCG", industry: "Diversified FMCG" },
  { symbol: "ITI", name: "ITI Limited", exchange: "NSE", sector: "Telecom", industry: "Telecom Equipment" },
  { symbol: "INDGN", name: "Indegene", exchange: "NSE", sector: "Pharma", industry: "Healthcare" },
  { symbol: "INDIACEM", name: "India Cements", exchange: "NSE", sector: "Cement", industry: "Cement" },
  { symbol: "INDIAGLYCO", name: "India Glycols", exchange: "NSE", sector: "FMCG", industry: "Fast Moving Consumer Goods" },
  { symbol: "INDIASHLTR", name: "India Shelter Finance", exchange: "NSE", sector: "NBFC", industry: "Housing Finance" },
  { symbol: "INDIAMART", name: "IndiaMART InterMESH", exchange: "NSE", sector: "IT", industry: "B2B Internet" },
  { symbol: "INDIANB", name: "Indian Bank", exchange: "NSE", sector: "Banks", industry: "Public Bank" },
  { symbol: "IEX", name: "Indian Energy Exchange", exchange: "NSE", sector: "NBFC", industry: "Financial Services" },
  { symbol: "INDHOTEL", name: "Indian Hotels (Taj)", exchange: "NSE", sector: "Consumer", industry: "Hotels" },
  { symbol: "IMFA", name: "Indian Metals & Ferro Alloys", exchange: "NSE", sector: "Metals", industry: "Metals & Mining" },
  { symbol: "IOC", name: "Indian Oil Corporation", exchange: "NSE", sector: "Energy", industry: "Oil Marketing" },
  { symbol: "IOB", name: "Indian Overseas Bank", exchange: "NSE", sector: "Banks", industry: "PSU Bank" },
  { symbol: "IRCTC", name: "Indian Railway Catering", exchange: "NSE", sector: "Logistics", industry: "Travel" },
  { symbol: "IRFC", name: "Indian Railway Finance", exchange: "NSE", sector: "NBFC", industry: "Infra Finance" },
  { symbol: "IREDA", name: "Indian Renewable Energy", exchange: "NSE", sector: "NBFC", industry: "Infra Finance" },
  { symbol: "INDIGOPNTS", name: "Indigo Paints", exchange: "NSE", sector: "Chemicals", industry: "Paints" },
  { symbol: "ICIL", name: "Indo Count Industries", exchange: "NSE", sector: "Textiles", industry: "Textiles" },
  { symbol: "IGL", name: "Indraprastha Gas", exchange: "NSE", sector: "Energy", industry: "Gas Distribution" },
  { symbol: "INDUSTOWER", name: "Indus Towers", exchange: "NSE", sector: "Telecom", industry: "Telecom Infra" },
  { symbol: "INDUSINDBK", name: "IndusInd Bank", exchange: "NSE", sector: "Banks", industry: "Private Bank" },
  { symbol: "NAUKRI", name: "Info Edge", exchange: "NSE", sector: "IT", industry: "Internet" },
  { symbol: "INFY", name: "Infosys", exchange: "NSE", sector: "IT", industry: "IT Services" },
  { symbol: "INOXGREEN", name: "Inox Green Energy Services", exchange: "NSE", sector: "Other", industry: "Services" },
  { symbol: "INOXWIND", name: "Inox Wind", exchange: "NSE", sector: "Power", industry: "Wind Equipment" },
  { symbol: "INTELLECT", name: "Intellect Design Arena", exchange: "NSE", sector: "IT", industry: "Software Products" },
  { symbol: "INDIGO", name: "InterGlobe Aviation (IndiGo)", exchange: "NSE", sector: "Consumer", industry: "Airlines" },
  { symbol: "IGIL", name: "International Gemological Institute", exchange: "NSE", sector: "Other", industry: "Services" },
  { symbol: "IKS", name: "Inventurus Knowledge Solutions", exchange: "NSE", sector: "IT", industry: "Information Technology" },
  { symbol: "IONEXCHANG", name: "Ion Exchange (India)", exchange: "NSE", sector: "Power", industry: "Utilities" },
  { symbol: "IPCALAB", name: "IPCA Laboratories", exchange: "NSE", sector: "Pharma", industry: "Pharmaceuticals" },
  { symbol: "JBCHEPHARM", name: "J B Chemicals", exchange: "NSE", sector: "Pharma", industry: "Pharmaceuticals" },
  { symbol: "JKCEMENT", name: "JK Cement", exchange: "NSE", sector: "Cement", industry: "Cement" },
  { symbol: "JBMA", name: "JBM Auto", exchange: "NSE", sector: "Auto", industry: "Auto Components" },
  { symbol: "JKLAKSHMI", name: "JK Lakshmi Cement", exchange: "NSE", sector: "Cement", industry: "Cement" },
  { symbol: "JKPAPER", name: "JK Paper", exchange: "NSE", sector: "Other", industry: "Forest Materials" },
  { symbol: "JKTYRE", name: "JK Tyre & Industries", exchange: "NSE", sector: "Auto", industry: "Tyres" },
  { symbol: "JMFINANCIL", name: "JM Financial", exchange: "NSE", sector: "NBFC", industry: "Financial Services" },
  { symbol: "JSWCEMENT", name: "JSW Cement", exchange: "NSE", sector: "Cement", industry: "Construction Materials" },
  { symbol: "JSWDULUX", name: "JSW Dulux", exchange: "NSE", sector: "Consumer", industry: "Consumer Durables" },
  { symbol: "JSWENERGY", name: "JSW Energy", exchange: "NSE", sector: "Power", industry: "Power Generation" },
  { symbol: "JSWINFRA", name: "JSW Infrastructure", exchange: "NSE", sector: "Logistics", industry: "Ports" },
  { symbol: "JSWSTEEL", name: "JSW Steel", exchange: "NSE", sector: "Metals", industry: "Iron & Steel" },
  { symbol: "JAIBALAJI", name: "Jai Balaji Industries", exchange: "NSE", sector: "Metals", industry: "Metals & Mining" },
  { symbol: "JAINREC", name: "Jain Resource Recycling", exchange: "NSE", sector: "Metals", industry: "Metals & Mining" },
  { symbol: "JPPOWER", name: "Jaiprakash Power Ventures", exchange: "NSE", sector: "Power", industry: "Power" },
  { symbol: "J&KBANK", name: "Jammu & Kashmir Bank", exchange: "NSE", sector: "Banks", industry: "Financial Services" },
  { symbol: "JAMNAAUTO", name: "Jamna Auto Industries", exchange: "NSE", sector: "Auto", industry: "Automobile and Auto Components" },
  { symbol: "JSFB", name: "Jana Small Finance Bank", exchange: "NSE", sector: "Banks", industry: "Financial Services" },
  { symbol: "JAYNECOIND", name: "Jayaswal Neco Industries", exchange: "NSE", sector: "Capital Goods", industry: "Capital Goods" },
  { symbol: "JSLL", name: "Jeena Sikho Lifecare", exchange: "NSE", sector: "Consumer", industry: "Consumer Services" },
  { symbol: "JINDALSAW", name: "Jindal Saw", exchange: "NSE", sector: "Capital Goods", industry: "Steel Pipes" },
  { symbol: "JSL", name: "Jindal Stainless", exchange: "NSE", sector: "Metals", industry: "Stainless Steel" },
  { symbol: "JINDALSTEL", name: "Jindal Steel & Power", exchange: "NSE", sector: "Metals", industry: "Iron & Steel" },
  { symbol: "JIOFIN", name: "Jio Financial Services", exchange: "NSE", sector: "NBFC", industry: "Diversified Financial" },
  { symbol: "JUBLFOOD", name: "Jubilant FoodWorks", exchange: "NSE", sector: "Consumer", industry: "Restaurants" },
  { symbol: "JUBLINGREA", name: "Jubilant Ingrevia", exchange: "NSE", sector: "Chemicals", industry: "Specialty Chemicals" },
  { symbol: "JUBLPHARMA", name: "Jubilant Pharmova", exchange: "NSE", sector: "Pharma", industry: "Pharmaceuticals" },
  { symbol: "JLHL", name: "Jupiter Life Line Hospitals", exchange: "NSE", sector: "Pharma", industry: "Healthcare" },
  { symbol: "JWL", name: "Jupiter Wagons", exchange: "NSE", sector: "Capital Goods", industry: "Railway Wagons" },
  { symbol: "JUSTDIAL", name: "Just Dial", exchange: "NSE", sector: "IT", industry: "Internet" },
  { symbol: "JYOTHYLAB", name: "Jyothy Labs", exchange: "NSE", sector: "FMCG", industry: "Home Care" },
  { symbol: "JYOTICNC", name: "Jyoti CNC Automation", exchange: "NSE", sector: "Capital Goods", industry: "Capital Goods" },
  { symbol: "KPRMILL", name: "K.P.R. Mill", exchange: "NSE", sector: "Textiles", industry: "Garments" },
  { symbol: "KEI", name: "KEI Industries", exchange: "NSE", sector: "Capital Goods", industry: "Cables" },
  { symbol: "KNRCON", name: "KNR Constructions", exchange: "NSE", sector: "Infrastructure", industry: "Construction" },
  { symbol: "KPIGREEN", name: "KPI Green Energy", exchange: "NSE", sector: "Power", industry: "Power" },
  { symbol: "KPITTECH", name: "KPIT Technologies", exchange: "NSE", sector: "IT", industry: "Engineering R&D" },
  { symbol: "KRBL", name: "KRBL", exchange: "NSE", sector: "Agri", industry: "Basmati Rice" },
  { symbol: "KRN", name: "KRN Heat Exchanger and Refrigeration", exchange: "NSE", sector: "Capital Goods", industry: "Capital Goods" },
  { symbol: "KSB", name: "KSB", exchange: "NSE", sector: "Capital Goods", industry: "Pumps" },
  { symbol: "KAJARIACER", name: "Kajaria Ceramics", exchange: "NSE", sector: "Consumer", industry: "Ceramics" },
  { symbol: "KPIL", name: "Kalpataru Projects International", exchange: "NSE", sector: "Infrastructure", industry: "Construction" },
  { symbol: "KALYANKJIL", name: "Kalyan Jewellers", exchange: "NSE", sector: "Consumer", industry: "Jewellery" },
  { symbol: "KANSAINER", name: "Kansai Nerolac Paints", exchange: "NSE", sector: "Chemicals", industry: "Paints" },
  { symbol: "KTKBANK", name: "Karnataka Bank", exchange: "NSE", sector: "Banks", industry: "Financial Services" },
  { symbol: "KARURVYSYA", name: "Karur Vysya Bank", exchange: "NSE", sector: "Banks", industry: "Private Bank" },
  { symbol: "KSCL", name: "Kaveri Seed Company", exchange: "NSE", sector: "FMCG", industry: "Fast Moving Consumer Goods" },
  { symbol: "KAYNES", name: "Kaynes Technology", exchange: "NSE", sector: "Capital Goods", industry: "EMS" },
  { symbol: "KEC", name: "KEC International", exchange: "NSE", sector: "Infrastructure", industry: "Transmission EPC" },
  { symbol: "KFINTECH", name: "KFin Technologies", exchange: "NSE", sector: "NBFC", industry: "Capital Markets" },
  { symbol: "KIRLOSBROS", name: "Kirloskar Brothers", exchange: "NSE", sector: "Capital Goods", industry: "Pumps" },
  { symbol: "KIRLOSENG", name: "Kirloskar Oil Engines", exchange: "NSE", sector: "Capital Goods", industry: "Engines" },
  { symbol: "KIRLPNU", name: "Kirloskar Pneumatic Company", exchange: "NSE", sector: "Capital Goods", industry: "Capital Goods" },
  { symbol: "KITEX", name: "Kitex Garments", exchange: "NSE", sector: "Textiles", industry: "Textiles" },
  { symbol: "KOTAKBANK", name: "Kotak Mahindra Bank", exchange: "NSE", sector: "Banks", industry: "Private Bank" },
  { symbol: "KIMS", name: "Krishna Institute of Medical Sciences", exchange: "NSE", sector: "Pharma", industry: "Hospitals" },
  { symbol: "LTF", name: "L&T Finance Holdings", exchange: "NSE", sector: "NBFC", industry: "Diversified NBFC" },
  { symbol: "LTTS", name: "L&T Technology Services", exchange: "NSE", sector: "IT", industry: "Engineering R&D" },
  { symbol: "LGEINDIA", name: "LG Electronics India", exchange: "NSE", sector: "Consumer", industry: "Consumer Durables" },
  { symbol: "LICHSGFIN", name: "LIC Housing Finance", exchange: "NSE", sector: "NBFC", industry: "Housing Finance" },
  { symbol: "LTFOODS", name: "LT Foods", exchange: "NSE", sector: "Agri", industry: "Basmati Rice" },
  { symbol: "LTM", name: "LTM", exchange: "NSE", sector: "IT", industry: "Information Technology" },
  { symbol: "LT", name: "Larsen & Toubro", exchange: "NSE", sector: "Infrastructure", industry: "Construction" },
  { symbol: "LATENTVIEW", name: "Latent View Analytics", exchange: "NSE", sector: "IT", industry: "Information Technology" },
  { symbol: "LAURUSLABS", name: "Laurus Labs", exchange: "NSE", sector: "Pharma", industry: "Pharmaceuticals" },
  { symbol: "LXCHEM", name: "Laxmi Organic Industries", exchange: "NSE", sector: "Chemicals", industry: "Chemicals" },
  { symbol: "IXIGO", name: "Le Travenues Technology", exchange: "NSE", sector: "Consumer", industry: "Consumer Services" },
  { symbol: "THELEELA", name: "Leela Palaces Hotels & Resorts", exchange: "NSE", sector: "Consumer", industry: "Consumer Services" },
  { symbol: "LEMONTREE", name: "Lemon Tree Hotels", exchange: "NSE", sector: "Consumer", industry: "Hotels" },
  { symbol: "LENSKART", name: "Lenskart Solutions", exchange: "NSE", sector: "Consumer", industry: "Consumer Services" },
  { symbol: "LICI", name: "Life Insurance Corporation", exchange: "NSE", sector: "Insurance", industry: "Life Insurance" },
  { symbol: "LINDEINDIA", name: "Linde India", exchange: "NSE", sector: "Chemicals", industry: "Chemicals" },
  { symbol: "LLOYDSENGG", name: "Lloyds Engineering Works", exchange: "NSE", sector: "Capital Goods", industry: "Capital Goods" },
  { symbol: "LLOYDSENT", name: "Lloyds Enterprises", exchange: "NSE", sector: "Metals", industry: "Metals & Mining" },
  { symbol: "LLOYDSME", name: "Lloyds Metals And Energy", exchange: "NSE", sector: "Metals", industry: "Metals & Mining" },
  { symbol: "LODHA", name: "Macrotech Developers (Lodha)", exchange: "NSE", sector: "Realty", industry: "Real Estate" },
  { symbol: "LUMAXTECH", name: "Lumax Auto Technologies", exchange: "NSE", sector: "Auto", industry: "Auto Components" },
  { symbol: "LUPIN", name: "Lupin", exchange: "NSE", sector: "Pharma", industry: "Pharmaceuticals" },
  { symbol: "MMTC", name: "MMTC", exchange: "NSE", sector: "Other", industry: "Services" },
  { symbol: "MOIL", name: "MOIL", exchange: "NSE", sector: "Metals", industry: "Mining" },
  { symbol: "MRF", name: "MRF", exchange: "NSE", sector: "Auto", industry: "Tyres" },
  { symbol: "MSTCLTD", name: "MSTC", exchange: "NSE", sector: "Other", industry: "Services" },
  { symbol: "MTARTECH", name: "MTAR Technologies", exchange: "NSE", sector: "Capital Goods", industry: "Defence Aerospace" },
  { symbol: "MGL", name: "Mahanagar Gas", exchange: "NSE", sector: "Energy", industry: "Gas Distribution" },
  { symbol: "MAHSCOOTER", name: "Maharashtra Scooters", exchange: "NSE", sector: "NBFC", industry: "Financial Services" },
  { symbol: "MAHSEAMLES", name: "Maharashtra Seamless", exchange: "NSE", sector: "Capital Goods", industry: "Capital Goods" },
  { symbol: "M&MFIN", name: "Mahindra & Mahindra Financial Services", exchange: "NSE", sector: "NBFC", industry: "Financial Services" },
  { symbol: "M&M", name: "Mahindra & Mahindra", exchange: "NSE", sector: "Auto", industry: "Passenger Vehicles" },
  { symbol: "MANAPPURAM", name: "Manappuram Finance", exchange: "NSE", sector: "NBFC", industry: "Gold Loans" },
  { symbol: "MRPL", name: "Mangalore Refinery", exchange: "NSE", sector: "Energy", industry: "Oil Refining" },
  { symbol: "MANKIND", name: "Mankind Pharma", exchange: "NSE", sector: "Pharma", industry: "Pharmaceuticals" },
  { symbol: "MANORAMA", name: "Manorama Industries", exchange: "NSE", sector: "FMCG", industry: "Fast Moving Consumer Goods" },
  { symbol: "MARICO", name: "Marico", exchange: "NSE", sector: "FMCG", industry: "Personal Care" },
  { symbol: "MARKSANS", name: "Marksans Pharma", exchange: "NSE", sector: "Pharma", industry: "Healthcare" },
  { symbol: "MARUTI", name: "Maruti Suzuki India", exchange: "NSE", sector: "Auto", industry: "Passenger Vehicles" },
  { symbol: "MASTEK", name: "Mastek", exchange: "NSE", sector: "IT", industry: "IT Services" },
  { symbol: "MFSL", name: "Max Financial Services", exchange: "NSE", sector: "NBFC", industry: "Financial Services" },
  { symbol: "MAXHEALTH", name: "Max Healthcare", exchange: "NSE", sector: "Pharma", industry: "Healthcare Services" },
  { symbol: "MAZDOCK", name: "Mazagon Dock Shipbuilders", exchange: "NSE", sector: "Capital Goods", industry: "Defence" },
  { symbol: "MEDPLUS", name: "Medplus Health Services", exchange: "NSE", sector: "Consumer", industry: "Consumer Services" },
  { symbol: "MEESHO", name: "Meesho", exchange: "NSE", sector: "Consumer", industry: "Consumer Services" },
  { symbol: "METROPOLIS", name: "Metropolis Healthcare", exchange: "NSE", sector: "Pharma", industry: "Diagnostics" },
  { symbol: "MINDACORP", name: "Minda Corporation", exchange: "NSE", sector: "Auto", industry: "Automobile and Auto Components" },
  { symbol: "MIDHANI", name: "Mishra Dhatu Nigam", exchange: "NSE", sector: "Capital Goods", industry: "Capital Goods" },
  { symbol: "MSUMI", name: "Motherson Sumi Wiring India", exchange: "NSE", sector: "Auto", industry: "Automobile and Auto Components" },
  { symbol: "MOTILALOFS", name: "Motilal Oswal Financial", exchange: "NSE", sector: "NBFC", industry: "Capital Markets" },
  { symbol: "MPHASIS", name: "Mphasis", exchange: "NSE", sector: "IT", industry: "IT Services" },
  { symbol: "BECTORFOOD", name: "Mrs. Bectors Food Specialities", exchange: "NSE", sector: "FMCG", industry: "Fast Moving Consumer Goods" },
  { symbol: "MCX", name: "Multi Commodity Exchange", exchange: "NSE", sector: "Other", industry: "Exchange" },
  { symbol: "MUTHOOTFIN", name: "Muthoot Finance", exchange: "NSE", sector: "NBFC", industry: "Gold Loans" },
  { symbol: "NATCOPHARM", name: "Natco Pharma", exchange: "NSE", sector: "Pharma", industry: "Pharmaceuticals" },
  { symbol: "NBCC", name: "NBCC (India)", exchange: "NSE", sector: "Infrastructure", industry: "Construction" },
  { symbol: "NCC", name: "NCC", exchange: "NSE", sector: "Infrastructure", industry: "Construction" },
  { symbol: "NEOGEN", name: "NEOGEN CHEMICALS", exchange: "NSE", sector: "Chemicals", industry: "Chemicals" },
  { symbol: "NESCO", name: "NESCO", exchange: "NSE", sector: "Other", industry: "Services" },
  { symbol: "NHPC", name: "NHPC", exchange: "NSE", sector: "Power", industry: "Hydro Power" },
  { symbol: "NLCINDIA", name: "NLC India", exchange: "NSE", sector: "Power", industry: "Power" },
  { symbol: "NMDC", name: "NMDC", exchange: "NSE", sector: "Metals", industry: "Mining" },
  { symbol: "NSLNISP", name: "NMDC Steel", exchange: "NSE", sector: "Metals", industry: "Metals & Mining" },
  { symbol: "NTPCGREEN", name: "NTPC Green Energy", exchange: "NSE", sector: "Power", industry: "Power" },
  { symbol: "NTPC", name: "NTPC", exchange: "NSE", sector: "Power", industry: "Power Generation" },
  { symbol: "NH", name: "Narayana Hrudayalaya", exchange: "NSE", sector: "Pharma", industry: "Hospitals" },
  { symbol: "NATIONALUM", name: "National Aluminium", exchange: "NSE", sector: "Metals", industry: "Aluminium" },
  { symbol: "NFL", name: "National Fertilizers", exchange: "NSE", sector: "Chemicals", industry: "Fertilisers" },
  { symbol: "NAVA", name: "Nava", exchange: "NSE", sector: "Power", industry: "Power" },
  { symbol: "NAVINFLUOR", name: "Navin Fluorine", exchange: "NSE", sector: "Chemicals", industry: "Specialty Chemicals" },
  { symbol: "NAZARA", name: "Nazara Technologies", exchange: "NSE", sector: "Media", industry: "Media Entertainment & Publication" },
  { symbol: "NESTLEIND", name: "Nestle India", exchange: "NSE", sector: "FMCG", industry: "Packaged Foods" },
  { symbol: "NETWEB", name: "Netweb Technologies India", exchange: "NSE", sector: "IT", industry: "Information Technology" },
  { symbol: "NETWORK18", name: "Network18 Media", exchange: "NSE", sector: "Media", industry: "Media" },
  { symbol: "NEULANDLAB", name: "Neuland Laboratories", exchange: "NSE", sector: "Pharma", industry: "Healthcare" },
  { symbol: "NEWGEN", name: "Newgen Software", exchange: "NSE", sector: "IT", industry: "Software Products" },
  { symbol: "NAM-INDIA", name: "Nippon Life India Asset Management", exchange: "NSE", sector: "Insurance", industry: "Financial Services" },
  { symbol: "NIVABUPA", name: "Niva Bupa Health Insurance Company", exchange: "NSE", sector: "Insurance", industry: "Financial Services" },
  { symbol: "NUVAMA", name: "Nuvama Wealth Management", exchange: "NSE", sector: "NBFC", industry: "Wealth Management" },
  { symbol: "NUVOCO", name: "Nuvoco Vistas Corporation", exchange: "NSE", sector: "Cement", industry: "Construction Materials" },
  { symbol: "OBEROIRLTY", name: "Oberoi Realty", exchange: "NSE", sector: "Realty", industry: "Real Estate" },
  { symbol: "ONGC", name: "Oil and Natural Gas Corporation", exchange: "NSE", sector: "Energy", industry: "Oil & Gas Exploration" },
  { symbol: "OIL", name: "Oil India", exchange: "NSE", sector: "Energy", industry: "Oil & Gas Exploration" },
  { symbol: "OLAELEC", name: "Ola Electric Mobility", exchange: "NSE", sector: "Auto", industry: "Automobile and Auto Components" },
  { symbol: "OLECTRA", name: "Olectra Greentech", exchange: "NSE", sector: "Auto", industry: "Electric Buses" },
  { symbol: "PAYTM", name: "One 97 Communications", exchange: "NSE", sector: "Other", industry: "Fintech" },
  { symbol: "ONESOURCE", name: "Onesource Specialty Pharma", exchange: "NSE", sector: "Pharma", industry: "Healthcare" },
  { symbol: "OPTIEMUS", name: "Optiemus Infracom", exchange: "NSE", sector: "Telecom", industry: "Telecommunication" },
  { symbol: "OFSS", name: "Oracle Financial Services", exchange: "NSE", sector: "IT", industry: "Software Products" },
  { symbol: "ORIENTCEM", name: "Orient Cement", exchange: "NSE", sector: "Cement", industry: "Cement" },
  { symbol: "ORKLAINDIA", name: "Orkla India", exchange: "NSE", sector: "FMCG", industry: "Fast Moving Consumer Goods" },
  { symbol: "OSWALPUMPS", name: "Oswal Pumps", exchange: "NSE", sector: "Capital Goods", industry: "Capital Goods" },
  { symbol: "PNGJL", name: "P N Gadgil Jewellers", exchange: "NSE", sector: "Consumer", industry: "Consumer Durables" },
  { symbol: "POLICYBZR", name: "PB Fintech", exchange: "NSE", sector: "Other", industry: "Fintech" },
  { symbol: "PCJEWELLER", name: "PC Jeweller", exchange: "NSE", sector: "Consumer", industry: "Jewellery" },
  { symbol: "PCBL", name: "PCBL Limited", exchange: "NSE", sector: "Chemicals", industry: "Carbon Black" },
  { symbol: "PGEL", name: "PG Electroplast", exchange: "NSE", sector: "Capital Goods", industry: "EMS" },
  { symbol: "PIIND", name: "PI Industries", exchange: "NSE", sector: "Chemicals", industry: "Agrochemicals" },
  { symbol: "PNBHOUSING", name: "PNB Housing Finance", exchange: "NSE", sector: "NBFC", industry: "Housing Finance" },
  { symbol: "PNCINFRA", name: "PNC Infratech", exchange: "NSE", sector: "Infrastructure", industry: "Roads" },
  { symbol: "PTC", name: "PTC India", exchange: "NSE", sector: "Power", industry: "Power" },
  { symbol: "PTCIL", name: "PTC Industries", exchange: "NSE", sector: "Capital Goods", industry: "Capital Goods" },
  { symbol: "PVRINOX", name: "PVR INOX", exchange: "NSE", sector: "Media", industry: "Exhibition" },
  { symbol: "PAGEIND", name: "Page Industries", exchange: "NSE", sector: "Textiles", industry: "Apparel" },
  { symbol: "PARADEEP", name: "Paradeep Phosphates", exchange: "NSE", sector: "Chemicals", industry: "Chemicals" },
  { symbol: "PARAS", name: "Paras Defence", exchange: "NSE", sector: "Capital Goods", industry: "Defence" },
  { symbol: "PARKHOSPS", name: "Park Medi World", exchange: "NSE", sector: "Pharma", industry: "Healthcare" },
  { symbol: "PATANJALI", name: "Patanjali Foods", exchange: "NSE", sector: "FMCG", industry: "Edible Oils" },
  { symbol: "PGIL", name: "Pearl Global Industries", exchange: "NSE", sector: "Textiles", industry: "Textiles" },
  { symbol: "PERSISTENT", name: "Persistent Systems", exchange: "NSE", sector: "IT", industry: "IT Services" },
  { symbol: "PETRONET", name: "Petronet LNG", exchange: "NSE", sector: "Energy", industry: "Gas Distribution" },
  { symbol: "PFIZER", name: "Pfizer", exchange: "NSE", sector: "Pharma", industry: "Pharmaceuticals" },
  { symbol: "PHOENIXLTD", name: "Phoenix Mills", exchange: "NSE", sector: "Realty", industry: "Real Estate" },
  { symbol: "PWL", name: "Physicswallah", exchange: "NSE", sector: "Consumer", industry: "Consumer Services" },
  { symbol: "PICCADIL", name: "Piccadily Agro Industries", exchange: "NSE", sector: "FMCG", industry: "Fast Moving Consumer Goods" },
  { symbol: "PIDILITIND", name: "Pidilite Industries", exchange: "NSE", sector: "Consumer", industry: "Adhesives" },
  { symbol: "PINELABS", name: "Pine Labs", exchange: "NSE", sector: "NBFC", industry: "Financial Services" },
  { symbol: "PIRAMALFIN", name: "Piramal Finance", exchange: "NSE", sector: "NBFC", industry: "Financial Services" },
  { symbol: "PPLPHARMA", name: "Piramal Pharma", exchange: "NSE", sector: "Pharma", industry: "Healthcare" },
  { symbol: "POLYMED", name: "Poly Medicure", exchange: "NSE", sector: "Pharma", industry: "Medical Devices" },
  { symbol: "POLYCAB", name: "Polycab India", exchange: "NSE", sector: "Capital Goods", industry: "Cables" },
  { symbol: "POONAWALLA", name: "Poonawalla Fincorp", exchange: "NSE", sector: "NBFC", industry: "Consumer Finance" },
  { symbol: "PFC", name: "Power Finance Corporation", exchange: "NSE", sector: "NBFC", industry: "Infra Finance" },
  { symbol: "POWERGRID", name: "Power Grid Corporation", exchange: "NSE", sector: "Power", industry: "Power Transmission" },
  { symbol: "POWERMECH", name: "Power Mech Projects", exchange: "NSE", sector: "Infrastructure", industry: "Construction" },
  { symbol: "PRAJIND", name: "Praj Industries", exchange: "NSE", sector: "Capital Goods", industry: "Ethanol Plants" },
  { symbol: "PREMIERENE", name: "Premier Energies", exchange: "NSE", sector: "Capital Goods", industry: "Capital Goods" },
  { symbol: "PRESTIGE", name: "Prestige Estates", exchange: "NSE", sector: "Realty", industry: "Real Estate" },
  { symbol: "PRICOLLTD", name: "Pricol", exchange: "NSE", sector: "Auto", industry: "Automobile and Auto Components" },
  { symbol: "PFOCUS", name: "Prime Focus", exchange: "NSE", sector: "Media", industry: "Media Entertainment & Publication" },
  { symbol: "PRSMJOHNSN", name: "Prism Johnson", exchange: "NSE", sector: "Cement", industry: "Construction Materials" },
  { symbol: "PRIVISCL", name: "Privi Speciality Chemicals", exchange: "NSE", sector: "Chemicals", industry: "Chemicals" },
  { symbol: "PRUDENT", name: "Prudent Corporate Advisory", exchange: "NSE", sector: "NBFC", industry: "Wealth Management" },
  { symbol: "PNB", name: "Punjab National Bank", exchange: "NSE", sector: "Banks", industry: "Public Bank" },
  { symbol: "PURVA", name: "Puravankara", exchange: "NSE", sector: "Realty", industry: "Realty" },
  { symbol: "QPOWER", name: "Quality Power Electrical Equipments", exchange: "NSE", sector: "Capital Goods", industry: "Capital Goods" },
  { symbol: "QUESS", name: "Quess Corp", exchange: "NSE", sector: "Other", industry: "Services" },
  { symbol: "RRKABEL", name: "R R Kabel", exchange: "NSE", sector: "Capital Goods", industry: "Capital Goods" },
  { symbol: "RBLBANK", name: "RBL Bank", exchange: "NSE", sector: "Banks", industry: "Private Bank" },
  { symbol: "RECLTD", name: "REC", exchange: "NSE", sector: "NBFC", industry: "Infra Finance" },
  { symbol: "RHIM", name: "RHI Magnesita India", exchange: "NSE", sector: "Other", industry: "Refractories" },
  { symbol: "RITES", name: "RITES", exchange: "NSE", sector: "Infrastructure", industry: "Railway Consultancy" },
  { symbol: "RADICO", name: "Radico Khaitan", exchange: "NSE", sector: "FMCG", industry: "Beverages" },
  { symbol: "RVNL", name: "Rail Vikas Nigam", exchange: "NSE", sector: "Infrastructure", industry: "Railways" },
  { symbol: "RAILTEL", name: "RailTel Corporation", exchange: "NSE", sector: "Telecom", industry: "Telecom Services" },
  { symbol: "RAIN", name: "Rain Industries", exchange: "NSE", sector: "Chemicals", industry: "Chemicals" },
  { symbol: "RAINBOW", name: "Rainbow Children's Medicare", exchange: "NSE", sector: "Pharma", industry: "Hospitals" },
  { symbol: "RALLIS", name: "Rallis India", exchange: "NSE", sector: "Chemicals", industry: "Agrochemicals" },
  { symbol: "RKFORGE", name: "Ramkrishna Forgings", exchange: "NSE", sector: "Auto", industry: "Automobile and Auto Components" },
  { symbol: "RCF", name: "Rashtriya Chemicals & Fertilizers", exchange: "NSE", sector: "Chemicals", industry: "Fertilisers" },
  { symbol: "RATEGAIN", name: "RateGain Travel Technologies", exchange: "NSE", sector: "IT", industry: "Travel Software" },
  { symbol: "RATNAMANI", name: "Ratnamani Metals", exchange: "NSE", sector: "Metals", industry: "Steel Tubes" },
  { symbol: "RTNINDIA", name: "RattanIndia Enterprises", exchange: "NSE", sector: "Consumer", industry: "Consumer Services" },
  { symbol: "RTNPOWER", name: "RattanIndia Power", exchange: "NSE", sector: "Power", industry: "Power" },
  { symbol: "RAYMONDLSL", name: "Raymond Lifestyle", exchange: "NSE", sector: "Textiles", industry: "Textiles" },
  { symbol: "REDINGTON", name: "Redington", exchange: "NSE", sector: "Other", industry: "Services" },
  { symbol: "REDTAPE", name: "Redtape", exchange: "NSE", sector: "Consumer", industry: "Consumer Durables" },
  { symbol: "REFEX", name: "Refex Industries", exchange: "NSE", sector: "Power", industry: "Utilities" },
  { symbol: "RELAXO", name: "Relaxo Footwears", exchange: "NSE", sector: "Consumer", industry: "Footwear" },
  { symbol: "RELIANCE", name: "Reliance Industries", exchange: "NSE", sector: "Energy", industry: "Oil & Gas Refining" },
  { symbol: "RPOWER", name: "Reliance Power", exchange: "NSE", sector: "Power", industry: "Power Generation" },
  { symbol: "RELIGARE", name: "Religare Enterprises", exchange: "NSE", sector: "NBFC", industry: "Financial Services" },
  { symbol: "RBA", name: "Restaurant Brands Asia", exchange: "NSE", sector: "Consumer", industry: "Consumer Services" },
  { symbol: "ROUTE", name: "Route Mobile", exchange: "NSE", sector: "Telecom", industry: "Telecom Services" },
  { symbol: "RUBICON", name: "Rubicon Research", exchange: "NSE", sector: "Pharma", industry: "Healthcare" },
  { symbol: "SBFC", name: "SBFC Finance", exchange: "NSE", sector: "NBFC", industry: "Financial Services" },
  { symbol: "SBICARD", name: "SBI Cards and Payment Services", exchange: "NSE", sector: "NBFC", industry: "Financial Services" },
  { symbol: "SBILIFE", name: "SBI Life Insurance", exchange: "NSE", sector: "Insurance", industry: "Life Insurance" },
  { symbol: "SJVN", name: "SJVN", exchange: "NSE", sector: "Power", industry: "Hydro Power" },
  { symbol: "SKFINDUS", name: "SKF India (Industrial)", exchange: "NSE", sector: "Capital Goods", industry: "Capital Goods" },
  { symbol: "SKFINDIA", name: "SKF India", exchange: "NSE", sector: "Auto", industry: "Bearings" },
  { symbol: "SKYGOLD", name: "SKY GOLD AND DIAMONDS", exchange: "NSE", sector: "Consumer", industry: "Consumer Durables" },
  { symbol: "SMLMAH", name: "SML Mahindra", exchange: "NSE", sector: "Capital Goods", industry: "Capital Goods" },
  { symbol: "SRF", name: "SRF", exchange: "NSE", sector: "Chemicals", industry: "Specialty Chemicals" },
  { symbol: "SAATVIKGL", name: "Saatvik Green Energy", exchange: "NSE", sector: "Capital Goods", industry: "Capital Goods" },
  { symbol: "SAFARI", name: "Safari Industries (India)", exchange: "NSE", sector: "Consumer", industry: "Consumer Durables" },
  { symbol: "SAGILITY", name: "Sagility", exchange: "NSE", sector: "IT", industry: "Information Technology" },
  { symbol: "SAILIFE", name: "Sai Life Sciences", exchange: "NSE", sector: "Pharma", industry: "Healthcare" },
  { symbol: "SAMHI", name: "Samhi Hotels", exchange: "NSE", sector: "Consumer", industry: "Consumer Services" },
  { symbol: "SAMMAANCAP", name: "Sammaan Capital", exchange: "NSE", sector: "NBFC", industry: "Financial Services" },
  { symbol: "MOTHERSON", name: "Samvardhana Motherson", exchange: "NSE", sector: "Auto", industry: "Auto Components" },
  { symbol: "SANDUMA", name: "Sandur Manganese & Iron Ores", exchange: "NSE", sector: "Metals", industry: "Metals & Mining" },
  { symbol: "SANOFICONR", name: "Sanofi Consumer Healthcare India", exchange: "NSE", sector: "Pharma", industry: "Healthcare" },
  { symbol: "SANSERA", name: "Sansera Engineering", exchange: "NSE", sector: "Auto", industry: "Auto Components" },
  { symbol: "SAPPHIRE", name: "Sapphire Foods India", exchange: "NSE", sector: "FMCG", industry: "QSR" },
  { symbol: "SARDAEN", name: "Sarda Energy and Minerals", exchange: "NSE", sector: "Metals", industry: "Metals & Mining" },
  { symbol: "SAREGAMA", name: "Saregama India", exchange: "NSE", sector: "Media", industry: "Music" },
  { symbol: "SCHAEFFLER", name: "Schaeffler India", exchange: "NSE", sector: "Auto", industry: "Bearings" },
  { symbol: "SCHNEIDER", name: "Schneider Electric Infra", exchange: "NSE", sector: "Capital Goods", industry: "Electrical Equipment" },
  { symbol: "SENCO", name: "Senco Gold", exchange: "NSE", sector: "Consumer", industry: "Jewellery" },
  { symbol: "STYL", name: "Seshaasai Technologies", exchange: "NSE", sector: "NBFC", industry: "Financial Services" },
  { symbol: "SHAILY", name: "Shaily Engineering Plastics", exchange: "NSE", sector: "Consumer", industry: "Consumer Durables" },
  { symbol: "SHAKTIPUMP", name: "Shakti Pumps", exchange: "NSE", sector: "Capital Goods", industry: "Pumps" },
  { symbol: "SHARDACROP", name: "Sharda Cropchem", exchange: "NSE", sector: "Chemicals", industry: "Chemicals" },
  { symbol: "SHAREINDIA", name: "Share India Securities", exchange: "NSE", sector: "NBFC", industry: "Financial Services" },
  { symbol: "SFL", name: "Sheela Foam", exchange: "NSE", sector: "Consumer", industry: "Consumer Durables" },
  { symbol: "SHILPAMED", name: "Shilpa Medicare", exchange: "NSE", sector: "Pharma", industry: "Healthcare" },
  { symbol: "SCI", name: "Shipping Corporation of India", exchange: "NSE", sector: "Logistics", industry: "Shipping" },
  { symbol: "SHREECEM", name: "Shree Cement", exchange: "NSE", sector: "Cement", industry: "Cement" },
  { symbol: "RENUKA", name: "Shree Renuka Sugars", exchange: "NSE", sector: "Agri", industry: "Sugar" },
  { symbol: "SHRIRAMFIN", name: "Shriram Finance", exchange: "NSE", sector: "NBFC", industry: "Consumer Finance" },
  { symbol: "SHRIPISTON", name: "Shriram Pistons & Rings", exchange: "NSE", sector: "Auto", industry: "Automobile and Auto Components" },
  { symbol: "SHYAMMETL", name: "Shyam Metalics and Energy", exchange: "NSE", sector: "Capital Goods", industry: "Capital Goods" },
  { symbol: "ENRIN", name: "Siemens Energy India", exchange: "NSE", sector: "Capital Goods", industry: "Capital Goods" },
  { symbol: "SIEMENS", name: "Siemens", exchange: "NSE", sector: "Capital Goods", industry: "Electrical Equipment" },
  { symbol: "SIGNATURE", name: "Signatureglobal (India)", exchange: "NSE", sector: "Realty", industry: "Realty" },
  { symbol: "SKIPPER", name: "Skipper", exchange: "NSE", sector: "Capital Goods", industry: "Capital Goods" },
  { symbol: "SMARTWORKS", name: "Smartworks Coworking Spaces", exchange: "NSE", sector: "Other", industry: "Services" },
  { symbol: "SOBHA", name: "Sobha", exchange: "NSE", sector: "Realty", industry: "Real Estate" },
  { symbol: "SOLARINDS", name: "Solar Industries India", exchange: "NSE", sector: "Chemicals", industry: "Chemicals" },
  { symbol: "SONACOMS", name: "Sona BLW Precision Forgings", exchange: "NSE", sector: "Auto", industry: "EV Components" },
  { symbol: "SONATSOFTW", name: "Sonata Software", exchange: "NSE", sector: "IT", industry: "IT Services" },
  { symbol: "SOUTHBANK", name: "South Indian Bank", exchange: "NSE", sector: "Banks", industry: "Private Bank" },
  { symbol: "LOTUSDEV", name: "Sri Lotus Developers and Realty", exchange: "NSE", sector: "Realty", industry: "Realty" },
  { symbol: "STARCEMENT", name: "Star Cement", exchange: "NSE", sector: "Cement", industry: "Cement" },
  { symbol: "STARHEALTH", name: "Star Health & Allied Insurance", exchange: "NSE", sector: "Insurance", industry: "Health Insurance" },
  { symbol: "SBIN", name: "State Bank of India", exchange: "NSE", sector: "Banks", industry: "Public Bank" },
  { symbol: "SAIL", name: "Steel Authority of India", exchange: "NSE", sector: "Metals", industry: "Iron & Steel" },
  { symbol: "SWSOLAR", name: "Sterling and Wilson Renewable Energy", exchange: "NSE", sector: "Infrastructure", industry: "Construction" },
  { symbol: "STLTECH", name: "Sterlite Technologies", exchange: "NSE", sector: "Telecom", industry: "Optical Fibre" },
  { symbol: "STAR", name: "Strides Pharma Science", exchange: "NSE", sector: "Pharma", industry: "Pharmaceuticals" },
  { symbol: "STYRENIX", name: "Styrenix Performance Materials", exchange: "NSE", sector: "Chemicals", industry: "Chemicals" },
  { symbol: "SUBROS", name: "Subros", exchange: "NSE", sector: "Auto", industry: "Auto AC" },
  { symbol: "SUDARSCHEM", name: "Sudarshan Chemical", exchange: "NSE", sector: "Chemicals", industry: "Pigments" },
  { symbol: "SUDEEPPHRM", name: "Sudeep Pharma", exchange: "NSE", sector: "Chemicals", industry: "Chemicals" },
  { symbol: "SUMICHEM", name: "Sumitomo Chemical India", exchange: "NSE", sector: "Chemicals", industry: "Agrochemicals" },
  { symbol: "SPARC", name: "Sun Pharma Advanced Research Company", exchange: "NSE", sector: "Pharma", industry: "Healthcare" },
  { symbol: "SUNPHARMA", name: "Sun Pharmaceutical", exchange: "NSE", sector: "Pharma", industry: "Pharmaceuticals" },
  { symbol: "SUNTV", name: "Sun TV Network", exchange: "NSE", sector: "Media", industry: "Broadcasting" },
  { symbol: "SUNDARMFIN", name: "Sundaram Finance", exchange: "NSE", sector: "NBFC", industry: "Vehicle Finance" },
  { symbol: "SUNTECK", name: "Sunteck Realty", exchange: "NSE", sector: "Realty", industry: "Real Estate" },
  { symbol: "SUPREMEIND", name: "Supreme Industries", exchange: "NSE", sector: "Capital Goods", industry: "Plastics" },
  { symbol: "SPLPETRO", name: "Supreme Petrochem", exchange: "NSE", sector: "Chemicals", industry: "Chemicals" },
  { symbol: "SUPRIYA", name: "Supriya Lifescience", exchange: "NSE", sector: "Pharma", industry: "API" },
  { symbol: "SURYAROSNI", name: "Surya Roshni", exchange: "NSE", sector: "Capital Goods", industry: "Capital Goods" },
  { symbol: "SUZLON", name: "Suzlon Energy", exchange: "NSE", sector: "Power", industry: "Wind Equipment" },
  { symbol: "SWANCORP", name: "Swan Corp", exchange: "NSE", sector: "Chemicals", industry: "Chemicals" },
  { symbol: "SWIGGY", name: "Swiggy", exchange: "NSE", sector: "Consumer", industry: "Consumer Services" },
  { symbol: "SYNGENE", name: "Syngene International", exchange: "NSE", sector: "Pharma", industry: "CRAMS" },
  { symbol: "SYRMA", name: "Syrma SGS Technology", exchange: "NSE", sector: "Capital Goods", industry: "EMS" },
  { symbol: "TARC", name: "TARC", exchange: "NSE", sector: "Realty", industry: "Realty" },
  { symbol: "TBOTEK", name: "TBO Tek", exchange: "NSE", sector: "Consumer", industry: "Travel Tech" },
  { symbol: "TDPOWERSYS", name: "TD Power Systems", exchange: "NSE", sector: "Capital Goods", industry: "Capital Goods" },
  { symbol: "TSFINV", name: "TSF Investments", exchange: "NSE", sector: "NBFC", industry: "Financial Services" },
  { symbol: "TVSMOTOR", name: "TVS Motor Company", exchange: "NSE", sector: "Auto", industry: "Two Wheelers" },
  { symbol: "TVSSCS", name: "TVS Supply Chain Solutions", exchange: "NSE", sector: "Other", industry: "Services" },
  { symbol: "TMB", name: "Tamilnad Mercantile Bank", exchange: "NSE", sector: "Banks", industry: "Private Bank" },
  { symbol: "TANLA", name: "Tanla Platforms", exchange: "NSE", sector: "IT", industry: "Communication Platform" },
  { symbol: "TATACAP", name: "Tata Capital", exchange: "NSE", sector: "NBFC", industry: "Financial Services" },
  { symbol: "TATACHEM", name: "Tata Chemicals", exchange: "NSE", sector: "Chemicals", industry: "Commodity Chemicals" },
  { symbol: "TATACOMM", name: "Tata Communications", exchange: "NSE", sector: "Telecom", industry: "Telecom Services" },
  { symbol: "TCS", name: "Tata Consultancy Services", exchange: "NSE", sector: "IT", industry: "IT Services" },
  { symbol: "TATACONSUM", name: "Tata Consumer Products", exchange: "NSE", sector: "FMCG", industry: "Packaged Foods" },
  { symbol: "TATAELXSI", name: "Tata Elxsi", exchange: "NSE", sector: "IT", industry: "Engineering R&D" },
  { symbol: "TATAINVEST", name: "Tata Investment Corporation", exchange: "NSE", sector: "NBFC", industry: "Financial Services" },
  { symbol: "TMCV", name: "Tata Motors", exchange: "NSE", sector: "Capital Goods", industry: "Capital Goods" },
  { symbol: "TMPV", name: "Tata Motors Passenger Vehicles", exchange: "NSE", sector: "Auto", industry: "Automobile and Auto Components" },
  { symbol: "TATAPOWER", name: "Tata Power", exchange: "NSE", sector: "Power", industry: "Power Generation" },
  { symbol: "TATASTEEL", name: "Tata Steel", exchange: "NSE", sector: "Metals", industry: "Iron & Steel" },
  { symbol: "TATATECH", name: "Tata Technologies", exchange: "NSE", sector: "IT", industry: "Engineering R&D" },
  { symbol: "TTML", name: "Tata Teleservices (Maharashtra)", exchange: "NSE", sector: "Telecom", industry: "Telecommunication" },
  { symbol: "TECHM", name: "Tech Mahindra", exchange: "NSE", sector: "IT", industry: "IT Services" },
  { symbol: "TECHNOE", name: "Techno Electric & Engineering", exchange: "NSE", sector: "IT", industry: "Power EPC" },
  { symbol: "TEGA", name: "Tega Industries", exchange: "NSE", sector: "Capital Goods", industry: "Capital Goods" },
  { symbol: "TEJASNET", name: "Tejas Networks", exchange: "NSE", sector: "Telecom", industry: "Telecommunication" },
  { symbol: "TENNIND", name: "Tenneco Clean Air India", exchange: "NSE", sector: "Auto", industry: "Automobile and Auto Components" },
  { symbol: "TEXRAIL", name: "Texmaco Rail & Engineering", exchange: "NSE", sector: "Capital Goods", industry: "Railway Wagons" },
  { symbol: "THANGAMAYL", name: "Thangamayil Jewellery", exchange: "NSE", sector: "Consumer", industry: "Consumer Durables" },
  { symbol: "ANUP", name: "Anup Engineering", exchange: "NSE", sector: "Capital Goods", industry: "Process Equipment" },
  { symbol: "NIACL", name: "New India Assurance", exchange: "NSE", sector: "Insurance", industry: "General Insurance" },
  { symbol: "RAMCOCEM", name: "The Ramco Cements", exchange: "NSE", sector: "Cement", industry: "Cement" },
  { symbol: "THERMAX", name: "Thermax", exchange: "NSE", sector: "Capital Goods", industry: "Industrial Engg" },
  { symbol: "THOMASCOOK", name: "Thomas Cook (India)", exchange: "NSE", sector: "Consumer", industry: "Consumer Services" },
  { symbol: "THYROCARE", name: "Thyrocare Technologies", exchange: "NSE", sector: "Pharma", industry: "Diagnostics" },
  { symbol: "TI", name: "Tilaknagar Industries", exchange: "NSE", sector: "FMCG", industry: "Fast Moving Consumer Goods" },
  { symbol: "TIMETECHNO", name: "Time Technoplast", exchange: "NSE", sector: "Capital Goods", industry: "Industrial Packaging" },
  { symbol: "TIMKEN", name: "Timken India", exchange: "NSE", sector: "Auto", industry: "Bearings" },
  { symbol: "TIPSMUSIC", name: "Tips Music", exchange: "NSE", sector: "Media", industry: "Music" },
  { symbol: "TITAGARH", name: "Titagarh Rail Systems", exchange: "NSE", sector: "Capital Goods", industry: "Railway Wagons" },
  { symbol: "TITAN", name: "Titan Company", exchange: "NSE", sector: "Consumer", industry: "Consumer Durables" },
  { symbol: "TORNTPHARM", name: "Torrent Pharmaceuticals", exchange: "NSE", sector: "Pharma", industry: "Pharmaceuticals" },
  { symbol: "TORNTPOWER", name: "Torrent Power", exchange: "NSE", sector: "Power", industry: "Power Distribution" },
  { symbol: "TARIL", name: "Transformers And Rectifiers (India)", exchange: "NSE", sector: "Capital Goods", industry: "Capital Goods" },
  { symbol: "TRANSRAILL", name: "Transrail Lighting", exchange: "NSE", sector: "Capital Goods", industry: "Capital Goods" },
  { symbol: "TRAVELFOOD", name: "Travel Food Services", exchange: "NSE", sector: "Consumer", industry: "Consumer Services" },
  { symbol: "TRENT", name: "Trent", exchange: "NSE", sector: "Consumer", industry: "Retail" },
  { symbol: "TRIDENT", name: "Trident", exchange: "NSE", sector: "Textiles", industry: "Home Textiles" },
  { symbol: "TRIVENI", name: "Triveni Engineering & Industries", exchange: "NSE", sector: "Agri", industry: "Sugar" },
  { symbol: "TRITURBINE", name: "Triveni Turbine", exchange: "NSE", sector: "Capital Goods", industry: "Turbines" },
  { symbol: "TIINDIA", name: "Tube Investments", exchange: "NSE", sector: "Capital Goods", industry: "Industrial Engg" },
  { symbol: "UCOBANK", name: "UCO Bank", exchange: "NSE", sector: "Banks", industry: "PSU Bank" },
  { symbol: "UNOMINDA", name: "UNO Minda", exchange: "NSE", sector: "Auto", industry: "Automobile and Auto Components" },
  { symbol: "UPL", name: "UPL", exchange: "NSE", sector: "Agri", industry: "Agrochemicals" },
  { symbol: "UTIAMC", name: "UTI Asset Management Company", exchange: "NSE", sector: "NBFC", industry: "Financial Services" },
  { symbol: "UJJIVANSFB", name: "Ujjivan Small Finance Bank", exchange: "NSE", sector: "Banks", industry: "Small Finance Bank" },
  { symbol: "ULTRACEMCO", name: "UltraTech Cement", exchange: "NSE", sector: "Cement", industry: "Cement" },
  { symbol: "UNIONBANK", name: "Union Bank of India", exchange: "NSE", sector: "Banks", industry: "Public Bank" },
  { symbol: "UBL", name: "United Breweries", exchange: "NSE", sector: "FMCG", industry: "Beverages" },
  { symbol: "UNITDSPR", name: "United Spirits", exchange: "NSE", sector: "FMCG", industry: "Beverages" },
  { symbol: "URBANCO", name: "Urban Company", exchange: "NSE", sector: "Consumer", industry: "Consumer Services" },
  { symbol: "USHAMART", name: "Usha Martin", exchange: "NSE", sector: "Capital Goods", industry: "Capital Goods" },
  { symbol: "VGUARD", name: "V-Guard Industries", exchange: "NSE", sector: "Consumer", industry: "Electricals" },
  { symbol: "VMART", name: "V-Mart Retail", exchange: "NSE", sector: "Consumer", industry: "Retail" },
  { symbol: "VIPIND", name: "V.I.P. Industries", exchange: "NSE", sector: "Consumer", industry: "Consumer Durables" },
  { symbol: "V2RETAIL", name: "V2 Retail", exchange: "NSE", sector: "Consumer", industry: "Consumer Services" },
  { symbol: "WABAG", name: "Va Tech Wabag", exchange: "NSE", sector: "Power", industry: "Utilities" },
  { symbol: "VAIBHAVGBL", name: "Vaibhav Global", exchange: "NSE", sector: "Consumer", industry: "Jewellery" },
  { symbol: "DBREALTY", name: "D B Realty", exchange: "NSE", sector: "Realty", industry: "Real Estate" },
  { symbol: "VTL", name: "Vardhman Textiles", exchange: "NSE", sector: "Textiles", industry: "Textiles" },
  { symbol: "VARROC", name: "Varroc Engineering", exchange: "NSE", sector: "Auto", industry: "Automobile and Auto Components" },
  { symbol: "VBL", name: "Varun Beverages", exchange: "NSE", sector: "FMCG", industry: "Beverages" },
  { symbol: "MANYAVAR", name: "Vedant Fashions", exchange: "NSE", sector: "Consumer", industry: "Consumer Services" },
  { symbol: "VEDL", name: "Vedanta", exchange: "NSE", sector: "Metals", industry: "Diversified Metals" },
  { symbol: "VIJAYA", name: "Vijaya Diagnostic Centre", exchange: "NSE", sector: "Pharma", industry: "Diagnostics" },
  { symbol: "VIKRAMSOLR", name: "Vikram Solar", exchange: "NSE", sector: "Capital Goods", industry: "Capital Goods" },
  { symbol: "VMM", name: "Vishal Mega Mart", exchange: "NSE", sector: "Consumer", industry: "Consumer Services" },
  { symbol: "VIYASH", name: "Viyash Scientific", exchange: "NSE", sector: "Pharma", industry: "Healthcare" },
  { symbol: "IDEA", name: "Vodafone Idea", exchange: "NSE", sector: "Telecom", industry: "Telecom Services" },
  { symbol: "VOLTAMP", name: "Voltamp Transformers", exchange: "NSE", sector: "Capital Goods", industry: "Transformers" },
  { symbol: "VOLTAS", name: "Voltas", exchange: "NSE", sector: "Consumer", industry: "Consumer Electronics" },
  { symbol: "WAAREEENER", name: "Waaree Energies", exchange: "NSE", sector: "Capital Goods", industry: "Capital Goods" },
  { symbol: "WAAREERTL", name: "Waaree Renewable Technologies", exchange: "NSE", sector: "Capital Goods", industry: "Capital Goods" },
  { symbol: "WAKEFIT", name: "Wakefit Innovations", exchange: "NSE", sector: "Consumer", industry: "Consumer Durables" },
  { symbol: "WEWORK", name: "WeWork India Management", exchange: "NSE", sector: "Other", industry: "Services" },
  { symbol: "WEBELSOLAR", name: "Websol Energy System", exchange: "NSE", sector: "Capital Goods", industry: "Capital Goods" },
  { symbol: "WELCORP", name: "Welspun Corp", exchange: "NSE", sector: "Metals", industry: "Steel Pipes" },
  { symbol: "WELENT", name: "Welspun Enterprises", exchange: "NSE", sector: "Infrastructure", industry: "Construction" },
  { symbol: "WELSPUNLIV", name: "Welspun Living", exchange: "NSE", sector: "Textiles", industry: "Textiles" },
  { symbol: "WESTLIFE", name: "Westlife Foodworld", exchange: "NSE", sector: "Consumer", industry: "Restaurants" },
  { symbol: "WHIRLPOOL", name: "Whirlpool of India", exchange: "NSE", sector: "Consumer", industry: "Consumer Durables" },
  { symbol: "WIPRO", name: "Wipro", exchange: "NSE", sector: "IT", industry: "IT Services" },
  { symbol: "WOCKPHARMA", name: "Wockhardt", exchange: "NSE", sector: "Pharma", industry: "Pharmaceuticals" },
  { symbol: "YATHARTH", name: "Yatharth Hospital & Trauma Care Services", exchange: "NSE", sector: "Pharma", industry: "Healthcare" },
  { symbol: "YESBANK", name: "Yes Bank", exchange: "NSE", sector: "Banks", industry: "Private Bank" },
  { symbol: "ZFCVINDIA", name: "ZF Commercial Vehicle Control Systems India", exchange: "NSE", sector: "Auto", industry: "Automobile and Auto Components" },
  { symbol: "ZAGGLE", name: "Zaggle Prepaid Ocean Services", exchange: "NSE", sector: "Other", industry: "Fintech" },
  { symbol: "ZEEL", name: "Zee Entertainment", exchange: "NSE", sector: "Media", industry: "Broadcasting" },
  { symbol: "ZENTEC", name: "Zen Technologies", exchange: "NSE", sector: "Capital Goods", industry: "Capital Goods" },
  { symbol: "ZENSARTECH", name: "Zensar Technologies", exchange: "NSE", sector: "IT", industry: "IT Services" },
  { symbol: "ZYDUSLIFE", name: "Zydus Lifesciences", exchange: "NSE", sector: "Pharma", industry: "Pharmaceuticals" },
  { symbol: "ZYDUSWELL", name: "Zydus Wellness", exchange: "NSE", sector: "FMCG", industry: "Fast Moving Consumer Goods" },
  { symbol: "ECLERX", name: "eClerx Services", exchange: "NSE", sector: "IT", industry: "KPO" },
];

export const ALL_SECTORS: Sector[] = [
  "IT", "Banks", "NBFC", "Auto", "Pharma", "FMCG", "Energy", "Metals",
  "Telecom", "Cement", "Power", "Insurance", "Consumer", "Realty",
  "Capital Goods", "Chemicals", "Infrastructure", "Media", "Logistics",
  "Textiles", "Agri", "Other",
];

export function searchSymbols(query: string, limit = 10): SymbolEntry[] {
  const q = query.trim().toUpperCase();
  if (!q) return [];
  return NSE_SYMBOLS.filter(
    (s) => s.symbol.startsWith(q) || s.name.toUpperCase().includes(q),
  ).slice(0, limit);
}

export function allIndustries(): string[] {
  const set = new Set<string>();
  for (const s of NSE_SYMBOLS) if (s.industry) set.add(s.industry);
  return [...set].sort();
}
