export type Sector =
  | "IT" | "Banks" | "NBFC" | "Auto" | "Pharma" | "FMCG" | "Energy"
  | "Metals" | "Telecom" | "Cement" | "Power" | "Insurance" | "Consumer"
  | "Realty" | "Capital Goods" | "Chemicals" | "Infrastructure"
  | "Media" | "Logistics" | "Textiles" | "Agri" | "Other";

export type SymbolEntry = {
  symbol: string;
  name: string;
  exchange: "NSE" | "BSE";
  sector: Sector;
  industry?: string;
};

export const NSE_SYMBOLS: SymbolEntry[] = [
  { symbol: "RELIANCE", name: "Reliance Industries", exchange: "NSE", sector: "Energy", industry: "Oil & Gas Refining" },
  { symbol: "TCS", name: "Tata Consultancy Services", exchange: "NSE", sector: "IT", industry: "IT Services" },
  { symbol: "HDFCBANK", name: "HDFC Bank", exchange: "NSE", sector: "Banks", industry: "Private Bank" },
  { symbol: "ICICIBANK", name: "ICICI Bank", exchange: "NSE", sector: "Banks", industry: "Private Bank" },
  { symbol: "INFY", name: "Infosys", exchange: "NSE", sector: "IT", industry: "IT Services" },
  { symbol: "BHARTIARTL", name: "Bharti Airtel", exchange: "NSE", sector: "Telecom", industry: "Telecom Services" },
  { symbol: "ITC", name: "ITC", exchange: "NSE", sector: "FMCG", industry: "Diversified FMCG" },
  { symbol: "SBIN", name: "State Bank of India", exchange: "NSE", sector: "Banks", industry: "Public Bank" },
  { symbol: "LICI", name: "Life Insurance Corporation", exchange: "NSE", sector: "Insurance", industry: "Life Insurance" },
  { symbol: "HINDUNILVR", name: "Hindustan Unilever", exchange: "NSE", sector: "FMCG", industry: "Personal Care" },
  { symbol: "LT", name: "Larsen & Toubro", exchange: "NSE", sector: "Infrastructure", industry: "Construction" },
  { symbol: "BAJFINANCE", name: "Bajaj Finance", exchange: "NSE", sector: "NBFC", industry: "Consumer Finance" },
  { symbol: "HCLTECH", name: "HCL Technologies", exchange: "NSE", sector: "IT", industry: "IT Services" },
  { symbol: "MARUTI", name: "Maruti Suzuki India", exchange: "NSE", sector: "Auto", industry: "Passenger Vehicles" },
  { symbol: "KOTAKBANK", name: "Kotak Mahindra Bank", exchange: "NSE", sector: "Banks", industry: "Private Bank" },
  { symbol: "AXISBANK", name: "Axis Bank", exchange: "NSE", sector: "Banks", industry: "Private Bank" },
  { symbol: "SUNPHARMA", name: "Sun Pharmaceutical", exchange: "NSE", sector: "Pharma", industry: "Pharmaceuticals" },
  { symbol: "ASIANPAINT", name: "Asian Paints", exchange: "NSE", sector: "Consumer", industry: "Paints" },
  { symbol: "TITAN", name: "Titan Company", exchange: "NSE", sector: "Consumer", industry: "Consumer Durables" },
  { symbol: "ADANIENT", name: "Adani Enterprises", exchange: "NSE", sector: "Other", industry: "Diversified" },
  { symbol: "ULTRACEMCO", name: "UltraTech Cement", exchange: "NSE", sector: "Cement", industry: "Cement" },
  { symbol: "ONGC", name: "Oil and Natural Gas Corporation", exchange: "NSE", sector: "Energy", industry: "Oil & Gas Exploration" },
  { symbol: "NTPC", name: "NTPC", exchange: "NSE", sector: "Power", industry: "Power Generation" },
  { symbol: "WIPRO", name: "Wipro", exchange: "NSE", sector: "IT", industry: "IT Services" },
  { symbol: "POWERGRID", name: "Power Grid Corporation", exchange: "NSE", sector: "Power", industry: "Power Transmission" },
  { symbol: "M&M", name: "Mahindra & Mahindra", exchange: "NSE", sector: "Auto", industry: "Passenger Vehicles" },
  { symbol: "JSWSTEEL", name: "JSW Steel", exchange: "NSE", sector: "Metals", industry: "Iron & Steel" },
  { symbol: "TATAMOTORS", name: "Tata Motors", exchange: "NSE", sector: "Auto", industry: "Passenger Vehicles" },
  { symbol: "TATASTEEL", name: "Tata Steel", exchange: "NSE", sector: "Metals", industry: "Iron & Steel" },
  { symbol: "COALINDIA", name: "Coal India", exchange: "NSE", sector: "Energy", industry: "Coal" },
  { symbol: "NESTLEIND", name: "Nestle India", exchange: "NSE", sector: "FMCG", industry: "Packaged Foods" },
  { symbol: "BAJAJFINSV", name: "Bajaj Finserv", exchange: "NSE", sector: "NBFC", industry: "Diversified Financial" },
  { symbol: "ADANIPORTS", name: "Adani Ports & SEZ", exchange: "NSE", sector: "Logistics", industry: "Ports" },
  { symbol: "GRASIM", name: "Grasim Industries", exchange: "NSE", sector: "Cement", industry: "Cement" },
  { symbol: "TECHM", name: "Tech Mahindra", exchange: "NSE", sector: "IT", industry: "IT Services" },
  { symbol: "HINDALCO", name: "Hindalco Industries", exchange: "NSE", sector: "Metals", industry: "Aluminium" },
  { symbol: "DRREDDY", name: "Dr Reddys Laboratories", exchange: "NSE", sector: "Pharma", industry: "Pharmaceuticals" },
  { symbol: "CIPLA", name: "Cipla", exchange: "NSE", sector: "Pharma", industry: "Pharmaceuticals" },
  { symbol: "BPCL", name: "Bharat Petroleum", exchange: "NSE", sector: "Energy", industry: "Oil Marketing" },
  { symbol: "IOC", name: "Indian Oil Corporation", exchange: "NSE", sector: "Energy", industry: "Oil Marketing" },
  { symbol: "DIVISLAB", name: "Divis Laboratories", exchange: "NSE", sector: "Pharma", industry: "Pharmaceuticals" },
  { symbol: "EICHERMOT", name: "Eicher Motors", exchange: "NSE", sector: "Auto", industry: "Two Wheelers" },
  { symbol: "BRITANNIA", name: "Britannia Industries", exchange: "NSE", sector: "FMCG", industry: "Packaged Foods" },
  { symbol: "HEROMOTOCO", name: "Hero MotoCorp", exchange: "NSE", sector: "Auto", industry: "Two Wheelers" },
  { symbol: "APOLLOHOSP", name: "Apollo Hospitals", exchange: "NSE", sector: "Pharma", industry: "Healthcare Services" },
  { symbol: "TATACONSUM", name: "Tata Consumer Products", exchange: "NSE", sector: "FMCG", industry: "Packaged Foods" },
  { symbol: "BAJAJ-AUTO", name: "Bajaj Auto", exchange: "NSE", sector: "Auto", industry: "Two Wheelers" },
  { symbol: "INDUSINDBK", name: "IndusInd Bank", exchange: "NSE", sector: "Banks", industry: "Private Bank" },
  { symbol: "SBILIFE", name: "SBI Life Insurance", exchange: "NSE", sector: "Insurance", industry: "Life Insurance" },
  { symbol: "HDFCLIFE", name: "HDFC Life Insurance", exchange: "NSE", sector: "Insurance", industry: "Life Insurance" },
  { symbol: "UPL", name: "UPL", exchange: "NSE", sector: "Agri", industry: "Agrochemicals" },
  { symbol: "ZOMATO", name: "Zomato", exchange: "NSE", sector: "Consumer", industry: "Internet" },
  { symbol: "PAYTM", name: "One 97 Communications", exchange: "NSE", sector: "Other", industry: "Fintech" },
  { symbol: "DMART", name: "Avenue Supermarts", exchange: "NSE", sector: "Consumer", industry: "Retail" },
  { symbol: "IRCTC", name: "Indian Railway Catering", exchange: "NSE", sector: "Logistics", industry: "Travel" },
  { symbol: "NYKAA", name: "FSN E-Commerce Ventures", exchange: "NSE", sector: "Consumer", industry: "Internet" },
  { symbol: "POLICYBZR", name: "PB Fintech", exchange: "NSE", sector: "Other", industry: "Fintech" },
  { symbol: "ZEEL", name: "Zee Entertainment", exchange: "NSE", sector: "Media", industry: "Broadcasting" },
  { symbol: "TATAPOWER", name: "Tata Power", exchange: "NSE", sector: "Power", industry: "Power Generation" },
  { symbol: "VEDL", name: "Vedanta", exchange: "NSE", sector: "Metals", industry: "Diversified Metals" },
  { symbol: "PIDILITIND", name: "Pidilite Industries", exchange: "NSE", sector: "Consumer", industry: "Adhesives" },
  { symbol: "DLF", name: "DLF", exchange: "NSE", sector: "Realty", industry: "Real Estate" },
  { symbol: "GODREJCP", name: "Godrej Consumer Products", exchange: "NSE", sector: "FMCG", industry: "Personal Care" },
  { symbol: "DABUR", name: "Dabur India", exchange: "NSE", sector: "FMCG", industry: "Personal Care" },
  { symbol: "MARICO", name: "Marico", exchange: "NSE", sector: "FMCG", industry: "Personal Care" },
  { symbol: "COLPAL", name: "Colgate-Palmolive India", exchange: "NSE", sector: "FMCG", industry: "Personal Care" },
  { symbol: "HAVELLS", name: "Havells India", exchange: "NSE", sector: "Consumer", industry: "Consumer Electronics" },
  { symbol: "VOLTAS", name: "Voltas", exchange: "NSE", sector: "Consumer", industry: "Consumer Electronics" },
  { symbol: "BERGEPAINT", name: "Berger Paints", exchange: "NSE", sector: "Consumer", industry: "Paints" },
  { symbol: "AMBUJACEM", name: "Ambuja Cements", exchange: "NSE", sector: "Cement", industry: "Cement" },
  { symbol: "ACC", name: "ACC", exchange: "NSE", sector: "Cement", industry: "Cement" },
  { symbol: "SHREECEM", name: "Shree Cement", exchange: "NSE", sector: "Cement", industry: "Cement" },
  { symbol: "DALBHARAT", name: "Dalmia Bharat", exchange: "NSE", sector: "Cement", industry: "Cement" },
  { symbol: "SAIL", name: "Steel Authority of India", exchange: "NSE", sector: "Metals", industry: "Iron & Steel" },
  { symbol: "JINDALSTEL", name: "Jindal Steel & Power", exchange: "NSE", sector: "Metals", industry: "Iron & Steel" },
  { symbol: "NMDC", name: "NMDC", exchange: "NSE", sector: "Metals", industry: "Mining" },
  { symbol: "HINDZINC", name: "Hindustan Zinc", exchange: "NSE", sector: "Metals", industry: "Zinc" },
  { symbol: "MOIL", name: "MOIL", exchange: "NSE", sector: "Metals", industry: "Mining" },
  { symbol: "GAIL", name: "GAIL India", exchange: "NSE", sector: "Energy", industry: "Gas Distribution" },
  { symbol: "IGL", name: "Indraprastha Gas", exchange: "NSE", sector: "Energy", industry: "Gas Distribution" },
  { symbol: "MGL", name: "Mahanagar Gas", exchange: "NSE", sector: "Energy", industry: "Gas Distribution" },
  { symbol: "GUJGASLTD", name: "Gujarat Gas", exchange: "NSE", sector: "Energy", industry: "Gas Distribution" },
  { symbol: "PETRONET", name: "Petronet LNG", exchange: "NSE", sector: "Energy", industry: "Gas Distribution" },
  { symbol: "OIL", name: "Oil India", exchange: "NSE", sector: "Energy", industry: "Oil & Gas Exploration" },
  { symbol: "HINDPETRO", name: "Hindustan Petroleum", exchange: "NSE", sector: "Energy", industry: "Oil Marketing" },
  { symbol: "ADANIGREEN", name: "Adani Green Energy", exchange: "NSE", sector: "Power", industry: "Renewable Energy" },
  { symbol: "ADANIPOWER", name: "Adani Power", exchange: "NSE", sector: "Power", industry: "Power Generation" },
  { symbol: "ADANITRANS", name: "Adani Energy Solutions", exchange: "NSE", sector: "Power", industry: "Power Transmission" },
  { symbol: "JSWENERGY", name: "JSW Energy", exchange: "NSE", sector: "Power", industry: "Power Generation" },
  { symbol: "TORNTPOWER", name: "Torrent Power", exchange: "NSE", sector: "Power", industry: "Power Distribution" },
  { symbol: "NHPC", name: "NHPC", exchange: "NSE", sector: "Power", industry: "Hydro Power" },
  { symbol: "SJVN", name: "SJVN", exchange: "NSE", sector: "Power", industry: "Hydro Power" },
  { symbol: "BANKBARODA", name: "Bank of Baroda", exchange: "NSE", sector: "Banks", industry: "Public Bank" },
  { symbol: "PNB", name: "Punjab National Bank", exchange: "NSE", sector: "Banks", industry: "Public Bank" },
  { symbol: "CANBK", name: "Canara Bank", exchange: "NSE", sector: "Banks", industry: "Public Bank" },
  { symbol: "UNIONBANK", name: "Union Bank of India", exchange: "NSE", sector: "Banks", industry: "Public Bank" },
  { symbol: "INDIANB", name: "Indian Bank", exchange: "NSE", sector: "Banks", industry: "Public Bank" },
  { symbol: "FEDERALBNK", name: "Federal Bank", exchange: "NSE", sector: "Banks", industry: "Private Bank" },
  { symbol: "IDFCFIRSTB", name: "IDFC First Bank", exchange: "NSE", sector: "Banks", industry: "Private Bank" },
  { symbol: "BANDHANBNK", name: "Bandhan Bank", exchange: "NSE", sector: "Banks", industry: "Private Bank" },
  { symbol: "AUBANK", name: "AU Small Finance Bank", exchange: "NSE", sector: "Banks", industry: "Small Finance" },
  { symbol: "RBLBANK", name: "RBL Bank", exchange: "NSE", sector: "Banks", industry: "Private Bank" },
  { symbol: "YESBANK", name: "Yes Bank", exchange: "NSE", sector: "Banks", industry: "Private Bank" },
  { symbol: "IDBI", name: "IDBI Bank", exchange: "NSE", sector: "Banks", industry: "Private Bank" },
  { symbol: "CHOLAFIN", name: "Cholamandalam Investment", exchange: "NSE", sector: "NBFC", industry: "Consumer Finance" },
  { symbol: "MUTHOOTFIN", name: "Muthoot Finance", exchange: "NSE", sector: "NBFC", industry: "Gold Loans" },
  { symbol: "MANAPPURAM", name: "Manappuram Finance", exchange: "NSE", sector: "NBFC", industry: "Gold Loans" },
  { symbol: "LICHSGFIN", name: "LIC Housing Finance", exchange: "NSE", sector: "NBFC", industry: "Housing Finance" },
  { symbol: "PFC", name: "Power Finance Corporation", exchange: "NSE", sector: "NBFC", industry: "Infra Finance" },
  { symbol: "RECLTD", name: "REC", exchange: "NSE", sector: "NBFC", industry: "Infra Finance" },
  { symbol: "IRFC", name: "Indian Railway Finance", exchange: "NSE", sector: "NBFC", industry: "Infra Finance" },
  { symbol: "SHRIRAMFIN", name: "Shriram Finance", exchange: "NSE", sector: "NBFC", industry: "Consumer Finance" },
  { symbol: "ICICIGI", name: "ICICI Lombard General Insurance", exchange: "NSE", sector: "Insurance", industry: "General Insurance" },
  { symbol: "ICICIPRULI", name: "ICICI Prudential Life", exchange: "NSE", sector: "Insurance", industry: "Life Insurance" },
  { symbol: "BAJAJHLDNG", name: "Bajaj Holdings", exchange: "NSE", sector: "NBFC", industry: "Holding Company" },
  { symbol: "HDFCAMC", name: "HDFC Asset Management", exchange: "NSE", sector: "NBFC", industry: "Asset Management" },
  { symbol: "NIPPONLIFE", name: "Nippon Life India AMC", exchange: "NSE", sector: "NBFC", industry: "Asset Management" },
  { symbol: "BSE", name: "BSE", exchange: "NSE", sector: "Other", industry: "Exchange" },
  { symbol: "MCX", name: "Multi Commodity Exchange", exchange: "NSE", sector: "Other", industry: "Exchange" },
  { symbol: "CDSL", name: "Central Depository Services", exchange: "NSE", sector: "Other", industry: "Depository" },
  { symbol: "LTIM", name: "LTIMindtree", exchange: "NSE", sector: "IT", industry: "IT Services" },
  { symbol: "PERSISTENT", name: "Persistent Systems", exchange: "NSE", sector: "IT", industry: "IT Services" },
  { symbol: "COFORGE", name: "Coforge", exchange: "NSE", sector: "IT", industry: "IT Services" },
  { symbol: "MPHASIS", name: "Mphasis", exchange: "NSE", sector: "IT", industry: "IT Services" },
  { symbol: "LTTS", name: "L&T Technology Services", exchange: "NSE", sector: "IT", industry: "Engineering R&D" },
  { symbol: "OFSS", name: "Oracle Financial Services", exchange: "NSE", sector: "IT", industry: "Software Products" },
  { symbol: "TATAELXSI", name: "Tata Elxsi", exchange: "NSE", sector: "IT", industry: "Engineering R&D" },
  { symbol: "KPITTECH", name: "KPIT Technologies", exchange: "NSE", sector: "IT", industry: "Engineering R&D" },
  { symbol: "INTELLECT", name: "Intellect Design Arena", exchange: "NSE", sector: "IT", industry: "Software Products" },
  { symbol: "NAUKRI", name: "Info Edge", exchange: "NSE", sector: "IT", industry: "Internet" },
  { symbol: "AUROPHARMA", name: "Aurobindo Pharma", exchange: "NSE", sector: "Pharma", industry: "Pharmaceuticals" },
  { symbol: "LUPIN", name: "Lupin", exchange: "NSE", sector: "Pharma", industry: "Pharmaceuticals" },
  { symbol: "TORNTPHARM", name: "Torrent Pharmaceuticals", exchange: "NSE", sector: "Pharma", industry: "Pharmaceuticals" },
  { symbol: "ZYDUSLIFE", name: "Zydus Lifesciences", exchange: "NSE", sector: "Pharma", industry: "Pharmaceuticals" },
  { symbol: "MANKIND", name: "Mankind Pharma", exchange: "NSE", sector: "Pharma", industry: "Pharmaceuticals" },
  { symbol: "ALKEM", name: "Alkem Laboratories", exchange: "NSE", sector: "Pharma", industry: "Pharmaceuticals" },
  { symbol: "GLENMARK", name: "Glenmark Pharmaceuticals", exchange: "NSE", sector: "Pharma", industry: "Pharmaceuticals" },
  { symbol: "BIOCON", name: "Biocon", exchange: "NSE", sector: "Pharma", industry: "Biotech" },
  { symbol: "ABBOTINDIA", name: "Abbott India", exchange: "NSE", sector: "Pharma", industry: "Pharmaceuticals" },
  { symbol: "GLAND", name: "Gland Pharma", exchange: "NSE", sector: "Pharma", industry: "Pharmaceuticals" },
  { symbol: "FORTIS", name: "Fortis Healthcare", exchange: "NSE", sector: "Pharma", industry: "Healthcare Services" },
  { symbol: "MAXHEALTH", name: "Max Healthcare", exchange: "NSE", sector: "Pharma", industry: "Healthcare Services" },
  { symbol: "DRLAL", name: "Dr Lal Pathlabs", exchange: "NSE", sector: "Pharma", industry: "Diagnostics" },
  { symbol: "METROPOLIS", name: "Metropolis Healthcare", exchange: "NSE", sector: "Pharma", industry: "Diagnostics" },
  { symbol: "LAURUSLABS", name: "Laurus Labs", exchange: "NSE", sector: "Pharma", industry: "Pharmaceuticals" },
  { symbol: "TVSMOTOR", name: "TVS Motor Company", exchange: "NSE", sector: "Auto", industry: "Two Wheelers" },
  { symbol: "ASHOKLEY", name: "Ashok Leyland", exchange: "NSE", sector: "Auto", industry: "Commercial Vehicles" },
  { symbol: "MOTHERSON", name: "Samvardhana Motherson", exchange: "NSE", sector: "Auto", industry: "Auto Components" },
  { symbol: "BHARATFORG", name: "Bharat Forge", exchange: "NSE", sector: "Auto", industry: "Auto Components" },
  { symbol: "BOSCHLTD", name: "Bosch", exchange: "NSE", sector: "Auto", industry: "Auto Components" },
  { symbol: "MRF", name: "MRF", exchange: "NSE", sector: "Auto", industry: "Tyres" },
  { symbol: "BALKRISIND", name: "Balkrishna Industries", exchange: "NSE", sector: "Auto", industry: "Tyres" },
  { symbol: "APOLLOTYRE", name: "Apollo Tyres", exchange: "NSE", sector: "Auto", industry: "Tyres" },
  { symbol: "CEATLTD", name: "CEAT", exchange: "NSE", sector: "Auto", industry: "Tyres" },
  { symbol: "EXIDEIND", name: "Exide Industries", exchange: "NSE", sector: "Auto", industry: "Batteries" },
  { symbol: "AMARAJABAT", name: "Amara Raja Energy", exchange: "NSE", sector: "Auto", industry: "Batteries" },
  { symbol: "TRENT", name: "Trent", exchange: "NSE", sector: "Consumer", industry: "Retail" },
  { symbol: "PAGEIND", name: "Page Industries", exchange: "NSE", sector: "Textiles", industry: "Apparel" },
  { symbol: "VBL", name: "Varun Beverages", exchange: "NSE", sector: "FMCG", industry: "Beverages" },
  { symbol: "UNITDSPR", name: "United Spirits", exchange: "NSE", sector: "FMCG", industry: "Beverages" },
  { symbol: "UBL", name: "United Breweries", exchange: "NSE", sector: "FMCG", industry: "Beverages" },
  { symbol: "RADICO", name: "Radico Khaitan", exchange: "NSE", sector: "FMCG", industry: "Beverages" },
  { symbol: "JUBLFOOD", name: "Jubilant FoodWorks", exchange: "NSE", sector: "Consumer", industry: "Restaurants" },
  { symbol: "DEVYANI", name: "Devyani International", exchange: "NSE", sector: "Consumer", industry: "Restaurants" },
  { symbol: "WESTLIFE", name: "Westlife Foodworld", exchange: "NSE", sector: "Consumer", industry: "Restaurants" },
  { symbol: "ABFRL", name: "Aditya Birla Fashion", exchange: "NSE", sector: "Textiles", industry: "Apparel Retail" },
  { symbol: "ADITYABIRLA", name: "Aditya Birla Capital", exchange: "NSE", sector: "NBFC", industry: "Diversified Financial" },
  { symbol: "SHOPERSTOP", name: "Shoppers Stop", exchange: "NSE", sector: "Consumer", industry: "Retail" },
  { symbol: "VMART", name: "V-Mart Retail", exchange: "NSE", sector: "Consumer", industry: "Retail" },
  { symbol: "RELAXO", name: "Relaxo Footwears", exchange: "NSE", sector: "Consumer", industry: "Footwear" },
  { symbol: "BATAINDIA", name: "Bata India", exchange: "NSE", sector: "Consumer", industry: "Footwear" },
  { symbol: "CROMPTON", name: "Crompton Greaves Consumer", exchange: "NSE", sector: "Consumer", industry: "Consumer Electronics" },
  { symbol: "WHIRLPOOL", name: "Whirlpool of India", exchange: "NSE", sector: "Consumer", industry: "Consumer Durables" },
  { symbol: "DIXON", name: "Dixon Technologies", exchange: "NSE", sector: "Consumer", industry: "Consumer Electronics" },
  { symbol: "AMBER", name: "Amber Enterprises", exchange: "NSE", sector: "Consumer", industry: "Consumer Durables" },
  { symbol: "KAJARIACER", name: "Kajaria Ceramics", exchange: "NSE", sector: "Consumer", industry: "Ceramics" },
  { symbol: "SIEMENS", name: "Siemens", exchange: "NSE", sector: "Capital Goods", industry: "Electrical Equipment" },
  { symbol: "ABB", name: "ABB India", exchange: "NSE", sector: "Capital Goods", industry: "Electrical Equipment" },
  { symbol: "HONAUT", name: "Honeywell Automation", exchange: "NSE", sector: "Capital Goods", industry: "Industrial Automation" },
  { symbol: "BHEL", name: "BHEL", exchange: "NSE", sector: "Capital Goods", industry: "Power Equipment" },
  { symbol: "THERMAX", name: "Thermax", exchange: "NSE", sector: "Capital Goods", industry: "Industrial Engg" },
  { symbol: "CUMMINSIND", name: "Cummins India", exchange: "NSE", sector: "Capital Goods", industry: "Industrial Engg" },
  { symbol: "POLYCAB", name: "Polycab India", exchange: "NSE", sector: "Capital Goods", industry: "Cables" },
  { symbol: "KEI", name: "KEI Industries", exchange: "NSE", sector: "Capital Goods", industry: "Cables" },
  { symbol: "ASTRAL", name: "Astral", exchange: "NSE", sector: "Capital Goods", industry: "Plastics" },
  { symbol: "SUPREMEIND", name: "Supreme Industries", exchange: "NSE", sector: "Capital Goods", industry: "Plastics" },
  { symbol: "TIINDIA", name: "Tube Investments", exchange: "NSE", sector: "Capital Goods", industry: "Industrial Engg" },
  { symbol: "PIIND", name: "PI Industries", exchange: "NSE", sector: "Chemicals", industry: "Agrochemicals" },
  { symbol: "SRF", name: "SRF", exchange: "NSE", sector: "Chemicals", industry: "Specialty Chemicals" },
  { symbol: "AARTIIND", name: "Aarti Industries", exchange: "NSE", sector: "Chemicals", industry: "Specialty Chemicals" },
  { symbol: "TATACHEM", name: "Tata Chemicals", exchange: "NSE", sector: "Chemicals", industry: "Commodity Chemicals" },
  { symbol: "GNFC", name: "GNFC", exchange: "NSE", sector: "Chemicals", industry: "Fertilisers" },
  { symbol: "DEEPAKNTR", name: "Deepak Nitrite", exchange: "NSE", sector: "Chemicals", industry: "Specialty Chemicals" },
  { symbol: "NAVINFLUOR", name: "Navin Fluorine", exchange: "NSE", sector: "Chemicals", industry: "Specialty Chemicals" },
  { symbol: "VINATIORGA", name: "Vinati Organics", exchange: "NSE", sector: "Chemicals", industry: "Specialty Chemicals" },
  { symbol: "CHAMBLFERT", name: "Chambal Fertilisers", exchange: "NSE", sector: "Chemicals", industry: "Fertilisers" },
  { symbol: "COROMANDEL", name: "Coromandel International", exchange: "NSE", sector: "Chemicals", industry: "Fertilisers" },
  { symbol: "GODREJPROP", name: "Godrej Properties", exchange: "NSE", sector: "Realty", industry: "Real Estate" },
  { symbol: "OBEROIRLTY", name: "Oberoi Realty", exchange: "NSE", sector: "Realty", industry: "Real Estate" },
  { symbol: "PRESTIGE", name: "Prestige Estates", exchange: "NSE", sector: "Realty", industry: "Real Estate" },
  { symbol: "PHOENIXLTD", name: "Phoenix Mills", exchange: "NSE", sector: "Realty", industry: "Real Estate" },
  { symbol: "BRIGADE", name: "Brigade Enterprises", exchange: "NSE", sector: "Realty", industry: "Real Estate" },
  { symbol: "MAHLIFE", name: "Mahindra Lifespace", exchange: "NSE", sector: "Realty", industry: "Real Estate" },
  { symbol: "GMRINFRA", name: "GMR Airports Infra", exchange: "NSE", sector: "Infrastructure", industry: "Airports" },
  { symbol: "IRB", name: "IRB Infrastructure", exchange: "NSE", sector: "Infrastructure", industry: "Roads" },
  { symbol: "KNRCON", name: "KNR Constructions", exchange: "NSE", sector: "Infrastructure", industry: "Construction" },
  { symbol: "NCC", name: "NCC", exchange: "NSE", sector: "Infrastructure", industry: "Construction" },
  { symbol: "PNCINFRA", name: "PNC Infratech", exchange: "NSE", sector: "Infrastructure", industry: "Roads" },
  { symbol: "CONCOR", name: "Container Corporation", exchange: "NSE", sector: "Logistics", industry: "Container Logistics" },
  { symbol: "BLUEDART", name: "Blue Dart Express", exchange: "NSE", sector: "Logistics", industry: "Courier" },
  { symbol: "DELHIVERY", name: "Delhivery", exchange: "NSE", sector: "Logistics", industry: "Courier" },
  { symbol: "TCI", name: "Transport Corporation", exchange: "NSE", sector: "Logistics", industry: "Trucking" },
  { symbol: "VTL", name: "Vardhman Textiles", exchange: "NSE", sector: "Textiles", industry: "Textiles" },
  { symbol: "WELSPUNIND", name: "Welspun Living", exchange: "NSE", sector: "Textiles", industry: "Home Textiles" },
  { symbol: "TRIDENT", name: "Trident", exchange: "NSE", sector: "Textiles", industry: "Home Textiles" },
  { symbol: "SUNTV", name: "Sun TV Network", exchange: "NSE", sector: "Media", industry: "Broadcasting" },
  { symbol: "PVRINOX", name: "PVR INOX", exchange: "NSE", sector: "Media", industry: "Exhibition" },
  { symbol: "TATACOMM", name: "Tata Communications", exchange: "NSE", sector: "Telecom", industry: "Telecom Services" },
  { symbol: "IDEA", name: "Vodafone Idea", exchange: "NSE", sector: "Telecom", industry: "Telecom Services" },
  { symbol: "ROUTE", name: "Route Mobile", exchange: "NSE", sector: "Telecom", industry: "Telecom Services" },
  { symbol: "HAL", name: "Hindustan Aeronautics", exchange: "NSE", sector: "Capital Goods", industry: "Defence" },
  { symbol: "BEL", name: "Bharat Electronics", exchange: "NSE", sector: "Capital Goods", industry: "Defence" },
  { symbol: "BDL", name: "Bharat Dynamics", exchange: "NSE", sector: "Capital Goods", industry: "Defence" },
  { symbol: "MAZDOCK", name: "Mazagon Dock Shipbuilders", exchange: "NSE", sector: "Capital Goods", industry: "Defence" },
  { symbol: "COCHINSHIP", name: "Cochin Shipyard", exchange: "NSE", sector: "Capital Goods", industry: "Defence" },
  { symbol: "GRSE", name: "Garden Reach Shipbuilders", exchange: "NSE", sector: "Capital Goods", industry: "Defence" },
  { symbol: "DATAPATTNS", name: "Data Patterns", exchange: "NSE", sector: "Capital Goods", industry: "Defence" },
  { symbol: "PARAS", name: "Paras Defence", exchange: "NSE", sector: "Capital Goods", industry: "Defence" },
  { symbol: "MAPMYINDIA", name: "C.E. Info Systems", exchange: "NSE", sector: "IT", industry: "Software Products" },
  { symbol: "EASEMYTRIP", name: "Easy Trip Planners", exchange: "NSE", sector: "Consumer", industry: "Travel" },
  { symbol: "RAILTEL", name: "RailTel Corporation", exchange: "NSE", sector: "Telecom", industry: "Telecom Services" },
  { symbol: "IREDA", name: "Indian Renewable Energy", exchange: "NSE", sector: "NBFC", industry: "Infra Finance" },
  { symbol: "TATATECH", name: "Tata Technologies", exchange: "NSE", sector: "IT", industry: "Engineering R&D" },
  { symbol: "JIOFIN", name: "Jio Financial Services", exchange: "NSE", sector: "NBFC", industry: "Diversified Financial" },
  { symbol: "ZAGGLE", name: "Zaggle Prepaid Ocean Services", exchange: "NSE", sector: "Other", industry: "Fintech" },
  { symbol: "IDEAFORGE", name: "ideaForge Technology", exchange: "NSE", sector: "Capital Goods", industry: "Defence" },
  { symbol: "CSBBANK", name: "CSB Bank", exchange: "NSE", sector: "Banks", industry: "Private Bank" },
  { symbol: "DCBBANK", name: "DCB Bank", exchange: "NSE", sector: "Banks", industry: "Private Bank" },
  { symbol: "KARURVYSYA", name: "Karur Vysya Bank", exchange: "NSE", sector: "Banks", industry: "Private Bank" },
  { symbol: "SOUTHBANK", name: "South Indian Bank", exchange: "NSE", sector: "Banks", industry: "Private Bank" },
  { symbol: "TMB", name: "Tamilnad Mercantile Bank", exchange: "NSE", sector: "Banks", industry: "Private Bank" },
  { symbol: "UJJIVANSFB", name: "Ujjivan Small Finance Bank", exchange: "NSE", sector: "Banks", industry: "Small Finance Bank" },
  { symbol: "EQUITASBNK", name: "Equitas Small Finance Bank", exchange: "NSE", sector: "Banks", industry: "Small Finance Bank" },
  { symbol: "SURYODAY", name: "Suryoday Small Finance Bank", exchange: "NSE", sector: "Banks", industry: "Small Finance Bank" },
  { symbol: "ESAFSFB", name: "ESAF Small Finance Bank", exchange: "NSE", sector: "Banks", industry: "Small Finance Bank" },
  { symbol: "FINOPB", name: "Fino Payments Bank", exchange: "NSE", sector: "Banks", industry: "Payments Bank" },
  { symbol: "JKBANK", name: "Jammu & Kashmir Bank", exchange: "NSE", sector: "Banks", industry: "PSU Bank" },
  { symbol: "PSB", name: "Punjab & Sind Bank", exchange: "NSE", sector: "Banks", industry: "PSU Bank" },
  { symbol: "MAHABANK", name: "Bank of Maharashtra", exchange: "NSE", sector: "Banks", industry: "PSU Bank" },
  { symbol: "UCOBANK", name: "UCO Bank", exchange: "NSE", sector: "Banks", industry: "PSU Bank" },
  { symbol: "CENTRALBK", name: "Central Bank of India", exchange: "NSE", sector: "Banks", industry: "PSU Bank" },
  { symbol: "IOB", name: "Indian Overseas Bank", exchange: "NSE", sector: "Banks", industry: "PSU Bank" },
  { symbol: "ABCAPITAL", name: "Aditya Birla Capital", exchange: "NSE", sector: "NBFC", industry: "Diversified Financial" },
  { symbol: "LTF", name: "L&T Finance Holdings", exchange: "NSE", sector: "NBFC", industry: "Diversified NBFC" },
  { symbol: "POONAWALLA", name: "Poonawalla Fincorp", exchange: "NSE", sector: "NBFC", industry: "Consumer Finance" },
  { symbol: "SUNDARMFIN", name: "Sundaram Finance", exchange: "NSE", sector: "NBFC", industry: "Vehicle Finance" },
  { symbol: "MMFIN", name: "Mahindra & Mahindra Financial", exchange: "NSE", sector: "NBFC", industry: "Vehicle Finance" },
  { symbol: "CHOLAHLDNG", name: "Cholamandalam Financial Holdings", exchange: "NSE", sector: "NBFC", industry: "Diversified Financial" },
  { symbol: "AAVAS", name: "Aavas Financiers", exchange: "NSE", sector: "NBFC", industry: "Housing Finance" },
  { symbol: "AADHARHFC", name: "Aadhar Housing Finance", exchange: "NSE", sector: "NBFC", industry: "Housing Finance" },
  { symbol: "APTUS", name: "Aptus Value Housing Finance", exchange: "NSE", sector: "NBFC", industry: "Housing Finance" },
  { symbol: "HOMEFIRST", name: "Home First Finance", exchange: "NSE", sector: "NBFC", industry: "Housing Finance" },
  { symbol: "PNBHOUSING", name: "PNB Housing Finance", exchange: "NSE", sector: "NBFC", industry: "Housing Finance" },
  { symbol: "REPCOHOME", name: "Repco Home Finance", exchange: "NSE", sector: "NBFC", industry: "Housing Finance" },
  { symbol: "CANFINHOME", name: "Can Fin Homes", exchange: "NSE", sector: "NBFC", industry: "Housing Finance" },
  { symbol: "INDIASHLTR", name: "India Shelter Finance", exchange: "NSE", sector: "NBFC", industry: "Housing Finance" },
  { symbol: "FIVESTAR", name: "Five Star Business Finance", exchange: "NSE", sector: "NBFC", industry: "SME Finance" },
  { symbol: "CREDITACC", name: "CreditAccess Grameen", exchange: "NSE", sector: "NBFC", industry: "Microfinance" },
  { symbol: "FUSION", name: "Fusion Microfinance", exchange: "NSE", sector: "NBFC", industry: "Microfinance" },
  { symbol: "SPANDANA", name: "Spandana Sphoorty", exchange: "NSE", sector: "NBFC", industry: "Microfinance" },
  { symbol: "EDELWEISS", name: "Edelweiss Financial Services", exchange: "NSE", sector: "NBFC", industry: "Diversified Financial" },
  { symbol: "MOTILALOFS", name: "Motilal Oswal Financial", exchange: "NSE", sector: "NBFC", industry: "Capital Markets" },
  { symbol: "IIFL", name: "IIFL Finance", exchange: "NSE", sector: "NBFC", industry: "Diversified NBFC" },
  { symbol: "IIFLSEC", name: "IIFL Securities", exchange: "NSE", sector: "NBFC", industry: "Capital Markets" },
  { symbol: "ANGELONE", name: "Angel One", exchange: "NSE", sector: "NBFC", industry: "Capital Markets" },
  { symbol: "CAMS", name: "Computer Age Management Services", exchange: "NSE", sector: "NBFC", industry: "Capital Markets" },
  { symbol: "KFINTECH", name: "KFin Technologies", exchange: "NSE", sector: "NBFC", industry: "Capital Markets" },
  { symbol: "NUVAMA", name: "Nuvama Wealth Management", exchange: "NSE", sector: "NBFC", industry: "Wealth Management" },
  { symbol: "PRUDENT", name: "Prudent Corporate Advisory", exchange: "NSE", sector: "NBFC", industry: "Wealth Management" },
  { symbol: "ANANDRATHI", name: "Anand Rathi Wealth", exchange: "NSE", sector: "NBFC", industry: "Wealth Management" },
  { symbol: "HUDCO", name: "Housing & Urban Development Corp", exchange: "NSE", sector: "NBFC", industry: "Housing Finance" },
  { symbol: "CYIENT", name: "Cyient", exchange: "NSE", sector: "IT", industry: "Engineering R&D" },
  { symbol: "ZENSARTECH", name: "Zensar Technologies", exchange: "NSE", sector: "IT", industry: "IT Services" },
  { symbol: "BIRLASOFT", name: "Birlasoft", exchange: "NSE", sector: "IT", industry: "IT Services" },
  { symbol: "RAMCOSYS", name: "Ramco Systems", exchange: "NSE", sector: "IT", industry: "Software Products" },
  { symbol: "NEWGEN", name: "Newgen Software", exchange: "NSE", sector: "IT", industry: "Software Products" },
  { symbol: "TANLA", name: "Tanla Platforms", exchange: "NSE", sector: "IT", industry: "Communication Platform" },
  { symbol: "AFFLE", name: "Affle India", exchange: "NSE", sector: "IT", industry: "AdTech" },
  { symbol: "HAPPSTMNDS", name: "Happiest Minds Technologies", exchange: "NSE", sector: "IT", industry: "IT Services" },
  { symbol: "FSL", name: "Firstsource Solutions", exchange: "NSE", sector: "IT", industry: "BPO" },
  { symbol: "SONATSOFTW", name: "Sonata Software", exchange: "NSE", sector: "IT", industry: "IT Services" },
  { symbol: "RATEGAIN", name: "RateGain Travel Technologies", exchange: "NSE", sector: "IT", industry: "Travel Software" },
  { symbol: "ECLERX", name: "eClerx Services", exchange: "NSE", sector: "IT", industry: "KPO" },
  { symbol: "MASTEK", name: "Mastek", exchange: "NSE", sector: "IT", industry: "IT Services" },
  { symbol: "NIITLTD", name: "NIIT Learning Systems", exchange: "NSE", sector: "IT", industry: "EdTech" },
  { symbol: "NIITMTS", name: "NIIT Limited", exchange: "NSE", sector: "IT", industry: "Education" },
  { symbol: "JUSTDIAL", name: "Just Dial", exchange: "NSE", sector: "IT", industry: "Internet" },
  { symbol: "INDIAMART", name: "IndiaMART InterMESH", exchange: "NSE", sector: "IT", industry: "B2B Internet" },
  { symbol: "INFIBEAM", name: "Infibeam Avenues", exchange: "NSE", sector: "IT", industry: "Payments" },
  { symbol: "TECHNOE", name: "Techno Electric & Engineering", exchange: "NSE", sector: "IT", industry: "Power EPC" },
  { symbol: "ESCORTS", name: "Escorts Kubota", exchange: "NSE", sector: "Auto", industry: "Tractors" },
  { symbol: "FORCEMOT", name: "Force Motors", exchange: "NSE", sector: "Auto", industry: "Commercial Vehicles" },
  { symbol: "OLECTRA", name: "Olectra Greentech", exchange: "NSE", sector: "Auto", industry: "Electric Buses" },
  { symbol: "SUNDRMFAST", name: "Sundram Fasteners", exchange: "NSE", sector: "Auto", industry: "Fasteners" },
  { symbol: "JKTYRE", name: "JK Tyre & Industries", exchange: "NSE", sector: "Auto", industry: "Tyres" },
  { symbol: "ENDURANCE", name: "Endurance Technologies", exchange: "NSE", sector: "Auto", industry: "Auto Components" },
  { symbol: "MINDAIND", name: "Uno Minda", exchange: "NSE", sector: "Auto", industry: "Auto Components" },
  { symbol: "SUPRAJIT", name: "Suprajit Engineering", exchange: "NSE", sector: "Auto", industry: "Auto Components" },
  { symbol: "SCHAEFFLER", name: "Schaeffler India", exchange: "NSE", sector: "Auto", industry: "Bearings" },
  { symbol: "SKFINDIA", name: "SKF India", exchange: "NSE", sector: "Auto", industry: "Bearings" },
  { symbol: "TIMKEN", name: "Timken India", exchange: "NSE", sector: "Auto", industry: "Bearings" },
  { symbol: "WHEELS", name: "Wheels India", exchange: "NSE", sector: "Auto", industry: "Auto Components" },
  { symbol: "JBMA", name: "JBM Auto", exchange: "NSE", sector: "Auto", industry: "Auto Components" },
  { symbol: "SANSERA", name: "Sansera Engineering", exchange: "NSE", sector: "Auto", industry: "Auto Components" },
  { symbol: "SUBROS", name: "Subros", exchange: "NSE", sector: "Auto", industry: "Auto AC" },
  { symbol: "GABRIEL", name: "Gabriel India", exchange: "NSE", sector: "Auto", industry: "Auto Components" },
  { symbol: "SHARDAMOTR", name: "Sharda Motor Industries", exchange: "NSE", sector: "Auto", industry: "Auto Components" },
  { symbol: "PRECAM", name: "Precision Camshafts", exchange: "NSE", sector: "Auto", industry: "Auto Components" },
  { symbol: "LUMAXTECH", name: "Lumax Auto Technologies", exchange: "NSE", sector: "Auto", industry: "Auto Components" },
  { symbol: "SONACOMS", name: "Sona BLW Precision Forgings", exchange: "NSE", sector: "Auto", industry: "EV Components" },
  { symbol: "PFIZER", name: "Pfizer", exchange: "NSE", sector: "Pharma", industry: "Pharmaceuticals" },
  { symbol: "SANOFI", name: "Sanofi India", exchange: "NSE", sector: "Pharma", industry: "Pharmaceuticals" },
  { symbol: "GLAXO", name: "GlaxoSmithKline Pharma", exchange: "NSE", sector: "Pharma", industry: "Pharmaceuticals" },
  { symbol: "AJANTPHARM", name: "Ajanta Pharma", exchange: "NSE", sector: "Pharma", industry: "Pharmaceuticals" },
  { symbol: "IPCALAB", name: "IPCA Laboratories", exchange: "NSE", sector: "Pharma", industry: "Pharmaceuticals" },
  { symbol: "NATCOPHARM", name: "Natco Pharma", exchange: "NSE", sector: "Pharma", industry: "Pharmaceuticals" },
  { symbol: "JBCHEPHARM", name: "J B Chemicals", exchange: "NSE", sector: "Pharma", industry: "Pharmaceuticals" },
  { symbol: "ERIS", name: "Eris Lifesciences", exchange: "NSE", sector: "Pharma", industry: "Pharmaceuticals" },
  { symbol: "GRANULES", name: "Granules India", exchange: "NSE", sector: "Pharma", industry: "API" },
  { symbol: "NH", name: "Narayana Hrudayalaya", exchange: "NSE", sector: "Pharma", industry: "Hospitals" },
  { symbol: "RAINBOW", name: "Rainbow Children's Medicare", exchange: "NSE", sector: "Pharma", industry: "Hospitals" },
  { symbol: "KIMS", name: "Krishna Institute of Medical Sciences", exchange: "NSE", sector: "Pharma", industry: "Hospitals" },
  { symbol: "ASTERDM", name: "Aster DM Healthcare", exchange: "NSE", sector: "Pharma", industry: "Hospitals" },
  { symbol: "MEDANTA", name: "Global Health (Medanta)", exchange: "NSE", sector: "Pharma", industry: "Hospitals" },
  { symbol: "JUPITER", name: "Jupiter Life Line Hospitals", exchange: "NSE", sector: "Pharma", industry: "Hospitals" },
  { symbol: "THYROCARE", name: "Thyrocare Technologies", exchange: "NSE", sector: "Pharma", industry: "Diagnostics" },
  { symbol: "VIJAYA", name: "Vijaya Diagnostic Centre", exchange: "NSE", sector: "Pharma", industry: "Diagnostics" },
  { symbol: "POLYMED", name: "Poly Medicure", exchange: "NSE", sector: "Pharma", industry: "Medical Devices" },
  { symbol: "SUPRIYA", name: "Supriya Lifescience", exchange: "NSE", sector: "Pharma", industry: "API" },
  { symbol: "WOCKPHARMA", name: "Wockhardt", exchange: "NSE", sector: "Pharma", industry: "Pharmaceuticals" },
  { symbol: "SYNGENE", name: "Syngene International", exchange: "NSE", sector: "Pharma", industry: "CRAMS" },
  { symbol: "PIRAMALPHL", name: "Piramal Pharma", exchange: "NSE", sector: "Pharma", industry: "CRAMS" },
  { symbol: "STAR", name: "Strides Pharma Science", exchange: "NSE", sector: "Pharma", industry: "Pharmaceuticals" },
  { symbol: "CAPLIPOINT", name: "Caplin Point Laboratories", exchange: "NSE", sector: "Pharma", industry: "Pharmaceuticals" },
  { symbol: "EMAMILTD", name: "Emami", exchange: "NSE", sector: "FMCG", industry: "Personal Care" },
  { symbol: "JYOTHYLAB", name: "Jyothy Labs", exchange: "NSE", sector: "FMCG", industry: "Home Care" },
  { symbol: "MCDOWELL-N", name: "United Spirits", exchange: "NSE", sector: "FMCG", industry: "Spirits" },
  { symbol: "VSTIND", name: "VST Industries", exchange: "NSE", sector: "FMCG", industry: "Tobacco" },
  { symbol: "GODFRYPHLP", name: "Godfrey Phillips India", exchange: "NSE", sector: "FMCG", industry: "Tobacco" },
  { symbol: "PATANJALI", name: "Patanjali Foods", exchange: "NSE", sector: "FMCG", industry: "Edible Oils" },
  { symbol: "ADANIWILMAR", name: "Adani Wilmar", exchange: "NSE", sector: "FMCG", industry: "Edible Oils" },
  { symbol: "BIKAJI", name: "Bikaji Foods International", exchange: "NSE", sector: "FMCG", industry: "Snacks" },
  { symbol: "SAPPHIRE", name: "Sapphire Foods India", exchange: "NSE", sector: "FMCG", industry: "QSR" },
  { symbol: "RESTAURANT", name: "Restaurant Brands Asia", exchange: "NSE", sector: "FMCG", industry: "QSR" },
  { symbol: "AVENUE", name: "Avenue Supermarts (DMart)", exchange: "NSE", sector: "Consumer", industry: "Retail" },
  { symbol: "ADITBIRLA", name: "Aditya Birla Fashion & Retail", exchange: "NSE", sector: "Consumer", industry: "Apparel Retail" },
  { symbol: "RUPA", name: "Rupa & Company", exchange: "NSE", sector: "Consumer", industry: "Apparel" },
  { symbol: "DOLLAR", name: "Dollar Industries", exchange: "NSE", sector: "Consumer", industry: "Apparel" },
  { symbol: "METROBRAND", name: "Metro Brands", exchange: "NSE", sector: "Consumer", industry: "Footwear" },
  { symbol: "KALYANKJIL", name: "Kalyan Jewellers", exchange: "NSE", sector: "Consumer", industry: "Jewellery" },
  { symbol: "SENCO", name: "Senco Gold", exchange: "NSE", sector: "Consumer", industry: "Jewellery" },
  { symbol: "PCJEWELLER", name: "PC Jeweller", exchange: "NSE", sector: "Consumer", industry: "Jewellery" },
  { symbol: "TBOTEK", name: "TBO Tek", exchange: "NSE", sector: "Consumer", industry: "Travel Tech" },
  { symbol: "INDIGO", name: "InterGlobe Aviation (IndiGo)", exchange: "NSE", sector: "Consumer", industry: "Airlines" },
  { symbol: "SPICEJET", name: "SpiceJet", exchange: "NSE", sector: "Consumer", industry: "Airlines" },
  { symbol: "EIHOTEL", name: "EIH (Oberoi Hotels)", exchange: "NSE", sector: "Consumer", industry: "Hotels" },
  { symbol: "INDHOTEL", name: "Indian Hotels (Taj)", exchange: "NSE", sector: "Consumer", industry: "Hotels" },
  { symbol: "CHALET", name: "Chalet Hotels", exchange: "NSE", sector: "Consumer", industry: "Hotels" },
  { symbol: "LEMONTREE", name: "Lemon Tree Hotels", exchange: "NSE", sector: "Consumer", industry: "Hotels" },
  { symbol: "MAHLOG", name: "Mahindra Holidays & Resorts", exchange: "NSE", sector: "Consumer", industry: "Hospitality" },
  { symbol: "MRPL", name: "Mangalore Refinery", exchange: "NSE", sector: "Energy", industry: "Oil Refining" },
  { symbol: "AEGISCHEM", name: "Aegis Logistics", exchange: "NSE", sector: "Energy", industry: "Oil & Gas Logistics" },
  { symbol: "GSPL", name: "Gujarat State Petronet", exchange: "NSE", sector: "Energy", industry: "Gas Pipelines" },
  { symbol: "CESC", name: "CESC", exchange: "NSE", sector: "Power", industry: "Power Generation" },
  { symbol: "RPOWER", name: "Reliance Power", exchange: "NSE", sector: "Power", industry: "Power Generation" },
  { symbol: "INOXWIND", name: "Inox Wind", exchange: "NSE", sector: "Power", industry: "Wind Equipment" },
  { symbol: "SUZLON", name: "Suzlon Energy", exchange: "NSE", sector: "Power", industry: "Wind Equipment" },
  { symbol: "BFUTILITIE", name: "BF Utilities", exchange: "NSE", sector: "Power", industry: "Renewables" },
  { symbol: "INDIGRID", name: "India Grid Trust", exchange: "NSE", sector: "Power", industry: "Transmission" },
  { symbol: "POWERINDIA", name: "Hitachi Energy India", exchange: "NSE", sector: "Power", industry: "Power Equipment" },
  { symbol: "HINDCOPPER", name: "Hindustan Copper", exchange: "NSE", sector: "Metals", industry: "Copper" },
  { symbol: "NATIONALUM", name: "National Aluminium", exchange: "NSE", sector: "Metals", industry: "Aluminium" },
  { symbol: "JSL", name: "Jindal Stainless", exchange: "NSE", sector: "Metals", industry: "Stainless Steel" },
  { symbol: "APLAPOLLO", name: "APL Apollo Tubes", exchange: "NSE", sector: "Metals", industry: "Steel Tubes" },
  { symbol: "RATNAMANI", name: "Ratnamani Metals", exchange: "NSE", sector: "Metals", industry: "Steel Tubes" },
  { symbol: "WELCORP", name: "Welspun Corp", exchange: "NSE", sector: "Metals", industry: "Steel Pipes" },
  { symbol: "JSWHL", name: "JSW Holdings", exchange: "NSE", sector: "Metals", industry: "Holding Co" },
  { symbol: "GMDC", name: "Gujarat Mineral Development", exchange: "NSE", sector: "Metals", industry: "Mining" },
  { symbol: "GRAVITA", name: "Gravita India", exchange: "NSE", sector: "Metals", industry: "Lead Recycling" },
  { symbol: "JKCEMENT", name: "JK Cement", exchange: "NSE", sector: "Cement", industry: "Cement" },
  { symbol: "RAMCOCEM", name: "The Ramco Cements", exchange: "NSE", sector: "Cement", industry: "Cement" },
  { symbol: "JKLAKSHMI", name: "JK Lakshmi Cement", exchange: "NSE", sector: "Cement", industry: "Cement" },
  { symbol: "HEIDELBERG", name: "HeidelbergCement India", exchange: "NSE", sector: "Cement", industry: "Cement" },
  { symbol: "INDIACEM", name: "India Cements", exchange: "NSE", sector: "Cement", industry: "Cement" },
  { symbol: "BIRLACORPN", name: "Birla Corporation", exchange: "NSE", sector: "Cement", industry: "Cement" },
  { symbol: "STARCEMENT", name: "Star Cement", exchange: "NSE", sector: "Cement", industry: "Cement" },
  { symbol: "ORIENTCEM", name: "Orient Cement", exchange: "NSE", sector: "Cement", industry: "Cement" },
  { symbol: "MAXFIN", name: "Max Financial Services", exchange: "NSE", sector: "Insurance", industry: "Life Insurance" },
  { symbol: "STARHEALTH", name: "Star Health & Allied Insurance", exchange: "NSE", sector: "Insurance", industry: "Health Insurance" },
  { symbol: "NIACL", name: "New India Assurance", exchange: "NSE", sector: "Insurance", industry: "General Insurance" },
  { symbol: "GICRE", name: "General Insurance Corp of India", exchange: "NSE", sector: "Insurance", industry: "Reinsurance" },
  { symbol: "BHARTIHEXA", name: "Bharti Hexacom", exchange: "NSE", sector: "Telecom", industry: "Telecom Services" },
  { symbol: "INDUSTOWER", name: "Indus Towers", exchange: "NSE", sector: "Telecom", industry: "Telecom Infra" },
  { symbol: "STLTECH", name: "Sterlite Technologies", exchange: "NSE", sector: "Telecom", industry: "Optical Fibre" },
  { symbol: "HFCL", name: "HFCL", exchange: "NSE", sector: "Telecom", industry: "Telecom Equipment" },
  { symbol: "ITI", name: "ITI Limited", exchange: "NSE", sector: "Telecom", industry: "Telecom Equipment" },
  { symbol: "MTNL", name: "Mahanagar Telephone Nigam", exchange: "NSE", sector: "Telecom", industry: "Telecom Services" },
  { symbol: "TIPSMUSIC", name: "Tips Music", exchange: "NSE", sector: "Media", industry: "Music" },
  { symbol: "SAREGAMA", name: "Saregama India", exchange: "NSE", sector: "Media", industry: "Music" },
  { symbol: "NETWORK18", name: "Network18 Media", exchange: "NSE", sector: "Media", industry: "Media" },
  { symbol: "TV18BRDCST", name: "TV18 Broadcast", exchange: "NSE", sector: "Media", industry: "Broadcasting" },
  { symbol: "DISHTV", name: "Dish TV India", exchange: "NSE", sector: "Media", industry: "DTH" },
  { symbol: "DBCORP", name: "DB Corp", exchange: "NSE", sector: "Media", industry: "Print Media" },
  { symbol: "JAGRAN", name: "Jagran Prakashan", exchange: "NSE", sector: "Media", industry: "Print Media" },
  { symbol: "HATHWAY", name: "Hathway Cable & Datacom", exchange: "NSE", sector: "Media", industry: "Cable" },
  { symbol: "GTPL", name: "GTPL Hathway", exchange: "NSE", sector: "Media", industry: "Cable" },
  { symbol: "KANSAINER", name: "Kansai Nerolac Paints", exchange: "NSE", sector: "Chemicals", industry: "Paints" },
  { symbol: "AKZOINDIA", name: "Akzo Nobel India", exchange: "NSE", sector: "Chemicals", industry: "Paints" },
  { symbol: "INDIGOPNTS", name: "Indigo Paints", exchange: "NSE", sector: "Chemicals", industry: "Paints" },
  { symbol: "RALLIS", name: "Rallis India", exchange: "NSE", sector: "Chemicals", industry: "Agrochemicals" },
  { symbol: "BAYERCROP", name: "Bayer CropScience", exchange: "NSE", sector: "Chemicals", industry: "Agrochemicals" },
  { symbol: "SUMICHEM", name: "Sumitomo Chemical India", exchange: "NSE", sector: "Chemicals", industry: "Agrochemicals" },
  { symbol: "INSECTICID", name: "Insecticides India", exchange: "NSE", sector: "Chemicals", industry: "Agrochemicals" },
  { symbol: "DEEPAKFERT", name: "Deepak Fertilisers", exchange: "NSE", sector: "Chemicals", industry: "Fertilisers" },
  { symbol: "GUJFLUORO", name: "Gujarat Fluorochemicals", exchange: "NSE", sector: "Chemicals", industry: "Fluorochemicals" },
  { symbol: "FLUOROCHEM", name: "Anupam Rasayan", exchange: "NSE", sector: "Chemicals", industry: "Specialty Chemicals" },
  { symbol: "ATUL", name: "Atul", exchange: "NSE", sector: "Chemicals", industry: "Specialty Chemicals" },
  { symbol: "CLEAN", name: "Clean Science & Technology", exchange: "NSE", sector: "Chemicals", industry: "Specialty Chemicals" },
  { symbol: "GHCL", name: "GHCL", exchange: "NSE", sector: "Chemicals", industry: "Soda Ash" },
  { symbol: "DCMSHRIRAM", name: "DCM Shriram", exchange: "NSE", sector: "Chemicals", industry: "Diversified" },
  { symbol: "GSFC", name: "Gujarat State Fertilizers", exchange: "NSE", sector: "Chemicals", industry: "Fertilisers" },
  { symbol: "RCF", name: "Rashtriya Chemicals & Fertilizers", exchange: "NSE", sector: "Chemicals", industry: "Fertilisers" },
  { symbol: "NFL", name: "National Fertilizers", exchange: "NSE", sector: "Chemicals", industry: "Fertilisers" },
  { symbol: "FACT", name: "Fertilisers and Chemicals Travancore", exchange: "NSE", sector: "Chemicals", industry: "Fertilisers" },
  { symbol: "GAEL", name: "Gujarat Ambuja Exports", exchange: "NSE", sector: "Chemicals", industry: "Agri Processing" },
  { symbol: "ALKYLAMINE", name: "Alkyl Amines Chemicals", exchange: "NSE", sector: "Chemicals", industry: "Specialty Chemicals" },
  { symbol: "BALAMINES", name: "Balaji Amines", exchange: "NSE", sector: "Chemicals", industry: "Specialty Chemicals" },
  { symbol: "ROSSARI", name: "Rossari Biotech", exchange: "NSE", sector: "Chemicals", industry: "Specialty Chemicals" },
  { symbol: "EPIGRAL", name: "Epigral", exchange: "NSE", sector: "Chemicals", industry: "Chlor-Alkali" },
  { symbol: "TATVA", name: "Tatva Chintan Pharma Chem", exchange: "NSE", sector: "Chemicals", industry: "Specialty Chemicals" },
  { symbol: "JUBLINGREA", name: "Jubilant Ingrevia", exchange: "NSE", sector: "Chemicals", industry: "Specialty Chemicals" },
  { symbol: "JUBLPHARMA", name: "Jubilant Pharmova", exchange: "NSE", sector: "Pharma", industry: "Pharmaceuticals" },
  { symbol: "SUDARSCHEM", name: "Sudarshan Chemical", exchange: "NSE", sector: "Chemicals", industry: "Pigments" },
  { symbol: "GALAXYSURF", name: "Galaxy Surfactants", exchange: "NSE", sector: "Chemicals", industry: "Surfactants" },
  { symbol: "FINEORG", name: "Fine Organic Industries", exchange: "NSE", sector: "Chemicals", industry: "Oleochemicals" },
  { symbol: "PCBL", name: "PCBL Limited", exchange: "NSE", sector: "Chemicals", industry: "Carbon Black" },
  { symbol: "PHILLIPS", name: "Phillips Carbon Black", exchange: "NSE", sector: "Chemicals", industry: "Carbon Black" },
  { symbol: "BASF", name: "BASF India", exchange: "NSE", sector: "Chemicals", industry: "Specialty Chemicals" },
  { symbol: "BORORENEW", name: "Borosil Renewables", exchange: "NSE", sector: "Chemicals", industry: "Solar Glass" },
  { symbol: "BORO", name: "Borosil", exchange: "NSE", sector: "Chemicals", industry: "Glass" },
  { symbol: "CGPOWER", name: "CG Power & Industrial Solutions", exchange: "NSE", sector: "Capital Goods", industry: "Electrical Equipment" },
  { symbol: "MTARTECH", name: "MTAR Technologies", exchange: "NSE", sector: "Capital Goods", industry: "Defence Aerospace" },
  { symbol: "AZADENG", name: "Azad Engineering", exchange: "NSE", sector: "Capital Goods", industry: "Precision Eng" },
  { symbol: "ZENTECH", name: "Zen Technologies", exchange: "NSE", sector: "Capital Goods", industry: "Defence Training" },
  { symbol: "ASTRAMICRO", name: "Astra Microwave Products", exchange: "NSE", sector: "Capital Goods", industry: "Defence Electronics" },
  { symbol: "KIRLOSENG", name: "Kirloskar Oil Engines", exchange: "NSE", sector: "Capital Goods", industry: "Engines" },
  { symbol: "KIRLOSBROS", name: "Kirloskar Brothers", exchange: "NSE", sector: "Capital Goods", industry: "Pumps" },
  { symbol: "KIRLPUMPS", name: "Kirloskar Pneumatic", exchange: "NSE", sector: "Capital Goods", industry: "Compressors" },
  { symbol: "GREAVESCOT", name: "Greaves Cotton", exchange: "NSE", sector: "Capital Goods", industry: "Engines" },
  { symbol: "TIMETECHNO", name: "Time Technoplast", exchange: "NSE", sector: "Capital Goods", industry: "Industrial Packaging" },
  { symbol: "BLUESTARCO", name: "Blue Star", exchange: "NSE", sector: "Consumer", industry: "Cooling Products" },
  { symbol: "FINCABLES", name: "Finolex Cables", exchange: "NSE", sector: "Capital Goods", industry: "Wires & Cables" },
  { symbol: "FINPIPE", name: "Finolex Industries", exchange: "NSE", sector: "Capital Goods", industry: "PVC Pipes" },
  { symbol: "PRINCEPIPE", name: "Prince Pipes & Fittings", exchange: "NSE", sector: "Capital Goods", industry: "Plastic Pipes" },
  { symbol: "APOLLOPIPE", name: "Apollo Pipes", exchange: "NSE", sector: "Capital Goods", industry: "Plastic Pipes" },
  { symbol: "JINDALSAW", name: "Jindal Saw", exchange: "NSE", sector: "Capital Goods", industry: "Steel Pipes" },
  { symbol: "IFBIND", name: "IFB Industries", exchange: "NSE", sector: "Consumer", industry: "Home Appliances" },
  { symbol: "BAJAJELEC", name: "Bajaj Electricals", exchange: "NSE", sector: "Consumer", industry: "Electricals" },
  { symbol: "VGUARD", name: "V-Guard Industries", exchange: "NSE", sector: "Consumer", industry: "Electricals" },
  { symbol: "ORIENTELEC", name: "Orient Electric", exchange: "NSE", sector: "Consumer", industry: "Electricals" },
  { symbol: "KAYNES", name: "Kaynes Technology", exchange: "NSE", sector: "Capital Goods", industry: "EMS" },
  { symbol: "SYRMA", name: "Syrma SGS Technology", exchange: "NSE", sector: "Capital Goods", industry: "EMS" },
  { symbol: "ELIN", name: "Elin Electronics", exchange: "NSE", sector: "Capital Goods", industry: "EMS" },
  { symbol: "CARBORUNIV", name: "Carborundum Universal", exchange: "NSE", sector: "Capital Goods", industry: "Abrasives" },
  { symbol: "GRINDWELL", name: "Grindwell Norton", exchange: "NSE", sector: "Capital Goods", industry: "Abrasives" },
  { symbol: "AIAENG", name: "AIA Engineering", exchange: "NSE", sector: "Capital Goods", industry: "Grinding Media" },
  { symbol: "ELGIEQUIP", name: "Elgi Equipments", exchange: "NSE", sector: "Capital Goods", industry: "Compressors" },
  { symbol: "INGERRAND", name: "Ingersoll Rand India", exchange: "NSE", sector: "Capital Goods", industry: "Compressors" },
  { symbol: "PRAJIND", name: "Praj Industries", exchange: "NSE", sector: "Capital Goods", industry: "Ethanol Plants" },
  { symbol: "TRITURBINE", name: "Triveni Turbine", exchange: "NSE", sector: "Capital Goods", industry: "Turbines" },
  { symbol: "ISGEC", name: "ISGEC Heavy Engineering", exchange: "NSE", sector: "Capital Goods", industry: "Heavy Engineering" },
  { symbol: "VAIBHAVGBL", name: "Vaibhav Global", exchange: "NSE", sector: "Consumer", industry: "Jewellery" },
  { symbol: "ELECON", name: "Elecon Engineering", exchange: "NSE", sector: "Capital Goods", industry: "Industrial Gears" },
  { symbol: "SHAKTIPUMP", name: "Shakti Pumps", exchange: "NSE", sector: "Capital Goods", industry: "Pumps" },
  { symbol: "KSB", name: "KSB", exchange: "NSE", sector: "Capital Goods", industry: "Pumps" },
  { symbol: "ADANIENSOL", name: "Adani Energy Solutions", exchange: "NSE", sector: "Power", industry: "Transmission" },
  { symbol: "RVNL", name: "Rail Vikas Nigam", exchange: "NSE", sector: "Infrastructure", industry: "Railways" },
  { symbol: "IRCON", name: "Ircon International", exchange: "NSE", sector: "Infrastructure", industry: "Railways" },
  { symbol: "RITES", name: "RITES", exchange: "NSE", sector: "Infrastructure", industry: "Railway Consultancy" },
  { symbol: "TITAGARH", name: "Titagarh Rail Systems", exchange: "NSE", sector: "Capital Goods", industry: "Railway Wagons" },
  { symbol: "TEXRAIL", name: "Texmaco Rail & Engineering", exchange: "NSE", sector: "Capital Goods", industry: "Railway Wagons" },
  { symbol: "JWL", name: "Jupiter Wagons", exchange: "NSE", sector: "Capital Goods", industry: "Railway Wagons" },
  { symbol: "KEC", name: "KEC International", exchange: "NSE", sector: "Infrastructure", industry: "Transmission EPC" },
  { symbol: "KALPATPOWR", name: "Kalpataru Projects International", exchange: "NSE", sector: "Infrastructure", industry: "Transmission EPC" },
  { symbol: "HCC", name: "Hindustan Construction", exchange: "NSE", sector: "Infrastructure", industry: "Construction" },
  { symbol: "DBL", name: "Dilip Buildcon", exchange: "NSE", sector: "Infrastructure", industry: "Roads" },
  { symbol: "HGINFRA", name: "H.G. Infra Engineering", exchange: "NSE", sector: "Infrastructure", industry: "Roads" },
  { symbol: "GRINFRA", name: "GR Infraprojects", exchange: "NSE", sector: "Infrastructure", industry: "Roads" },
  { symbol: "ASHOKA", name: "Ashoka Buildcon", exchange: "NSE", sector: "Infrastructure", industry: "Roads" },
  { symbol: "JKIL", name: "J Kumar Infraprojects", exchange: "NSE", sector: "Infrastructure", industry: "Construction" },
  { symbol: "ITDC", name: "India Tourism Development", exchange: "NSE", sector: "Consumer", industry: "Hotels" },
  { symbol: "ENGINERSIN", name: "Engineers India", exchange: "NSE", sector: "Infrastructure", industry: "Consultancy" },
  { symbol: "MAHINDCIE", name: "CIE Automotive India", exchange: "NSE", sector: "Auto", industry: "Auto Components" },
  { symbol: "SOBHA", name: "Sobha", exchange: "NSE", sector: "Realty", industry: "Real Estate" },
  { symbol: "LODHA", name: "Macrotech Developers (Lodha)", exchange: "NSE", sector: "Realty", industry: "Real Estate" },
  { symbol: "SUNTECK", name: "Sunteck Realty", exchange: "NSE", sector: "Realty", industry: "Real Estate" },
  { symbol: "ANANTRAJ", name: "Anant Raj", exchange: "NSE", sector: "Realty", industry: "Real Estate" },
  { symbol: "ARVSMART", name: "Arvind SmartSpaces", exchange: "NSE", sector: "Realty", industry: "Real Estate" },
  { symbol: "KOLTEPATIL", name: "Kolte-Patil Developers", exchange: "NSE", sector: "Realty", industry: "Real Estate" },
  { symbol: "DBREALTY", name: "D B Realty", exchange: "NSE", sector: "Realty", industry: "Real Estate" },
  { symbol: "MBLINFRA", name: "MBL Infrastructures", exchange: "NSE", sector: "Infrastructure", industry: "Construction" },
  { symbol: "EMBASSY", name: "Embassy Office Parks REIT", exchange: "NSE", sector: "Realty", industry: "REIT" },
  { symbol: "MINDSPACE", name: "Mindspace Business Parks REIT", exchange: "NSE", sector: "Realty", industry: "REIT" },
  { symbol: "BIRET", name: "Brookfield India REIT", exchange: "NSE", sector: "Realty", industry: "REIT" },
  { symbol: "GATI", name: "Gati", exchange: "NSE", sector: "Logistics", industry: "Express Logistics" },
  { symbol: "TCIEXP", name: "TCI Express", exchange: "NSE", sector: "Logistics", industry: "Express Logistics" },
  { symbol: "MAHLOGIST", name: "Mahindra Logistics", exchange: "NSE", sector: "Logistics", industry: "3PL" },
  { symbol: "VRLLOG", name: "VRL Logistics", exchange: "NSE", sector: "Logistics", industry: "Road Logistics" },
  { symbol: "ALLCARGO", name: "Allcargo Logistics", exchange: "NSE", sector: "Logistics", industry: "Logistics" },
  { symbol: "GESHIP", name: "Great Eastern Shipping", exchange: "NSE", sector: "Logistics", industry: "Shipping" },
  { symbol: "SCI", name: "Shipping Corporation of India", exchange: "NSE", sector: "Logistics", industry: "Shipping" },
  { symbol: "ESSARSHPNG", name: "Essar Shipping", exchange: "NSE", sector: "Logistics", industry: "Shipping" },
  { symbol: "JSWINFRA", name: "JSW Infrastructure", exchange: "NSE", sector: "Logistics", industry: "Ports" },
  { symbol: "GUJPPL", name: "Gujarat Pipavav Port", exchange: "NSE", sector: "Logistics", industry: "Ports" },
  { symbol: "RAYMOND", name: "Raymond", exchange: "NSE", sector: "Textiles", industry: "Apparel" },
  { symbol: "ARVIND", name: "Arvind", exchange: "NSE", sector: "Textiles", industry: "Denim & Apparel" },
  { symbol: "INDOCOUNT", name: "Indo Count Industries", exchange: "NSE", sector: "Textiles", industry: "Home Textiles" },
  { symbol: "HIMATSEIDE", name: "Himatsingka Seide", exchange: "NSE", sector: "Textiles", industry: "Home Textiles" },
  { symbol: "GOKEX", name: "Gokaldas Exports", exchange: "NSE", sector: "Textiles", industry: "Garments Export" },
  { symbol: "GARFIBRES", name: "Garware Technical Fibres", exchange: "NSE", sector: "Textiles", industry: "Technical Textiles" },
  { symbol: "KPRMILL", name: "K.P.R. Mill", exchange: "NSE", sector: "Textiles", industry: "Garments" },
  { symbol: "SPMLIND", name: "S P Apparels", exchange: "NSE", sector: "Textiles", industry: "Garments" },
  { symbol: "PEARLGLOB", name: "Pearl Global Industries", exchange: "NSE", sector: "Textiles", industry: "Garments" },
  { symbol: "FILATEX", name: "Filatex India", exchange: "NSE", sector: "Textiles", industry: "Polyester Yarn" },
  { symbol: "BALRAMCHIN", name: "Balrampur Chini Mills", exchange: "NSE", sector: "Agri", industry: "Sugar" },
  { symbol: "BAJAJHIND", name: "Bajaj Hindusthan Sugar", exchange: "NSE", sector: "Agri", industry: "Sugar" },
  { symbol: "TRIVENI", name: "Triveni Engineering & Industries", exchange: "NSE", sector: "Agri", industry: "Sugar" },
  { symbol: "DHAMPURSUG", name: "Dhampur Sugar Mills", exchange: "NSE", sector: "Agri", industry: "Sugar" },
  { symbol: "DWARKESH", name: "Dwarikesh Sugar Industries", exchange: "NSE", sector: "Agri", industry: "Sugar" },
  { symbol: "DALMIASUG", name: "Dalmia Bharat Sugar", exchange: "NSE", sector: "Agri", industry: "Sugar" },
  { symbol: "RENUKA", name: "Shree Renuka Sugars", exchange: "NSE", sector: "Agri", industry: "Sugar" },
  { symbol: "KRBL", name: "KRBL", exchange: "NSE", sector: "Agri", industry: "Basmati Rice" },
  { symbol: "LTFOODS", name: "LT Foods", exchange: "NSE", sector: "Agri", industry: "Basmati Rice" },
  { symbol: "KAVERIAGRI", name: "Kaveri Seed Company", exchange: "NSE", sector: "Agri", industry: "Seeds" },
  { symbol: "GODREJAGRO", name: "Godrej Agrovet", exchange: "NSE", sector: "Agri", industry: "Animal Feed" },
  { symbol: "AVANTIFEED", name: "Avanti Feeds", exchange: "NSE", sector: "Agri", industry: "Shrimp Feed" },
  { symbol: "WATERBASE", name: "Waterbase", exchange: "NSE", sector: "Agri", industry: "Shrimp Feed" },
  { symbol: "HERITGFOOD", name: "Heritage Foods", exchange: "NSE", sector: "FMCG", industry: "Dairy" },
  { symbol: "DODLA", name: "Dodla Dairy", exchange: "NSE", sector: "FMCG", industry: "Dairy" },
  { symbol: "PARAGMILK", name: "Parag Milk Foods", exchange: "NSE", sector: "FMCG", industry: "Dairy" },
  { symbol: "GRINDWELLN", name: "Grindwell Norton", exchange: "NSE", sector: "Capital Goods", industry: "Abrasives" },
  { symbol: "3MINDIA", name: "3M India", exchange: "NSE", sector: "Other", industry: "Diversified" },
  { symbol: "JINDWORLD", name: "Jindal Worldwide", exchange: "NSE", sector: "Textiles", industry: "Denim" },
  { symbol: "TVTODAY", name: "TV Today Network", exchange: "NSE", sector: "Media", industry: "News" },
  { symbol: "EIDPARRY", name: "EID Parry India", exchange: "NSE", sector: "Agri", industry: "Sugar" },
  { symbol: "ORIENTHOT", name: "Oriental Hotels", exchange: "NSE", sector: "Consumer", industry: "Hotels" },
  { symbol: "RHIM", name: "RHI Magnesita India", exchange: "NSE", sector: "Other", industry: "Refractories" },
  { symbol: "VESUVIUS", name: "Vesuvius India", exchange: "NSE", sector: "Other", industry: "Refractories" },
  { symbol: "EVEREADY", name: "Eveready Industries India", exchange: "NSE", sector: "Consumer", industry: "Batteries" },
  { symbol: "STYLAMIND", name: "Stylam Industries", exchange: "NSE", sector: "Other", industry: "Laminates" },
  { symbol: "GREENPLY", name: "Greenply Industries", exchange: "NSE", sector: "Other", industry: "Plywood" },
  { symbol: "CENTURYPLY", name: "Century Plyboards", exchange: "NSE", sector: "Other", industry: "Plywood" },
  { symbol: "GREENLAM", name: "Greenlam Industries", exchange: "NSE", sector: "Other", industry: "Laminates" },
  { symbol: "CERA", name: "Cera Sanitaryware", exchange: "NSE", sector: "Consumer", industry: "Sanitaryware" },
  { symbol: "HSIL", name: "HSIL", exchange: "NSE", sector: "Consumer", industry: "Sanitaryware" },
  { symbol: "SOMANYCERA", name: "Somany Ceramics", exchange: "NSE", sector: "Consumer", industry: "Ceramic Tiles" },
  { symbol: "ASIANTILES", name: "Asian Granito India", exchange: "NSE", sector: "Consumer", industry: "Ceramic Tiles" },
  { symbol: "PRAGE", name: "Prataap Snacks", exchange: "NSE", sector: "FMCG", industry: "Snacks" },
  { symbol: "BLISSGVS", name: "Bliss GVS Pharma", exchange: "NSE", sector: "Pharma", industry: "Pharmaceuticals" },
  { symbol: "MOREPENLAB", name: "Morepen Laboratories", exchange: "NSE", sector: "Pharma", industry: "API" },
  { symbol: "IOLCP", name: "IOL Chemicals & Pharmaceuticals", exchange: "NSE", sector: "Pharma", industry: "API" },
  { symbol: "ABCAPITAL2", name: "Aditya Birla Money", exchange: "NSE", sector: "NBFC", industry: "Capital Markets" },
  { symbol: "SCHNEIDER", name: "Schneider Electric Infra", exchange: "NSE", sector: "Capital Goods", industry: "Electrical Equipment" },
  { symbol: "GENUSPOWER", name: "Genus Power Infrastructures", exchange: "NSE", sector: "Capital Goods", industry: "Smart Meters" },
  { symbol: "HBLPOWER", name: "HBL Power Systems", exchange: "NSE", sector: "Capital Goods", industry: "Batteries" },
  { symbol: "PGEL", name: "PG Electroplast", exchange: "NSE", sector: "Capital Goods", industry: "EMS" },
  { symbol: "AVALON", name: "Avalon Technologies", exchange: "NSE", sector: "Capital Goods", industry: "EMS" },
  { symbol: "CYIENTDLM", name: "Cyient DLM", exchange: "NSE", sector: "Capital Goods", industry: "EMS" },
  { symbol: "VOLTAMP", name: "Voltamp Transformers", exchange: "NSE", sector: "Capital Goods", industry: "Transformers" },
  { symbol: "TRIL", name: "Transformers & Rectifiers India", exchange: "NSE", sector: "Capital Goods", industry: "Transformers" },
  { symbol: "BHARATGEAR", name: "Bharat Gears", exchange: "NSE", sector: "Capital Goods", industry: "Industrial Gears" },
  { symbol: "ROLEXRINGS", name: "Rolex Rings", exchange: "NSE", sector: "Capital Goods", industry: "Bearings" },
  { symbol: "VEDANTFASH", name: "Vedant Fashions (Manyavar)", exchange: "NSE", sector: "Consumer", industry: "Apparel" },
  { symbol: "GO_FASHION", name: "Go Fashion India", exchange: "NSE", sector: "Consumer", industry: "Apparel Retail" },
  { symbol: "HONASA", name: "Honasa Consumer (Mamaearth)", exchange: "NSE", sector: "FMCG", industry: "Personal Care" },
  { symbol: "JUBLPHARM", name: "Jubilant Pharmova", exchange: "NSE", sector: "Pharma", industry: "Pharmaceuticals" },
  { symbol: "ENTERO", name: "Entero Healthcare Solutions", exchange: "NSE", sector: "Pharma", industry: "Distribution" },
  { symbol: "GOPALSNACK", name: "Gopal Snacks", exchange: "NSE", sector: "FMCG", industry: "Snacks" },
  { symbol: "JUNIPER", name: "Juniper Hotels", exchange: "NSE", sector: "Consumer", industry: "Hotels" },
  { symbol: "ANUP", name: "Anup Engineering", exchange: "NSE", sector: "Capital Goods", industry: "Process Equipment" },
  { symbol: "AETHER", name: "Aether Industries", exchange: "NSE", sector: "Chemicals", industry: "Specialty Chemicals" },
  { symbol: "GLOBUSSPR", name: "Globus Spirits", exchange: "NSE", sector: "FMCG", industry: "Spirits" },
  { symbol: "POKARNA", name: "Pokarna", exchange: "NSE", sector: "Other", industry: "Quartz Surfaces" },

];

export const ALL_SECTORS: Sector[] = [
  "IT", "Banks", "NBFC", "Auto", "Pharma", "FMCG", "Energy", "Metals",
  "Telecom", "Cement", "Power", "Insurance", "Consumer", "Realty",
  "Capital Goods", "Chemicals", "Infrastructure", "Media", "Logistics",
  "Textiles", "Agri", "Other",
];

export function searchSymbols(query: string, limit = 10): SymbolEntry[] {
  const q = query.trim().toUpperCase();
  if (!q) return [];
  return NSE_SYMBOLS.filter(
    (s) => s.symbol.startsWith(q) || s.name.toUpperCase().includes(q),
  ).slice(0, limit);
}

export function allIndustries(): string[] {
  const set = new Set<string>();
  for (const s of NSE_SYMBOLS) if (s.industry) set.add(s.industry);
  return [...set].sort();
}
