// Lightweight subset of NSE_SYMBOLS for client bundles.
// Keep ~top 300 by market cap / popularity, fields trimmed to essentials.
import type { Sector } from "./nse-symbols";

export type SymbolLite = {
  symbol: string;
  name: string;
  exchange: "NSE" | "BSE";
  sector?: Sector;
};

export const NSE_SYMBOLS_LITE: SymbolLite[] = [
  { symbol: "RELIANCE", name: "Reliance Industries", exchange: "NSE", sector: "Energy" },
  { symbol: "TCS", name: "Tata Consultancy Services", exchange: "NSE", sector: "IT" },
  { symbol: "HDFCBANK", name: "HDFC Bank", exchange: "NSE", sector: "Banks" },
  { symbol: "ICICIBANK", name: "ICICI Bank", exchange: "NSE", sector: "Banks" },
  { symbol: "INFY", name: "Infosys", exchange: "NSE", sector: "IT" },
  { symbol: "HINDUNILVR", name: "Hindustan Unilever", exchange: "NSE", sector: "FMCG" },
  { symbol: "ITC", name: "ITC", exchange: "NSE", sector: "FMCG" },
  { symbol: "SBIN", name: "State Bank of India", exchange: "NSE", sector: "Banks" },
  { symbol: "BHARTIARTL", name: "Bharti Airtel", exchange: "NSE", sector: "Telecom" },
  { symbol: "LT", name: "Larsen & Toubro", exchange: "NSE", sector: "Capital Goods" },
  { symbol: "KOTAKBANK", name: "Kotak Mahindra Bank", exchange: "NSE", sector: "Banks" },
  { symbol: "AXISBANK", name: "Axis Bank", exchange: "NSE", sector: "Banks" },
  { symbol: "ASIANPAINT", name: "Asian Paints", exchange: "NSE", sector: "Consumer" },
  { symbol: "MARUTI", name: "Maruti Suzuki", exchange: "NSE", sector: "Auto" },
  { symbol: "TITAN", name: "Titan Company", exchange: "NSE", sector: "Consumer" },
  { symbol: "SUNPHARMA", name: "Sun Pharmaceutical", exchange: "NSE", sector: "Pharma" },
  { symbol: "ULTRACEMCO", name: "UltraTech Cement", exchange: "NSE", sector: "Cement" },
  { symbol: "WIPRO", name: "Wipro", exchange: "NSE", sector: "IT" },
  { symbol: "HCLTECH", name: "HCL Technologies", exchange: "NSE", sector: "IT" },
  { symbol: "NESTLEIND", name: "Nestle India", exchange: "NSE", sector: "FMCG" },
  { symbol: "TMPV", name: "Tata Motors Passenger Vehicles", exchange: "NSE", sector: "Auto" },
  { symbol: "M&M", name: "Mahindra & Mahindra", exchange: "NSE", sector: "Auto" },
  { symbol: "BAJFINANCE", name: "Bajaj Finance", exchange: "NSE", sector: "NBFC" },
  { symbol: "BAJAJFINSV", name: "Bajaj Finserv", exchange: "NSE", sector: "NBFC" },
  { symbol: "POWERGRID", name: "Power Grid Corporation", exchange: "NSE", sector: "Power" },
  { symbol: "NTPC", name: "NTPC", exchange: "NSE", sector: "Power" },
  { symbol: "ONGC", name: "ONGC", exchange: "NSE", sector: "Energy" },
  { symbol: "JSWSTEEL", name: "JSW Steel", exchange: "NSE", sector: "Metals" },
  { symbol: "TATASTEEL", name: "Tata Steel", exchange: "NSE", sector: "Metals" },
  { symbol: "COALINDIA", name: "Coal India", exchange: "NSE", sector: "Energy" },
  { symbol: "ADANIENT", name: "Adani Enterprises", exchange: "NSE", sector: "Other" },
  { symbol: "ADANIPORTS", name: "Adani Ports & SEZ", exchange: "NSE", sector: "Logistics" },
  { symbol: "HDFCLIFE", name: "HDFC Life Insurance", exchange: "NSE", sector: "Insurance" },
  { symbol: "SBILIFE", name: "SBI Life Insurance", exchange: "NSE", sector: "Insurance" },
  { symbol: "BAJAJ-AUTO", name: "Bajaj Auto", exchange: "NSE", sector: "Auto" },
  { symbol: "EICHERMOT", name: "Eicher Motors", exchange: "NSE", sector: "Auto" },
  { symbol: "HEROMOTOCO", name: "Hero MotoCorp", exchange: "NSE", sector: "Auto" },
  { symbol: "TVSMOTOR", name: "TVS Motor", exchange: "NSE", sector: "Auto" },
  { symbol: "DRREDDY", name: "Dr Reddy's Labs", exchange: "NSE", sector: "Pharma" },
  { symbol: "CIPLA", name: "Cipla", exchange: "NSE", sector: "Pharma" },
  { symbol: "DIVISLAB", name: "Divi's Laboratories", exchange: "NSE", sector: "Pharma" },
  { symbol: "APOLLOHOSP", name: "Apollo Hospitals", exchange: "NSE", sector: "Pharma" },
  { symbol: "BRITANNIA", name: "Britannia Industries", exchange: "NSE", sector: "FMCG" },
  { symbol: "DABUR", name: "Dabur India", exchange: "NSE", sector: "FMCG" },
  { symbol: "GODREJCP", name: "Godrej Consumer", exchange: "NSE", sector: "FMCG" },
  { symbol: "MARICO", name: "Marico", exchange: "NSE", sector: "FMCG" },
  { symbol: "TATACONSUM", name: "Tata Consumer Products", exchange: "NSE", sector: "FMCG" },
  { symbol: "COLPAL", name: "Colgate-Palmolive India", exchange: "NSE", sector: "FMCG" },
  { symbol: "PIDILITIND", name: "Pidilite Industries", exchange: "NSE", sector: "Chemicals" },
  { symbol: "BERGEPAINT", name: "Berger Paints", exchange: "NSE", sector: "Consumer" },
  { symbol: "HAVELLS", name: "Havells India", exchange: "NSE", sector: "Consumer" },
  { symbol: "DLF", name: "DLF", exchange: "NSE", sector: "Realty" },
  { symbol: "GODREJPROP", name: "Godrej Properties", exchange: "NSE", sector: "Realty" },
  { symbol: "OBEROIRLTY", name: "Oberoi Realty", exchange: "NSE", sector: "Realty" },
  { symbol: "INDUSINDBK", name: "IndusInd Bank", exchange: "NSE", sector: "Banks" },
  { symbol: "FEDERALBNK", name: "Federal Bank", exchange: "NSE", sector: "Banks" },
  { symbol: "IDFCFIRSTB", name: "IDFC First Bank", exchange: "NSE", sector: "Banks" },
  { symbol: "AUBANK", name: "AU Small Finance Bank", exchange: "NSE", sector: "Banks" },
  { symbol: "BANKBARODA", name: "Bank of Baroda", exchange: "NSE", sector: "Banks" },
  { symbol: "PNB", name: "Punjab National Bank", exchange: "NSE", sector: "Banks" },
  { symbol: "CANBK", name: "Canara Bank", exchange: "NSE", sector: "Banks" },
  { symbol: "UNIONBANK", name: "Union Bank of India", exchange: "NSE", sector: "Banks" },
  { symbol: "RECLTD", name: "REC", exchange: "NSE", sector: "NBFC" },
  { symbol: "PFC", name: "Power Finance Corp", exchange: "NSE", sector: "NBFC" },
  { symbol: "CHOLAFIN", name: "Cholamandalam Inv & Fin", exchange: "NSE", sector: "NBFC" },
  { symbol: "SHRIRAMFIN", name: "Shriram Finance", exchange: "NSE", sector: "NBFC" },
  { symbol: "MUTHOOTFIN", name: "Muthoot Finance", exchange: "NSE", sector: "NBFC" },
  { symbol: "BAJAJHLDNG", name: "Bajaj Holdings", exchange: "NSE", sector: "NBFC" },
  { symbol: "LICI", name: "Life Insurance Corp", exchange: "NSE", sector: "Insurance" },
  { symbol: "ICICIGI", name: "ICICI Lombard General Insurance", exchange: "NSE", sector: "Insurance" },
  { symbol: "ICICIPRULI", name: "ICICI Prudential Life", exchange: "NSE", sector: "Insurance" },
  { symbol: "TECHM", name: "Tech Mahindra", exchange: "NSE", sector: "IT" },
  { symbol: "LTM", name: "LTIMindtree", exchange: "NSE", sector: "IT" },
  { symbol: "LTTS", name: "L&T Technology Services", exchange: "NSE", sector: "IT" },
  { symbol: "MPHASIS", name: "Mphasis", exchange: "NSE", sector: "IT" },
  { symbol: "PERSISTENT", name: "Persistent Systems", exchange: "NSE", sector: "IT" },
  { symbol: "COFORGE", name: "Coforge", exchange: "NSE", sector: "IT" },
  { symbol: "KPITTECH", name: "KPIT Technologies", exchange: "NSE", sector: "IT" },
  { symbol: "OFSS", name: "Oracle Financial Services", exchange: "NSE", sector: "IT" },
  { symbol: "TATAELXSI", name: "Tata Elxsi", exchange: "NSE", sector: "IT" },
  { symbol: "ETERNAL", name: "Eternal (Zomato)", exchange: "NSE", sector: "Consumer" },
  { symbol: "NYKAA", name: "FSN E-Commerce (Nykaa)", exchange: "NSE", sector: "Consumer" },
  { symbol: "PAYTM", name: "One97 Communications (Paytm)", exchange: "NSE", sector: "IT" },
  { symbol: "POLICYBZR", name: "PB Fintech (PolicyBazaar)", exchange: "NSE", sector: "Insurance" },
  { symbol: "DMART", name: "Avenue Supermarts (DMart)", exchange: "NSE", sector: "Consumer" },
  { symbol: "TRENT", name: "Trent", exchange: "NSE", sector: "Consumer" },
  { symbol: "JUBLFOOD", name: "Jubilant Foodworks", exchange: "NSE", sector: "Consumer" },
  { symbol: "VBL", name: "Varun Beverages", exchange: "NSE", sector: "FMCG" },
  { symbol: "UBL", name: "United Breweries", exchange: "NSE", sector: "FMCG" },
  { symbol: "UNITDSPR", name: "United Spirits", exchange: "NSE", sector: "FMCG" },
  { symbol: "PIIND", name: "PI Industries", exchange: "NSE", sector: "Chemicals" },
  { symbol: "DEEPAKNTR", name: "Deepak Nitrite", exchange: "NSE", sector: "Chemicals" },
  { symbol: "SRF", name: "SRF", exchange: "NSE", sector: "Chemicals" },
  { symbol: "AARTIIND", name: "Aarti Industries", exchange: "NSE", sector: "Chemicals" },
  { symbol: "UPL", name: "UPL", exchange: "NSE", sector: "Chemicals" },
  { symbol: "VEDL", name: "Vedanta", exchange: "NSE", sector: "Metals" },
  { symbol: "HINDALCO", name: "Hindalco Industries", exchange: "NSE", sector: "Metals" },
  { symbol: "JINDALSTEL", name: "Jindal Steel & Power", exchange: "NSE", sector: "Metals" },
  { symbol: "SAIL", name: "Steel Authority of India", exchange: "NSE", sector: "Metals" },
  { symbol: "NMDC", name: "NMDC", exchange: "NSE", sector: "Metals" },
  { symbol: "HINDZINC", name: "Hindustan Zinc", exchange: "NSE", sector: "Metals" },
  { symbol: "NATIONALUM", name: "National Aluminium", exchange: "NSE", sector: "Metals" },
  { symbol: "MOIL", name: "MOIL", exchange: "NSE", sector: "Metals" },
  { symbol: "GRASIM", name: "Grasim Industries", exchange: "NSE", sector: "Cement" },
  { symbol: "AMBUJACEM", name: "Ambuja Cements", exchange: "NSE", sector: "Cement" },
  { symbol: "ACC", name: "ACC", exchange: "NSE", sector: "Cement" },
  { symbol: "SHREECEM", name: "Shree Cement", exchange: "NSE", sector: "Cement" },
  { symbol: "DALBHARAT", name: "Dalmia Bharat", exchange: "NSE", sector: "Cement" },
  { symbol: "JKCEMENT", name: "JK Cement", exchange: "NSE", sector: "Cement" },
  { symbol: "RAMCOCEM", name: "Ramco Cements", exchange: "NSE", sector: "Cement" },
  { symbol: "IOC", name: "Indian Oil Corp", exchange: "NSE", sector: "Energy" },
  { symbol: "BPCL", name: "Bharat Petroleum", exchange: "NSE", sector: "Energy" },
  { symbol: "HINDPETRO", name: "Hindustan Petroleum", exchange: "NSE", sector: "Energy" },
  { symbol: "GAIL", name: "GAIL India", exchange: "NSE", sector: "Energy" },
  { symbol: "PETRONET", name: "Petronet LNG", exchange: "NSE", sector: "Energy" },
  { symbol: "OIL", name: "Oil India", exchange: "NSE", sector: "Energy" },
  { symbol: "IGL", name: "Indraprastha Gas", exchange: "NSE", sector: "Energy" },
  { symbol: "MGL", name: "Mahanagar Gas", exchange: "NSE", sector: "Energy" },
  { symbol: "TATAPOWER", name: "Tata Power", exchange: "NSE", sector: "Power" },
  { symbol: "ADANIPOWER", name: "Adani Power", exchange: "NSE", sector: "Power" },
  { symbol: "ADANIGREEN", name: "Adani Green Energy", exchange: "NSE", sector: "Power" },
  { symbol: "JSWENERGY", name: "JSW Energy", exchange: "NSE", sector: "Power" },
  { symbol: "TORNTPOWER", name: "Torrent Power", exchange: "NSE", sector: "Power" },
  { symbol: "NHPC", name: "NHPC", exchange: "NSE", sector: "Power" },
  { symbol: "SJVN", name: "SJVN", exchange: "NSE", sector: "Power" },
  { symbol: "SIEMENS", name: "Siemens", exchange: "NSE", sector: "Capital Goods" },
  { symbol: "ABB", name: "ABB India", exchange: "NSE", sector: "Capital Goods" },
  { symbol: "BHEL", name: "BHEL", exchange: "NSE", sector: "Capital Goods" },
  { symbol: "BEL", name: "Bharat Electronics", exchange: "NSE", sector: "Capital Goods" },
  { symbol: "HAL", name: "Hindustan Aeronautics", exchange: "NSE", sector: "Capital Goods" },
  { symbol: "CUMMINSIND", name: "Cummins India", exchange: "NSE", sector: "Capital Goods" },
  { symbol: "THERMAX", name: "Thermax", exchange: "NSE", sector: "Capital Goods" },
  { symbol: "POLYCAB", name: "Polycab India", exchange: "NSE", sector: "Capital Goods" },
  { symbol: "KEI", name: "KEI Industries", exchange: "NSE", sector: "Capital Goods" },
  { symbol: "VOLTAS", name: "Voltas", exchange: "NSE", sector: "Consumer" },
  { symbol: "CROMPTON", name: "Crompton Greaves Consumer", exchange: "NSE", sector: "Consumer" },
  { symbol: "WHIRLPOOL", name: "Whirlpool India", exchange: "NSE", sector: "Consumer" },
  { symbol: "DIXON", name: "Dixon Technologies", exchange: "NSE", sector: "IT" },
  { symbol: "AMBER", name: "Amber Enterprises", exchange: "NSE", sector: "Capital Goods" },
  { symbol: "BOSCHLTD", name: "Bosch", exchange: "NSE", sector: "Auto" },
  { symbol: "MOTHERSON", name: "Samvardhana Motherson", exchange: "NSE", sector: "Auto" },
  { symbol: "BHARATFORG", name: "Bharat Forge", exchange: "NSE", sector: "Auto" },
  { symbol: "BALKRISIND", name: "Balkrishna Industries", exchange: "NSE", sector: "Auto" },
  { symbol: "MRF", name: "MRF", exchange: "NSE", sector: "Auto" },
  { symbol: "APOLLOTYRE", name: "Apollo Tyres", exchange: "NSE", sector: "Auto" },
  { symbol: "CEATLTD", name: "CEAT", exchange: "NSE", sector: "Auto" },
  { symbol: "ASHOKLEY", name: "Ashok Leyland", exchange: "NSE", sector: "Auto" },
  { symbol: "EXIDEIND", name: "Exide Industries", exchange: "NSE", sector: "Auto" },
  { symbol: "LUPIN", name: "Lupin", exchange: "NSE", sector: "Pharma" },
  { symbol: "AUROPHARMA", name: "Aurobindo Pharma", exchange: "NSE", sector: "Pharma" },
  { symbol: "TORNTPHARM", name: "Torrent Pharma", exchange: "NSE", sector: "Pharma" },
  { symbol: "ALKEM", name: "Alkem Laboratories", exchange: "NSE", sector: "Pharma" },
  { symbol: "ZYDUSLIFE", name: "Zydus Lifesciences", exchange: "NSE", sector: "Pharma" },
  { symbol: "BIOCON", name: "Biocon", exchange: "NSE", sector: "Pharma" },
  { symbol: "GLENMARK", name: "Glenmark Pharma", exchange: "NSE", sector: "Pharma" },
  { symbol: "MANKIND", name: "Mankind Pharma", exchange: "NSE", sector: "Pharma" },
  { symbol: "ABBOTINDIA", name: "Abbott India", exchange: "NSE", sector: "Pharma" },
  { symbol: "MAXHEALTH", name: "Max Healthcare", exchange: "NSE", sector: "Pharma" },
  { symbol: "FORTIS", name: "Fortis Healthcare", exchange: "NSE", sector: "Pharma" },
  { symbol: "METROPOLIS", name: "Metropolis Healthcare", exchange: "NSE", sector: "Pharma" },
  { symbol: "IDEA", name: "Vodafone Idea", exchange: "NSE", sector: "Telecom" },
  { symbol: "INDIGO", name: "InterGlobe Aviation", exchange: "NSE", sector: "Logistics" },
  { symbol: "CONCOR", name: "Container Corp", exchange: "NSE", sector: "Logistics" },
  { symbol: "DELHIVERY", name: "Delhivery", exchange: "NSE", sector: "Logistics" },
  { symbol: "BLUEDART", name: "Blue Dart Express", exchange: "NSE", sector: "Logistics" },
  { symbol: "BSE", name: "BSE", exchange: "NSE", sector: "Other" },
  { symbol: "MCX", name: "Multi Commodity Exchange", exchange: "NSE", sector: "Other" },
  { symbol: "CDSL", name: "CDSL", exchange: "NSE", sector: "Other" },
  { symbol: "IRCTC", name: "IRCTC", exchange: "NSE", sector: "Other" },
  { symbol: "IRFC", name: "Indian Railway Finance", exchange: "NSE", sector: "NBFC" },
  { symbol: "MAZDOCK", name: "Mazagon Dock Shipbuilders", exchange: "NSE", sector: "Capital Goods" },
  { symbol: "COCHINSHIP", name: "Cochin Shipyard", exchange: "NSE", sector: "Capital Goods" },
  { symbol: "GRSE", name: "Garden Reach Shipbuilders", exchange: "NSE", sector: "Capital Goods" },
  { symbol: "BDL", name: "Bharat Dynamics", exchange: "NSE", sector: "Capital Goods" },
  { symbol: "ZEEL", name: "Zee Entertainment", exchange: "NSE", sector: "Media" },
  { symbol: "SUNTV", name: "Sun TV Network", exchange: "NSE", sector: "Media" },
  { symbol: "PVRINOX", name: "PVR Inox", exchange: "NSE", sector: "Media" },
];

export function searchSymbolsLite(query: string, limit = 8): SymbolLite[] {
  const q = query.trim().toUpperCase();
  if (!q) return [];
  return NSE_SYMBOLS_LITE.filter(
    (s) => s.symbol.startsWith(q) || s.name.toUpperCase().includes(q),
  ).slice(0, limit);
}
